### ISSUE TITLE
[Python]: Expose Dataframe.schema() to Python binding

### ISSUE THREAD

**Issue by mmuru** [apache/datafusion#1007]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

In Python, trying to get schema from Dataframe but it is not available in Python binding. Ideally, we should expose all the dataframe methods in Python binding. 

**Describe the solution you'd like**
In Python, I should able to get schema from dataframe.

**Describe alternatives you've considered**

**Additional context**

**Comment by mmuru** [comment]
@houqp: I reviewed the current implementation schema() in dataframe_impl.rs and it returns &DFSchema. In Python, how do I return it? Please, review this request and provide your feedback. Thanks.

**Comment by houqp** [comment]
I haven't put a lot of thought into this, so take it with a grain of salt ;)

I think one possible solution would be creating a new wrapper struct that wraps the DFSchema type within the python crate, then annotate it with `pyclass` (https://pyo3.rs/master/class.html#defining-a-new-class) so the wrapper type can be returned directly to python. You won't be able to return a reference to python, so you need to clone the `&DFSchema` reference and store it inside the wrapper struct.

**Comment by drauschenbach** [comment]
This appears to be resolved. In `datafusion-python`, I can call `df.schema()`.

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
