### ISSUE TITLE
Deprecate TreeNode `transform_xx_mut` methods

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10097]
### Is your feature request related to a problem or challenge?

Part of #8913 

While working on the documentation in  https://github.com/apache/arrow-datafusion/pull/10035, @peter-toth made the great observation  https://github.com/apache/arrow-datafusion/pull/10035#discussion_r1562648720 that:

> I have no idea why we have the ..._mut() version, most likely for just convenience, but IMO one transform_down() with FnMut should be fair enough.

Specifically, these methods are basically the same, except that `_mut` takes a mutable reference to the closure
* `transform_down` / `transform_down_mut` 
* `transform_up` / `transform_up_mut` 

The current API is pretty confusing enough already (see discussion on https://github.com/apache/arrow-datafusion/pull/10035) so having redundant methods just makes it more confusing

Also, this terminology leaked into the LogicalPlan variants `transform_down_with_subqueries_mut` etc in https://github.com/apache/arrow-datafusion/pull/9913

### Describe the solution you'd like

I would like to deprecate

* `transform_down_mut` 
* `transform_up_mut` 

And remove the (yet unreleased) logical plan variants `transform_down_with_subqueries_mut` and `transform_up_with_subqueries_mut`

**Comment by peter-toth** [comment]
I'm happy to take this and file a PR.

**Comment by alamb** [comment]
Thanks @peter-toth 🙏 

I had a short play with it as well and it may be slightly tricker to sort out than I had imagined. However, I am sure you'll figure it out
