### ISSUE TITLE
Trigger the Sort Merge Join benchmark using the GitHub action

### ISSUE THREAD

**Issue by comphead** [apache/datafusion#10109]
Would be great to have an opportunity to trigger SMJ benches separately during CI/CD

The action has tpch hard coded here: https://github.com/apache/arrow-datafusion/blob/b54adb36b855f198b5098fdb3e4cdf1934818efd/.github/workflows/pr_benchmarks.yml#L41-L51

We could probably add SMJ (or maybe add another command like `/benchmark smj` 🤔

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/issues/10092#issuecomment-2059921298_

**Comment by getChan** [comment]
take
