### ISSUE TITLE
Old URL for  CLI docs page is showing 404

### ISSUE THREAD

**Issue by samuelcolvin** [apache/datafusion#10124]
### Describe the bug

The CLI docs are down - https://arrow.apache.org/datafusion/user-guide/cli.html they're just showing 404 "Not Found"

### To Reproduce

go to https://arrow.apache.org/datafusion/user-guide/cli.html

Work around is to use https://web.archive.org/web/20240227014509/https://arrow.apache.org/datafusion/user-guide/cli.html

### Expected behavior

see them

**Comment by tinfoil-knight** [comment]
@samuelcolvin Docs for CLI were recently moved to https://arrow.apache.org/datafusion/user-guide/cli/index.html in this PR: #10078

@alamb could we setup a redirect?

https://arrow.apache.org/datafusion/user-guide/cli.html is the URL that shows up in search results when looking for datafusion cli. Might confuse users to land on a missing page.

**Comment by samuelcolvin** [comment]
Thanks.

Redirect would be good.

**Comment by alamb** [comment]
Thanks -- yes @tinfoil-knight  and @samuelcolvin  -- a redirect (or even just a page saying the content moved with a link to the new site). Prs most welcome

**Comment by doupache** [comment]
@alamb @jayzhan211 
I would like to try this.

**Comment by doupache** [comment]
take

**Comment by alamb** [comment]
Thank you @doupache 🙏

**Comment by alamb** [comment]
(I hit this issue when google searching today so figured I would make a PR)

This is what I came up with : https://github.com/apache/datafusion/pull/10187

**Comment by alamb** [comment]
I double checked the link and it appears to be going to the right place now. Thank you for the report @samuelcolvin  -- sorry it took so long to fix
