### ISSUE TITLE
 Updates to the release scripts and associated documentation to be datafusion rather than arrow-datafusion

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10134]
Part of https://github.com/apache/arrow-datafusion/issues/9691

### Is your feature request related to a problem or challenge?

Now that DataFusion is its own top level apache project https://github.com/apache/arrow-datafusion/issues/9691#issuecomment-2063690461 we need to update the various release scripts

### Describe the solution you'd like

we need to update the release process scripts and documentation in 

 (link to reporter URL, mailing list name, and so on)

**Comment by andygrove** [comment]
I am working on this and will have a PR up today.

Also, I created https://dist.apache.org/repos/dist/dev/datafusion and added a KEYS file (copied from Arrow and removed non DataFusion PMC members)

**Comment by andygrove** [comment]
I also created https://dist.apache.org/repos/dist/release/datafusion and added KEYS there as well
