### ISSUE TITLE
[Display] show preserve_partitioning in sortExec 

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/datafusion#10138]
### Is your feature request related to a problem or challenge?

Now when print plan of one sql in datafusion:
```
SortExec: TopK(fetch=10000), expr=[NASME@0 ASC,VISITS@1 DESC NULLS LAST]
```
Its difficult to find out what the sort unit is : **sort in partition** or **sort in global**

### Describe the solution you'd like

display `preserve_partitioning` info in SortExec
like
 ```
SortExec: TopK(fetch=10000), expr=[NASME@0 ASC,VISITS@1 DESC NULLS LAST], preserve_partitioning=[true] 
```

**Comment by kavirajk** [comment]
take
