### ISSUE TITLE
Update committer list for new top level DataFusion project

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10154]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/9691

Now that the repos have been moved, we need to ensure the correct people have commit access -- as the DataFusion project is now distinct from Arrow the committers list did not move too

### Describe the solution you'd like

Ensure that the list of committers  on https://people.apache.org/phonebook.html?unix=datafusion

reflects the list on the proposal thread: https://lists.apache.org/thread/tv8s8ootxf7nrsp3vo1mt8mtxxt5qcor

**Comment by alamb** [comment]
I have updated whimsy to reflect the list on reflects the list on the [proposal thread](https://lists.apache.org/thread/tv8s8ootxf7nrsp3vo1mt8mtxxt5qcor)

https://whimsy.apache.org/roster/committee/datafusion#committers

![Screenshot 2024-04-20 at 3 53 23 PM](https://github.com/apache/datafusion/assets/490673/98d5b6ac-809e-4710-8aea-f49715be182e)


https://people.apache.org/phonebook.html?unix=datafusion doesn't yet seem to reflect these changes, so I'll leave this ticket open until it does

**Comment by viirya** [comment]
cc @sunchao The committer list is updated.

**Comment by alamb** [comment]
https://people.apache.org/phonebook.html?unix=datafusion

Now shows what I believe to be the correct list and reflects the [proposal thread](https://lists.apache.org/thread/tv8s8ootxf7nrsp3vo1mt8mtxxt5qcor). Please let me know if I missed anything else

```
datafusion (LDAP unix group)
Roster:

agrove	Andrew Grove	 
akurmustafa	Mustafa Akur	 
alamb	Andrew Lamb	 
avantgardner	Brent Gardner	 
comphead	Oleks V.	 
dheres	Daniël Heres	 
houqp	QP Hou	 
jakevin	Jie Wen	 
jayzhan	Jay Zhan	 
jeffreyvo	Jeffrey Vo	 
jiayuliu	Liu Jiayu	 
liukun	Kun Liu	 
mete	Metehan Yildirim	 
mingmwang	Wang Mingming	 
mneumann	Marco Neumann	 
nju_yaho	Zhong Yanghong	 
ozankabak	Mehmet Ozan Kabak	 
paddyhoran	Paddy Horan	 
rdettai	Rémi Dettai	 
sunchao	Sun Chao	 
thinkharderdev	Daniel Harris	 
tustvold	Raphael Taylor-Davies	 
viirya	L. C. Hsieh	 
wayne	Ruihang Xia	 
wesm	Wes McKinney	 
wjones127	Will Jones	 
xudong963	Xudong Wang	 
yangjiang	Yang Jiang	 
yjshen	Yijie Shen
```
