### ISSUE TITLE
Move coalesce function from math to core

### ISSUE THREAD

**Issue by Omega359** [apache/datafusion#10174]
### Is your feature request related to a problem or challenge?

Noted in https://github.com/apache/datafusion/pull/10098#discussion_r1573855338 the current location of the coalesce function isn't really the best place for it.

### Describe the solution you'd like

Coalesce function moved to core function module.

### Describe alternatives you've considered

Leave coalesce in place.

**Comment by xxxuuu** [comment]
I would like to give it a try :)

**Comment by xxxuuu** [comment]
take
