### ISSUE TITLE
`create table` fails in datafusion-cli with External error: Failed to convert path to URL: foo

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10182]
### Describe the bug

Something is wrong with datafusion-cli and creating external tables

### To Reproduce

```
andrewlamb@Andrews-MacBook-Pro:~/Software/arrow-datafusion$ datafusion-cli
DataFusion CLI v37.1.0
> create table foo (x varchar);
External error: Failed to convert path to URL: foo
> create table foo(x varchar) as values ('a');
External error: Failed to convert path to URL: foo
```

### Expected behavior

I expect that all of the above queries work and create an empty table or a table with a single value

**Comment by Lordworms** [comment]
Take this one

**Comment by Lordworms** [comment]
I used debug mode to build this and the query worked fine
<img width="750" alt="image" src="https://github.com/apache/datafusion/assets/48054792/aa6c1b59-c28a-4041-8897-0f1d257b72cb">
<img width="644" alt="image" src="https://github.com/apache/datafusion/assets/48054792/3a723d69-cfc5-4638-a8c6-eb7312c27605">

**Comment by alamb** [comment]
🤔  I tested it locally and likewise it seems to work just fine for me in a debug build

I rebuilt a release build and it works fine. Not sure what was going on on my machine.

Sorry for the noise. Thanks @Lordworms
