### ISSUE TITLE
Stop copying LogicalPlan and Exprs in  `CommonSubexprEliminate`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10211]
### Is your feature request related to a problem or challenge?

As part of making the planner faster, we are updating the passes to avoid copying `LogicalPlan` and `Expr` (see https://github.com/apache/datafusion/issues/9637)

Recent profiling  (https://github.com/apache/datafusion/issues/9637#issuecomment-2073325456) shows that a non trivial amount of plan time happens in `CommonSubexprEliminate ` 

### Describe the solution you'd like

I would like to reduce the amount of copying in this pass that it no longer appears in profiling traces

**Comment by alamb** [comment]
I believe @peter-toth  is working on this one

**Comment by peter-toth** [comment]
I am, but how this issue relates to https://github.com/apache/datafusion/issues/9873? Are they duplicates?

**Comment by alamb** [comment]
> I am, but how this issue relates to #9873? Are they duplicates?

That is a good call -- I think this one subsumes https://github.com/apache/datafusion/issues/9873 -- marking it thusly

**Comment by alamb** [comment]
> I am, but how this issue relates to #9873? Are they duplicates?

Good call -- I think they are dupes. Closing this one

**Comment by peter-toth** [comment]
@alamb, why did you reopen this?

**Comment by alamb** [comment]
> @alamb, why did you reopen this?

I am not sure. Sorry about that
