### ISSUE TITLE
DataFusion `38.0.0` Release

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#10217]
### Is your feature request related to a problem or challenge?

I plan on starting to prepare for the DataFusion 38 release on Monday, April 29th. Let's use this issue to track which issues/PRs need to be included.

This will be the first release as a top-level ASF project and there will likely be some additional work required.

### Describe the solution you'd like

Issues/PRs to include:

- https://github.com/apache/datafusion/pull/10186 (would be helpful for the Comet project)
- https://github.com/apache/datafusion/pull/10254
- https://github.com/apache/datafusion/issues/10181
- https://github.com/apache/datafusion/pull/10095
- https://github.com/apache/datafusion/issues/10320
- https://github.com/apache/datafusion/issues/9785

### Additional context

37 release ticket: https://github.com/apache/datafusion/issues/9682

**Comment by l1t1** [comment]
please release the Python version too.

**Comment by andygrove** [comment]
> please release the Python version too.

We will need someone to make the necessary changes to the DataFusion Python subproject first, so that it compiles against the new version of DataFusion.

Is this something that you would be interested in helping with?

**Comment by alamb** [comment]
I added a few more items to the waiting list: 

https://github.com/apache/datafusion/pull/10254
https://github.com/apache/datafusion/issues/10181
https://github.com/apache/datafusion/pull/10095

**Comment by alamb** [comment]
Added https://github.com/apache/datafusion/issues/9785

**Comment by andygrove** [comment]
Hi @alamb. I assume we still want to wait on https://github.com/apache/datafusion/issues/10181 for creating the release?

**Comment by alamb** [comment]
> Hi @alamb. I assume we still want to wait on #10181 for creating the release?

I think that would be good -- are you about ready to make a release candidate? If so I will work on https://github.com/apache/datafusion/issues/10181 tomorrow

**Comment by andygrove** [comment]
> > Hi @alamb. I assume we still want to wait on #10181 for creating the release?
> 
> I think that would be good -- are you about ready to make a release candidate? If so I will work on #10181 tomorrow

I am ready any time.

**Comment by alamb** [comment]
Here is a PR witha proposed API https://github.com/apache/datafusion/pull/10330 that would close https://github.com/apache/datafusion/issues/10181

**Comment by alamb** [comment]
I also think https://github.com/apache/datafusion/issues/10320 should be included in 38.0.0 (as it would be a regression if we released `main` as is). There is a PR up to fix it here https://github.com/apache/datafusion/pull/10321

**Comment by andygrove** [comment]
I will start the process of creating the first release candidate today.

**Comment by alamb** [comment]
Vote thread: https://lists.apache.org/thread/nnhtnxt8rs65k5x59scfdc0qkmqghy3n

**Comment by andygrove** [comment]
Release has been completed

**Comment by alamb** [comment]
Filed https://github.com/apache/datafusion/issues/10517 for next one
