### ISSUE TITLE
Stop copying LogicalPlan and Exprs in  `EliminateLimit`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10212]
### Is your feature request related to a problem or challenge?

As part of making the planner faster, we are updating the passes to avoid copying `LogicalPlan` and `Expr` (see https://github.com/apache/datafusion/issues/9637)

### Describe the solution you'd like

I would like to reduce the amount of copying in this pass (even though it doesn't appear in current profiling)

### Describe alternatives you've considered

Apply the model from @Lordworms  in https://github.com/apache/datafusion/pull/10166 to `EliminateLimit`.  

### Additional context

I think this will be a pretty simple refactor with a good existing pattern, so mark this as good first issue

**Comment by kevinmingtarja** [comment]
Hi, I'd like to take on this issue!

**Comment by kevinmingtarja** [comment]
take
