### ISSUE TITLE
Change `null_treatment: Option<NullTreatment>` to bool

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10230]
I think ideally the physical expr shouldn't be depending on sql parser (for people who are not using SQL)

Though now I see that perhaps it is because AggregateFunction has a null treatment flag on it 🤔  That might be a nice dependency to avoid

_Originally posted by @alamb in https://github.com/apache/datafusion/pull/10214#discussion_r1579312800_

# The rationale of this change
NullTreatment  has only two token
```
pub enum NullTreatment {
    IgnoreNulls,
    RespectNulls,
}
```

We can use bool to represent this, and also avoid importing `sqlparser` for the downstream crate.

# The solution I expect
Replace `null_treatment` with `ignore_nulls: bool`. The logic should follow 

```rust
let ignore_nulls = null_treatment
                .unwrap_or(sqlparser::ast::NullTreatment::RespectNulls)
                == NullTreatment::IgnoreNulls;
```

**Comment by jayzhan211** [comment]
@alamb I would like to know if these API changes are fine to go. 
Specifically, WindowFunction and AggregateFunction are changed

**Comment by alamb** [comment]
> @alamb I would like to know if these API changes are fine to go. Specifically, WindowFunction and AggregateFunction are changed, but they will be easier to use.

I think it is fine with me, but I see your point about the API change 🤔  We could potentially also add a new `NullTreatment` enum into DataFusion (rather than bool) to avoid the dependency

**Comment by jayzhan211** [comment]
> > @alamb I would like to know if these API changes are fine to go. Specifically, WindowFunction and AggregateFunction are changed, but they will be easier to use.
> 
> I think it is fine with me, but I see your point about the API change 🤔 We could potentially also add a new `NullTreatment` enum into DataFusion (rather than bool) to avoid the dependency

If we introduce df version in common, or SQL crate. They both import sql_parser. Does that mean if anyone import the enum, they also get sql_parser 🤔

**Comment by dmitrybugakov** [comment]
@alamb @jayzhan211 

Since NullTreatment has a clear interpretation with true and false, and we need to resolve dependency concerns, do we really want to continue maintaining it as a structure?

**Comment by jayzhan211** [comment]
> @alamb @jayzhan211 
> 
> Since NullTreatment has a clear interpretation with true and false, and we need to resolve dependency concerns, do we really want to continue maintaining it as a structure?

Actually, it has one benefit over bool, we can impl debug, display with “respect nulls" or "ignore nulls"

**Comment by alamb** [comment]
> If we introduce enum in common, or sql crate. They both import sql_parser. Does that mean if anyone import the enum, they also get sql_parser 🤔

I think the only real value in making this change would be to remove the `sql_parser`  dependency in common (to keep the dependency stack on common as small as possible). Otherwise making the change I think is just API churn without benefit

https://github.com/apache/datafusion/blob/9c8873af12826e47f5743991859790df7a3b6400/datafusion/common/Cargo.toml#L64

I haven't looked to see if there are other things that depend on sql_parser in common

**Comment by dmitrybugakov** [comment]
> > If we introduce enum in common, or sql crate. They both import sql_parser. Does that mean if anyone import the enum, they also get sql_parser 🤔
> 
> I think the only real value in making this change would be to remove the `sql_parser` dependency in common (to keep the dependency stack on common as small as possible). Otherwise making the change I think is just API churn without benefit
> 
> https://github.com/apache/datafusion/blob/9c8873af12826e47f5743991859790df7a3b6400/datafusion/common/Cargo.toml#L64
> 
> I haven't looked to see if there are other things that depend on sql_parser in common

I haven't found NullTreatment being used in the common module, but there are many other explicit imports from sqlparser in it, such as:

use sqlparser::parser::ParserError;
use sqlparser::ast::Ident;
use sqlparser::dialect::GenericDialect;
use sqlparser::parser::Parser;
use sqlparser::ast::TableConstraint;

Thus, it seems changing NullTreatment to a boolean won't help in removing sqlparser from the module dependencies.

So, does this mean I should close the PR?

**Comment by alamb** [comment]
> Does this mean we should close the PR?

Yeah, I agree -- this seems like a waste of time (unless someone really wants to slim down the dependency tree)

Thanks for the research @dmitrybugakov
