### ISSUE TITLE
uuid and random need return different value in different row

### ISSUE THREAD

**Issue by liukun4515** [apache/datafusion#10247]
I think the idea here is that expectation is that `rand` is invoked *once per row* rather than *once per batch*. And the only way it knew how many rows to make is to get a null array in 🤔 

For example, when I run `datafusion-cli` from this PR to call random() the same value is returned for each row:

```sql
> create table foo as values (1), (2), (3), (4), (5);
0 row(s) fetched.
Elapsed 0.018 seconds.

> select column1, random() from foo;
+---------+--------------------+
| column1 | random()           |
+---------+--------------------+
| 1       | 0.9594375709000513 |
| 2       | 0.9594375709000513 |
| 3       | 0.9594375709000513 |
| 4       | 0.9594375709000513 |
| 5       | 0.9594375709000513 |
+---------+--------------------+
5 row(s) fetched.
Elapsed 0.012 seconds.
```

But I expect that each row has a different value for `random()`

However, since none of the tests failed, clearly we have a gap in test coverage 🤔

_Originally posted by @alamb in https://github.com/apache/datafusion/pull/10193#discussion_r1576674821_

**Comment by jayzhan211** [comment]
@liukun4515 This should be solved in #10193

**Comment by alamb** [comment]
To be clear, I think the correct thing happens on main already

The example from https://github.com/apache/datafusion/pull/10193#discussion_r1576674821 was with intermediate changes when I reran on  https://github.com/apache/datafusion/pull/10193

```sql
DataFusion CLI v37.1.0
> create table t as values (1), (2);
0 row(s) fetched.
Elapsed 0.032 seconds.

> select random() from t;
+---------------------+
| random()            |
+---------------------+
| 0.02024777131575939 |
| 0.9330727106990677  |
+---------------------+
2 row(s) fetched.
Elapsed 0.012 seconds.

> select uuid() from t;
+--------------------------------------+
| uuid()                               |
+--------------------------------------+
| 630d1d50-1ed2-4d3c-bb04-89d338e3e59f |
| 594e03fb-b038-4a48-a6e6-e2f8f12746c1 |
+--------------------------------------+
2 row(s) fetched.
Elapsed 0.003 seconds.
```

**Comment by alamb** [comment]
Here is a PR that adds a test for this case : https://github.com/apache/datafusion/pull/10248
