### ISSUE TITLE
Support skipping comments in `CsvReader`

### ISSUE THREAD

**Issue by bbannier** [apache/datafusion#10262]
It would be great if datafusion had out-of-the-box support for skipping comment lines. While non of this is "standardized" many CSV readers support skipping full comment lines. An often used comment indentifier is a `#` prefix (default in e.g. [pandas] or [R]).

I originally posted this as a comment https://github.com/apache/datafusion/issues/8824#issuecomment-2078835858. 

[pandas]: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
[R]: https://stat.ethz.ch/R-manual/R-devel/library/utils/html/read.table.html

**Comment by pingsutw** [comment]
take

**Comment by bbannier** [comment]
I opened https://github.com/apache/arrow-rs/pull/5759 to add comment support to Arrow's CSV reader. With that the work here is mostly around passing that flag from user code to the actual reader, and implementing support for the flag to be serialized in protos.
