### ISSUE TITLE
Signature::Equal for `NVL` and `NullIf`

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10270]
### Is your feature request related to a problem or challenge?

NVL and Nullif has signature uniform, which iterates valid types and creates many possible types for them

```rust
TypeSignature::Uniform(number, valid_types) => valid_types
            .iter()
            .map(|valid_type| (0..*number).map(|_| valid_type.clone()).collect())
            .collect(),
```

I think they can have better signatures that take repeated first type as the valid types. 

```rust
        TypeSignature::Equal(num) => {
            vec![vec![current_types[0]; num]]
        }
```

I think there are two benefits
1. only one valid type vector and it is good enough
2. no need to maintain supported types

**Comment by yyy1000** [comment]
I think this would not need a lot of changes and I want to take it. :)

**Comment by yyy1000** [comment]
After a initial try, there is an issue shown below:

> statement ok
> CREATE TABLE test(
>   int_field  INT,
>   bool_field BOOLEAN,
>   text_field TEXT,
>   more_ints  INT
> ) as VALUES
>   (1,    true,  'abc',  2),
>   (2,    false, 'def',  2),
>   (3,    NULL,  'ghij', 3),
>   (NULL, NULL,   NULL,  4),
>   (4,    false, 'zxc',  5),
>   (NULL, true,   NULL,  6)
> ;
> 
> 
> query I rowsort
> SELECT NULLIF(int_field, 2) FROM test;

External error: query failed: DataFusion error: Error during planning: No function matches the given name and argument types 'nvl(Int32, Int64)'. You might need to add explicit type casts.

I think it's because the first type is INT(32), however datafusion will treat the const 2 as int64.🤔
I will also see whether there is a solution.

**Comment by jayzhan211** [comment]
I checked the behavior in Postgres and found it doing casting implicitly, maybe the idea of Signature::Equal is not suitable for nullif. 😢

**Comment by yyy1000** [comment]
Got it, it seems that datafusion can't do casting implicitly now, so the idea may be not available now. 👀

**Comment by jayzhan211** [comment]
I think the coercion logic here is similar to coalesce and array. https://github.com/apache/datafusion/issues/10261#issuecomment-2081465710
