### ISSUE TITLE
Stop copying LogicalPlan and Exprs in `SingleDistinctToGroupBy`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10295]
### Is your feature request related to a problem or challenge?
Part of https://github.com/apache/datafusion/issues/9637

As part of making the planner faster, we are updating the optimizer passes to avoid copying `LogicalPlan` and `Expr` (see https://github.com/apache/datafusion/issues/9637)

### Describe the solution you'd like

I would like to reduce the amount of copying in this pass (even though it doesn't appear in current profiling)

### Describe alternatives you've considered

Apply the model from @Lordworms  in https://github.com/apache/datafusion/pull/10166 to this pass
2. Update OptimizerRule::supports_rewrite` to return true
1. Update `OptimizerRule` to use `rewrite`
3. Update the pass itself to not copy the LogicalPlan (ideally using the [`TreeNode`](https://github.com/apache/datafusion/blob/b41ef20c5dad7bdd674e3cc5f35a9c99efae676c/datafusion/common/src/tree_node.rs#L33-L94) API) - it is implemented for `LogicalPlan` ([API](https://github.com/apache/datafusion/blob/b41ef20c5dad7bdd674e3cc5f35a9c99efae676c/datafusion/expr/src/logical_plan/tree_node.rs#L18-L38)) and `Expr` ([API](https://github.com/apache/datafusion/blob/b41ef20c5dad7bdd674e3cc5f35a9c99efae676c/datafusion/expr/src/tree_node.rs#L18)) 

Other examples: https://github.com/apache/datafusion/pull/10218

### Additional context

I don't think this pass does much copying at the moment, for whwat it is woth -- the benfit would be to follow the same pattern

**Comment by appletreeisyellow** [comment]
I'd like to take this one if no one has worked on it yet

**Comment by alamb** [comment]
Thanks @appletreeisyellow -- that would be great. No one has started as far as I can tell.

**Comment by alamb** [comment]
I took a quick look at https://github.com/apache/datafusion/blob/58cc4e1289451b30adca4721fd6eb5a36b26a2cd/datafusion/optimizer/src/single_distinct_to_groupby.rs#L59

Looks to me like there are basically 2 things to do:
1. Switch to use `OptimizerRule::rewrite` API (as in https://github.com/apache/datafusion/pull/10166)
2. Remove the `expr.clone()` calls here https://github.com/apache/datafusion/blob/58cc4e1289451b30adca4721fd6eb5a36b26a2cd/datafusion/optimizer/src/single_distinct_to_groupby.rs#L131

Once you do 1. 2 should be pretty simple (maybe even just remove the `.clone()`

**Comment by appletreeisyellow** [comment]
@alamb Thank you for the guidance!
