### ISSUE TITLE
Substrait integration doesn't recognize typed functions

### ISSUE THREAD

**Issue by Blizzara** [apache/datafusion#10412]
### Describe the bug

Since https://github.com/substrait-io/substrait/pull/537, the standard has declared that functions must be named with compound names consisting of both the function and its types. For example, for the function "not", the full name would now be "not:bool". However trying to use "not:bool" in Substrait input for DataFusion results in 
`This feature is not implemented: Unsupported function name: \"not:bool\"` as "not:bool" doesn't match into the list used by  https://github.com/apache/datafusion/blob/f0e96c670108ba0ffdebb9dd9e764bba4d2dca8c/datafusion/substrait/src/logical_plan/consumer.rs#L125

### To Reproduce

Using e.g. [isthmus](https://github.com/substrait-io/substrait-java/tree/main/isthmus-cli) from Substrait-java, one can produce a simple substrait:

```
substrait-java % ./isthmus-cli/build/graal/isthmus "select not d from t" -c "create table t (d boolean)"  --outputformat=BINARY | base64 
ChsIARIXL2Z1bmN0aW9uc19ib29sZWFuLnlhbWwSDhoMCAEaCG5vdDpib29sGkcSRQo7OjkKBRIDCgEBEhoKGAoCCgASDQoBRBIICgQKAhABGAI6AwoBVBoUGhIaBAoCEAEiChoIEgYKAhIAIgASBkVYUFIkMA==
```
(Drop the `outputformat=BINARY | base64` to see the plan as text)

Then using DataFusion to execute that plan:
```
#[tokio::test]
async fn test_not() -> datafusion::common::Result<()> {
    let protobuf = general_purpose::STANDARD.decode("ChsIARIXL2Z1bmN0aW9uc19ib29sZWFuLnlhbWwSDhoMCAEaCG5vdDpib29sGkcSRQo7OjkKBRIDCgEBEhoKGAoCCgASDQoBRBIICgQKAhABGAI6AwoBVBoUGhIaBAoCEAEiChoIEgYKAhIAIgASBkVYUFIkMA==").unwrap();
    let ctx = SessionContext::new();
    ctx.register_csv("T", "tests/testdata/data.csv", CsvReadOptions::new())
        .await?;
    let plan = deserialize_bytes(protobuf).await?;
    let _ = from_substrait_plan(&ctx, plan.as_ref()).await?;
    Ok(())
}
```

Fails with `Error: NotImplemented("Unsupported function name: \"not:bool\"")`

### Expected behavior

`not:bool` should be found and the plan be created correctly

**Comment by alamb** [comment]
Thanks for the report @Blizzara  -- this would be a great thing to fix

**Comment by EpsilonPrime** [comment]
Be wary, Gluten contains a copy of Substrait instead of depending on the main repo.  As a result its Substrait is incompatible with the rest of the ecosystem.  That works for them as they only use the Substrait internally but the other tools are handy sometimes (especially the Substrait Validator).

It may also interest you that a generic Spark to Substrait tool is out there:  https://github.com/voltrondata/spark-substrait-gateway

It's mostly there for DuckDB but other backends require some tweaks (DataFusion is one of them).  We have a tweak to remove the compound names for DataFusion but would love to see this issue addressed.  If you have questions (especially from the Substrait side) feel free to reach out.

**Comment by Blizzara** [comment]
> Be wary, Gluten contains a copy of Substrait instead of depending on the main repo. As a result its Substrait is incompatible with the rest of the ecosystem. That works for them as they only use the Substrait internally but the other tools are handy sometimes (especially the Substrait Validator).

Yup, the substrait-spark submodule was not using Gluten's Substrait but the vanilla one. (The whole thing wasn't really used by Gluten and it's no longer part of the repo, thus the fork).

> It may also interest you that a generic Spark to Substrait tool is out there: https://github.com/voltrondata/spark-substrait-gateway

It does, thanks! Not directly useful as we need a solution in Java, but it's always good to have more references to look at.
