### ISSUE TITLE
Support "User defined coercion" rules

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10423]
### Is your feature request related to a problem or challenge?

DataFusion automatically "coerces" (see [docs here](https://docs.rs/datafusion/latest/datafusion/logical_expr/type_coercion/index.html)) input argument types to match the types required of operations or functions. 

For functions, this is described by a desired [TypeSignature](https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.TypeSignature.html#)
```rust
pub enum TypeSignature {
    Variadic(Vec<DataType>),
    VariadicEqual,
    VariadicAny,
    Uniform(usize, Vec<DataType>),
    Exact(Vec<DataType>),
    Any(usize),
    OneOf(Vec<TypeSignature>),
    ArraySignature(ArrayFunctionSignature),
}
```

However, some functions have special hard coded coercion logic such as sum and count (TODO link) as well as some Array functions like `make_array`. We started down the path of encoding the special array semantics into `TypeSignature` (see `ArrayFunctionSignature`))

However, as we continue to find other examples of different desired rules (most recently in sum and count), `TypeSignature` will grow and become more and more specialized

### Describe the solution you'd like

@jayzhan211  had a great suggestion https://github.com/apache/datafusion/pull/10268#discussion_r1593511241 that in addition to encoding common coercion behaviors in `TypeSignature`, we can also add a variant of `TypeSignature` that permits user defined coercion rules

**Comment by jayzhan211** [comment]
I found that to have `coerce_types` for both scalarUDF and aggregateUDF, I would need to introduce a more general trait for both function

```rust
impl UDFImpl for T {
    fn name(&self) -> &str {
       &self.name
    }

    fn coerce_types(&self, data_types: &[DataType]) -> Result<Vec<DataType>> {
        not_impl_err!("Function {} does not implement coerce_types", self.name)
    }
}

impl ScalarUDFImpl: UDFImpl for T
impl AggregateUDFImpl: UDFImpl for T
```
Then we can have
```
fn coerce_arguments_for_signature(
    expressions: Vec<Expr>,
    schema: &DFSchema,
    signature: &Signature,
    func: Arc<dyn UDFImpl>,
) -> Result<Vec<Expr>> {}
```

Another alternative is having a duplicate function for scalar and aggregate for a related function

```
fn coerce_arguments_for_signature(
    expressions: Vec<Expr>,
    schema: &DFSchema,
    signature: &Signature,
    func: &ScalarUDF,
) -> Result<Vec<Expr>> {}

fn coerce_arguments_for_signature(
    expressions: Vec<Expr>,
    schema: &DFSchema,
    signature: &Signature,
    func: &AggregateUDF,
) -> Result<Vec<Expr>> {}
```

I think the first option is potentially beneficial in the long run(?)
@alamb what do you think?
