### ISSUE TITLE
Type coercion when creating table

### ISSUE THREAD

**Issue by yyy1000** [apache/datafusion#10440]
### Is your feature request related to a problem or challenge?

When creating a table specifying the double as column datatype and giving some initial values without explicit double type, for example using some const like 1, there would be an error. Though I think the previous row could indicate the type. 
I don't know whether it's designed to behave like this, or something else. 🤔

```
External error: statement failed: DataFusion error: Error during planning: Inconsistent data type across values list at row 1 column 0. Was Float64 but found Int64
[SQL] create table t (c1 double, c2 double) as values (1.1, 4.1), (2, 5), (3, 6);
```

**Comment by jayzhan211** [comment]
I also notice that but did not dig into it. We might need type coercion in `LogicalPlan::Values`.
