### ISSUE TITLE
Move optimizer rule that has aggregate function out of core

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10455]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/8708
The background is that we are moving builtin aggregate function to `functions-aggregate` as an UDAF

While moving `count` to UDAF, I found that we need to call UDAF in the optimize rule [`single_distinct_to_groupby`](https://github.com/apache/arrow-datafusion/blob/main/datafusion/optimizer/src/single_distinct_to_groupby.rs).
I think we need to move the rule that has aggregate function out of the core because the optimizer is the core of the datafusion that we would like to prevent importing the `functions-aggregate` crate

### Describe the solution you'd like

# Optimizer
Move common optimizer things to `optimizer-common` crate or `datafusion-expr` crate
Move rules to `functions-aggregate`
- `single_distinct_to_groupby`
- common_subexpr_eliminate
- decorrelate
- replace_distinct_aggregate

# Analyzer
- count_wildcard_rule // This should be similar to https://github.com/apache/datafusion/pull/9583

**Comment by alamb** [comment]
What part of the rule was aggregate specific?

I think the single distinct aggregate removal rule is general to all aggreagetes (it isn't aggregate specific) including user defined ones so I am not sure we need to move the rules. I took a look and couldn't find any referenes 

BTW this PR is updating single distinct aggregate rule https://github.com/apache/datafusion/pull/10460

**Comment by jayzhan211** [comment]
I thought I need to import `functions-aggregate` to create new aggregate function expression, but I found out that I could just modify AggregateFunction directly, since the function does not change.

**Comment by jayzhan211** [comment]
let me close the issue first
