### ISSUE TITLE
Seperate out common types from Datafusion Proto

### ISSUE THREAD

**Issue by mustafasrepo** [apache/datafusion#10477]
### Is your feature request related to a problem or challenge?

Currently `datafusion-proto` crate, have serialization and deserialization support for 
- Common Core Types (`ColumnRelation`, `Column`, `DfSchema`, `DfField`, `ScalarValue`, etc.)
- various `LogicalPlanNode`s, `PhysicalPlanNode`s

While working on another project. I hit a usecase where I want to serialize, deserialize only some primitive types (such as `ScalarValue`, `Schema`, etc), where I want to do serialization and deserialization in the `datafusion-physical-plan` crate. 

I thought separating out common types from `datafusion-proto` crate into another crate such as `datafusion-proto-common` (as in `datafusion` and `datafusion-common`) might help to decrease dependency. This decoupling would enable us to use `datafusion-proto-common`crate (whose only dependency would be `datafusion-common`) inside other crates under the `datafusion` (except `datafusion-common`).

I wonder, what community thinks about this change. Do you think, this is useful? Are others have a usecase for this kind of separation.

### Describe the solution you'd like

This should be mostly reorganization PR.

**Comment by andygrove** [comment]
This makes sense to me.
