### ISSUE TITLE
Convert internal representation of LogicalPlanBuilder from `LogicalPlan` to `Arc<LogicalPlan>`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10485]
Great idea @ClSlaid 

Thanks to @AbrarNitk we have a first version of `LogicalPlanBuilder::from(arc_input)` in https://github.com/apache/datafusion/pull/10466 🙏 

Now that we have merged that PR we can make a second PR (and maybe a second ticket) about switching the internal representation from https://github.com/apache/datafusion/blob/8cc92a921f3b0296caf035edb66a4b3c422f084d/datafusion/expr/src/logical_plan/builder.rs#L98-L101

To 

```rust
 pub struct LogicalPlanBuilder { 
     plan: Arc<LogicalPlan>, 
 } 
```

The rationale is as explained by @ClSlaid  on https://github.com/apache/datafusion/issues/10465#issuecomment-2106192785 -- that in some cases this can prevent cloning the input

_Originally posted by @alamb in https://github.com/apache/datafusion/issues/10465#issuecomment-2107222678_

**Comment by alamb** [comment]
I think this is a good first issue as it is pretty clear what the ask is

**Comment by iiiancampbell** [comment]
Hi @alamb , would be keen to contribue to this as my first issue.

**Comment by iiiancampbell** [comment]
take

**Comment by alamb** [comment]
Awesome -- thank you @iiiancampbell 🎉

**Comment by jc4x4** [comment]
I noticed the previous commit is stale and closed. Here is my first attempt.
https://github.com/apache/datafusion/pull/12040
