### ISSUE TITLE
`GroupingSet` Expr --> String Support

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10521]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/9726 to complete the Expr

Converting `Expr` back to `SQL` is valuable for several usecases such as using DataFusion in federated databases (e.g. generate SQL to push down) or using DataFusion's expr APIs to programatically create SQL.

### Describe the solution you'd like

Support converting SQL syntax like this:

TODO I AM NOT SURE HOW TO MAKE THIS IN SQL

### Describe alternatives you've considered

The basic pattern is:

1.  Implement the Expr --> AST reverse code in `Unparser::expr_to_sql`([source link](https://github.com/apache/datafusion/blob/16346022ed4564211c0fb4bf20ac165f2c481a90/datafusion/sql/src/unparser/expr.rs#L93-L94)) 
3. Add a test to [`expr_to_sql_ok`](https://github.com/apache/datafusion/blob/16346022ed4564211c0fb4bf20ac165f2c481a90/datafusion/sql/src/unparser/expr.rs#L912-L913)

Note you can run the tests like 

```shell
cargo test -p datafusion-sql -- expr_to_sql_ok
```

### Additional context

This is likely NOT a good first issue

**Comment by xinlifoobar** [comment]
Hi @alamb, I am wondering whether  is there a way to implement the `cube` and 'rollup' functions easily. the inner vector is expanded in the planner.

**Comment by xinlifoobar** [comment]
I think from the `Vec<Expr>` could not mapping back to the only unique `Vec<Vec<Expr>>` and hence unparse the cube statement would be difficult. How about store another copy of origin Vec in the Cube and Rollup instance? i.e.,

```rs
pub enum GroupingSet {
    /// Rollup grouping sets
    Rollup(Vec<Expr>, Vec<Vec<Expr>>),
    /// Cube grouping sets
    Cube(Vec<Expr>, Vec<Vec<Expr>>),
    /// User-defined grouping sets
    GroupingSets(Vec<Vec<Expr>>),
}
```

**Comment by alamb** [comment]
Hi @xinlifoobar  - another thing that we could potentially do is to work at this from the SQL statement level (rather than the Expr level)

As in implement a round trip test like this for a query with a grouping set:

https://github.com/apache/datafusion/blob/main/datafusion/sql/tests/sql_integration.rs#L4678-L4708

**Comment by xinlifoobar** [comment]
I made a mistake about the previous statements. The vector of cube and rollout is not expanded so the implement could be easy.

https://github.com/apache/datafusion/blob/main/datafusion/sql/src/expr/grouping_set.rs#L42-L81

**Comment by alamb** [comment]
Thanks again @xinlifoobar
