### ISSUE TITLE
Create a DataFusion blog

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#10535]
### Is your feature request related to a problem or challenge?

We do not currently have a blog set up for DataFusion.

The DataFusion website at https://datafusion.apache.org is published from the sphinx documentation in the core DataFusion project. Sphinx does not have blogging functionality built-in, so we will need to set up a blog using some other solution.

The Apache Arrow site, where we previously published DataFusion posts, uses Jekyll [1], so the easiest path is for us to continue to use jekyll. We could even choose to republish old DataFusion posts on the new site so we have a complete history here.

I propose that we create a `datafusion-site` or `datafusion-blog` repo for the blog content to keep it separate from the software.

[1] https://github.com/apache/arrow-site

**Comment by andygrove** [comment]
I volunteer to take this on

**Comment by alamb** [comment]
> The Apache Arrow site, where we previously published DataFusion posts, uses Jekyll [1], so the easiest path is for us to continue to use jekyll. We could even choose to republish old DataFusion posts on the new site so we have a complete history here.

+1

> I propose that we create a datafusion-site or datafusion-blog repo for the blog content to keep it separate from the software.

A separate repo makes sense to me. Eventually we should probably move all doc content into a repo like `datafusion-site` but there is pretty serious value at the moment in my mind to being able to make a single PR with code changes and the relevant doc changes (which would not be possible if we moved the docs to a different repo)

**Comment by andygrove** [comment]
This task is complete: https://datafusion.apache.org/blog/
