### ISSUE TITLE
UserDefindedLogicalNode::from_template does not return a Result<...>.

### ISSUE THREAD

**Issue by LorrensP-2158466** [apache/datafusion#10571]
### Is your feature request related to a problem or challenge?

This is really a feature request but more of a question.

Currently `UserDefinedLogicalNode::from_template` only returns `Arc<dyn Self>` but i have noticed that `LogicalPlan::with_new_exprs` does return a Result. So when it calls `from_template` on an Extension node, it just wraps it in an `Ok()`.
In the example of `UserDefinedLogicalNodeCore` where TopK is implemented, the implementation of `from_template` first asserts the inputs and exprs. 
I have also tried to implement a custom LogicalPlan node and my own implementation of `from_template` also has several error cases (not just asserting the new values) which i unfortunately have to unwrap.

Is this expected behaviour, or is it maybe nicer to return `Result`s

**Comment by alamb** [comment]
I agree it would be much better to change the API and return an `Result<..>`

Thank you for the report

**Comment by LorrensP-2158466** [comment]
I don't see this as a really difficult API change. Is it ok if I do this?

**Comment by alamb** [comment]
> I don't see this as a really difficult API change. Is it ok if I do this? Edit: there is a PR already,did not see it, sorry.

@lewiszlw  beats us to it!


(BTW if anyone wants a workaround for this in older versions that does not requier a panic, they could potentially return a node that would generate a runtime error if the arguments to `from_template` didn't error)
