### ISSUE TITLE
Incorrect statistics read for `i8` `i16` columns in parquet

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10585]
### Describe the bug

As @NGA-TRAN  found in https://github.com/apache/datafusion/pull/10537 when i8 and i16 values are written to parquet and then the statistics are extracted, the returned min/max values are incorrect.

This could lead to incorrect results when reading parquet files with filters on columns with `i8` and `i16` types

### To Reproduce

See tests added in https://github.com/apache/datafusion/pull/10537

**Comment by alamb** [comment]
Possibly related to https://github.com/apache/datafusion/issues/9779

**Comment by Lordworms** [comment]
I have detected the location which causes the bug, seems like in arrow-rs, when getting DataType::Int8, we always return a Int32 Array Instead
<img width="1360" alt="image" src="https://github.com/apache/datafusion/assets/48054792/b42f1c78-5af6-4fc5-a210-f95ecc9fbf40">

**Comment by Lordworms** [comment]
take
