### ISSUE TITLE
DataFusion reads Date32 and Date64 parquet statistics in as Int32Array

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10587]
### Describe the bug

When reading a Date32 or Date64 column from a parquet file, DataFusion currently returns an Int32 array

### To Reproduce

You can see the issue in https://github.com/apache/datafusion/pull/10537 
* `test_dates_32_diff_rg_sizes`
* `test_dates_64_diff_rg_sizes`

### Expected behavior

I expect a
1.  Date32 column to be read as `Date32Array`
2. Date64 column to be read as `Date64Array`

**Comment by edmondop** [comment]
@alamb the title here doesn't make much sense, are you saying that the `min` and `max` are not extracted as Date32/Date64?
