### ISSUE TITLE
Implement a benchmark for extracting arrow statistics from parquet

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10606]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/10453 

Part of https://github.com/apache/datafusion/issues/10453 is to "efficiently" extract statistics from parquet files. The current code is likely quite bad, but we have no benchmarks that actually show that or allow for us to get better

### Describe the solution you'd like

I would like to create a benchmark, run like `cargo bench ...` that does:
1. Creates a parquet file that has 100 row groups once
2. Read the parquet metadata out
3. in the loop extracts the statistics from the metadata  into Arrow statistics (using the API introduced in https://github.com/apache/datafusion/pull/10537) -- not it shouldn't including reading the metadata from the parquet file

I suggest four benchmarks with different types:
1. UInt64
2. f64
3. String
4. Dictionary(Int32, String)

**Comment by Lordworms** [comment]
Take this one
