### ISSUE TITLE
Incorrect statistics read for unsigned integer columns in parquet

### ISSUE THREAD

**Issue by NGA-TRAN** [apache/datafusion#10604]
### Describe the bug

I found this bug while adding tests for reading parquet statistics https://github.com/apache/datafusion/pull/10592/. Instead of getting corresponding UInt8Array, UInt16Array, UInt32Array for columns with u8, u16, u32 data types, we get Int32Array. Similarly, instead of getting UInt64Array for column with data type u64, we get Int64Array.

### To Reproduce

See the test `test_uint` in PR https://github.com/apache/datafusion/pull/10592 (will be merged soon)

### Expected behavior

UInt8Array, UInt16Array, UInt32Array, UInt64Array for columns with data types u8, u16, u32 and u64 respectively

**Comment by edmondop** [comment]
This seems related to [this](https://github.com/apache/datafusion/pull/10593#discussion_r1608470231) comment
