### ISSUE TITLE
Make it easier to register object stores

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10616]
Came up in  https://github.com/apache/datafusion/issues/9280 

The problem is that when trying to use urls in ListingTables (or ParquetExec), if you try with a scheme like `file://` it won't work unless you have registered an object store handler

However, the current user experience is bad -- the error message is mysterious and confusing and it is not obvious how to register the correct listing table

"Error: Internal("No suitable object store found for file://")"

I would recommend two things:

# Suggestion 1: Change the error message 

Change the error message to include instructions on how to fix the issue

For example, instead of 
> No suitable object store found for file://

Perhaps it could be something more like

> No object store registered for url scheme 'file://'. See `RuntimeEnv::register_object_store`

# Suggestion 2: Add an example to the docs

Once the error message directs to  `RuntimeEnv::register_object_store` then it would be ideal if the docs

https://docs.rs/datafusion/latest/datafusion/execution/runtime_env/struct.RuntimeEnv.html#method.register_object_store

actually had an example

So that would perhaps take the form of adapting the example above as a doc example

Does that make sense?

_Originally posted by @alamb in https://github.com/apache/datafusion/issues/9280#issuecomment-2123183351_

**Comment by aditanase** [comment]
@alamb sent a quick PR - let me know if you were thinking of more than this. Thanks for the pointers!
