### ISSUE TITLE
SortMergeJoin: Add fuzz tests for SMJ when the JoinFilter is set

### ISSUE THREAD

**Issue by comphead** [apache/datafusion#10659]
### Is your feature request related to a problem or challenge?

SMJ now is in experimental state, and the test coverage can be improved. Because of poor test coverage it was found multiple bugs manually, with tests it would be much easier

### Describe the solution you'd like

I would like to expand fuzz test coverage for SMJ in `join_fuzz.rs` to support scenarios when the JoinFilter is set.
https://github.com/apache/datafusion/blob/8bedecc00b2f1f04d7b1a907152ce0d19b7046a5/datafusion/core/tests/fuzz_cases/join_fuzz.rs#L179

Currently JoinFilter is hardcoded as None for SMJ and would be great to start work for adding filter test cases

**Comment by edmondop** [comment]
@comphead would you please have a look at https://github.com/apache/datafusion/pull/10728? While hashjoin and sortmergejoin produce the same result when adding a filter, NestedLoopJoin doesn't, but I can't figure out what error I made in combining the two filters

**Comment by comphead** [comment]
@edmondop I'd suggest to make one step a time. join filter can be tricky, my vision we should be starting with HJ and SMJ for now. Leave NLJ for later

**Comment by edmondop** [comment]
Ok I will proceed to remove the join filter on the nested loop !

**Comment by comphead** [comment]
Appreciate if you could file the issue cc'ing me with NLJ wrong behavior details

**Comment by edmondop** [comment]
@comphead I filed this https://github.com/apache/datafusion/issues/10787, I have only added one test case with filtering at the moment, do you think we need to add one test case with filtering for each of the existing test cases?

**Comment by comphead** [comment]
RightJoin and LeftAnti join will addressed in separate PRs
