### ISSUE TITLE
Support convert LogicalPlan JOIN with `Using` constraint to SQL String

### ISSUE THREAD

**Issue by goldmedal** [apache/datafusion#10652]
### Is your feature request related to a problem or challenge?

We only support to convert JOIN with `ON` constraint to SQL String now. The SQL as below can't be converted now.
```
SELECT * FROM orders JOIN customer USING (custkey)
```
It will panic with the message:
```
NotImplemented("Unsupported join constraint: Using")
```

### Describe the solution you'd like

The unparse rule for `JOIN` in `datafusion/sql/src/unparser/plan.rs` should be implemented.
https://github.com/apache/datafusion/blob/8bedecc00b2f1f04d7b1a907152ce0d19b7046a5/datafusion/sql/src/unparser/plan.rs#L277-L285

**Comment by goldmedal** [comment]
By the way, I saw there're other unimplemented plans in `plan.rs`:
- Distinct
- Union
- Window
- Extension (I guess we need to provide some method for `UserDefinedLogicalNodeCore`)

Is there any plan to support them?
gentle ping @alamb

**Comment by alamb** [comment]
> Is there any plan to support them?

I think we should make plans to support them!

I started collecting issues on https://github.com/apache/datafusion/issues/8661

I also filed
https://github.com/apache/datafusion/issues/10663
 https://github.com/apache/datafusion/issues/10664

to track distint and window

Looking at https://github.com/apache/datafusion/blob/8bedecc00b2f1f04d7b1a907152ce0d19b7046a5/datafusion/sql/src/unparser/plan.rs#L83-L91 it actually looks like there are seveal other types of plans not yet supported  (like EXPLAIN, INSERT, etc...) Maybe we should file tickets for them as well
