### ISSUE TITLE
Convert `Variance Sample` to UDAF

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10667]
### Is your feature request related to a problem or challenge?

Part of #8708 
1. Move variance aggregate expression in `datafusion/physical-expr/src/aggregate/variance.rs` to `functions-aggregate`.
2. Add expression api in `roundtrip_expr_api` in `datafusion/proto/tests/cases/roundtrip_logical_plan.rs`

Similar to #10372 #10418

**Comment by yyin-dev** [comment]
take
