### ISSUE TITLE
Upgrade object_store to 0.10.1

### ISSUE THREAD

**Issue by Samrose-Ahmed** [apache/datafusion#10673]
### Is your feature request related to a problem or challenge?

object_store 0.10.1 includes some updates for better retrying, with multipart uplads

### Describe the solution you'd like

Upgrade object_store to 0.10.1

**Comment by Samrose-Ahmed** [comment]
I think `parquet` needs to be updated too, I tried it quickly locally and needed to update `pyo3` to 0.21 but get some weird type errors I couldn't understand.

**Comment by Omega359** [comment]
I believe this will happen with the arrow dependency upgrade.

**Comment by Omega359** [comment]
This looks to be completed as part of #10765, this ticket can be closed @alamb

**Comment by alamb** [comment]
Thank you for the ping @Omega359
