### ISSUE TITLE
Should the arg of `octet_length()` be a bare `Expr` instead of `Vec<Expr>`?

### ISSUE THREAD

**Issue by yutannihilation** [apache/datafusion#10676]
### Describe the bug

This is a minor issue about consistency. Currently, the signature of `octet_length()` is this, but I think this function takes only one argument just like `bit_length()`.

```rust
pub fn octet_length(args: Vec<Expr>) -> Expr
```
https://docs.rs/datafusion/38.0.0/datafusion/functions/string/expr_fn/fn.octet_length.html

### To Reproduce

n/a

### Expected behavior

n/a

### Additional context

n/a

**Comment by alamb** [comment]
Yes, I think so -- this is likely an oversight / regression since we moved the functions into a different crate. Thank you for the report

**Comment by yutannihilation** [comment]
Thanks for fixing!

**Comment by alamb** [comment]
> Thanks for fixing!

All credit goes to @ marvinlanhenke !
