### ISSUE TITLE
Use lowercase `name` for aggregate function

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10695]
### Is your feature request related to a problem or challenge?

`first_value` and `last_value` window functions currently report their names as `FIRST_VALUE` but also have a lower case alias:

https://github.com/apache/datafusion/blob/98cd19ef1cf52aef647e3e43fcc132a93028d1a2/datafusion/functions-aggregate/src/first_last.rs#L75

part of #8708

### Describe the solution you'd like

I think we would like to avoid the aliases and simply have a single name, similarly how the other functions work

TODO
- Count

**Comment by jayzhan211** [comment]
I think we need to rename other builtin aggregate function to uppercase too.

**Comment by edmondop** [comment]
This might be solved too? @alamb

**Comment by jayzhan211** [comment]
Yeah, solved
