### ISSUE TITLE
Google Cloud Storage requests during query execution being performed in series

### ISSUE THREAD

**Issue by davidhewitt** [apache/datafusion#10709]
### Describe the bug

I'm experimenting with datafusion 38 (using as a library, not the cli) to query against parquet files in Google Cloud Storage. For now I'm doing a basic test, just `select distinct(some_column) from my_table`. 

I wrapped the `ObjectStore` and `TableProvider` traits to add tracing to their execution, and this is what I see:

![image](https://github.com/apache/datafusion/assets/1939362/4e2e061d-cf09-46c9-842a-58a4ad5bb14e)

I'd like to improve the query performance to be much faster than my current 30s, and I think one dial in my control is to resize the parquet files so that there are fewer requests.

Another observation is that the requests to Google Cloud Storage during query execution appear to be done *in series*. The table scan, on the other hand, is being successfully done in parallel so takes a lot less time even though the total requests are a similar scale and duration per request.

This serial pattern on the requests seems like a performance bug to me.

### To Reproduce

`select distinct(some_column) from my_table`, where the table provider is parquet in Google Cloud Storage.

### Expected behavior

I would hope we can parallelise the requests to Google Cloud Storage! Best case is I'm told it's user error and there's a simple fix, otherwise if it's work needed in datafusion perhaps I can contribute a fix.

**Comment by samuelcolvin** [comment]
Thanks @davidhewitt, one extra note - if it would help anyone looking into this to see the Logfire live view of the trace, as well as the screenshot, happy to send some data to temporary project and share it with them.

**Comment by davidhewitt** [comment]
Ok great, so this is happily user error!

After digging around with the query plans and understanding that each file group is loaded sequentially by design, I found `ListingOptions::with_target_partitions`, and after setting that suitably, problem solved! 🚀 

![image](https://github.com/apache/datafusion/assets/1939362/93065f8d-11e6-4254-ae6e-69bfcbda4255)
