### ISSUE TITLE
Precision/length parameter of varchar/char types is ignored

### ISSUE THREAD

**Issue by lowka** [apache/datafusion#10743]
### Describe the bug

Since Datafusion has no Utf8(n) type precision/length parameter of varchar/char types is ignored and this leads to unexpected results in CAST expressions.

### To Reproduce

The following sqllogic test demonstrates the problem (DataFusion returns 12345 instead of 12):

```text
query T
SELECT '12345'::VARCHAR(2)
----
12
```

### Expected behavior

I would expect the following query return either:

 - '12' because casts to Varchar(n) should perform truncation.
 - an error since DataFusion has no Utf8(n) type. And it is better than silently ignore a length parameter.
 
UPD: 
Arbitrary expressions are affected as well.

```text
SELECT s::VARCHAR(2) FROM (VALUES ('12345')) t(s) // ignores type parameter and returns 12345
SELECT s::VARCHAR(2) FROM vals // ignores type parameter is well
```

### Additional context

DDL statements also allow varchar/char(n) types but n parameter is also silently ignored.

**Comment by Lordworms** [comment]
take

**Comment by lowka** [comment]
I updated the issue to make it clear that is not only a problem with literals.

**Comment by alamb** [comment]
Maybe we should simply error if DataFusion encouters a type of `VARCHAR` with an explcit length 🤔  Though if I worry that some people might expect it to work the way it currenty does (ignored)

Perhaps we could make a new configuration setting to control the behavior (`error_on_varchar_with_length` or something),

**Comment by Lordworms** [comment]
> Maybe we should simply error if DataFusion encouters a type of `VARCHAR` with an explcit length 🤔 Though if I worry that some people might expect it to work the way it currenty does (ignored)
> 
> Perhaps we could make a new configuration setting to control the behavior (`error_on_varchar_with_length` or something),

Current idea should be adding a new config parameter and when encounter VARCHAR with specific length, we throw an error. Don't know if it works for you @lowka

**Comment by lowka** [comment]
Taking into account the fact that DataFusion’s SqlParserOptions already has an option to specify different Sql dialects (and different dialects process this length/precision parameter in CAST expression differently - see examples below), adding a config parameter seems like a very reasonable approach.

SQLLite:
```
SELECT CAST('12345' AS VARCHAR(2))
12345
```

BigQuery:
```
SELECT CAST('12345' AS STRING(2))
Parameterized types are not allowed in CAST expressions.
```

**Comment by Lordworms** [comment]
> Taking into account the fact that DataFusion’s SqlParserOptions already has an option to specify different Sql dialects (and different dialects process this length/precision parameter in CAST expression differently - see examples below), adding a config parameter seems like a very reasonable approach.
> 
> SQLLite:
> 
> ```
> SELECT CAST('12345' AS VARCHAR(2))
> 12345
> ```
> 
> BigQuery:
> 
> ```
> SELECT CAST('12345' AS STRING(2))
> Parameterized types are not allowed in CAST expressions.
> ```

Sure, I will do it
