### ISSUE TITLE
`stride` arg of `array_slice()` should be optional

### ISSUE THREAD

**Issue by yutannihilation** [apache/datafusion#10740]
### Describe the bug

Currently, all args of `array_slice()` is mandatory, but `stride` seems optional.

https://docs.rs/datafusion/38.0.0/datafusion/functions_array/expr_fn/fn.array_slice.html:
```rust
pub fn array_slice(array: Expr, begin: Expr, end: Expr, stride: Expr) -> Expr
```

code:
https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion/functions-array/src/extract.rs#L296-L305

### To Reproduce

n/a

### Expected behavior

n/a

### Additional context

n/a

**Comment by jonahgao** [comment]
Hi @yutannihilation , this has been fixed on the main branch. 
https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion/functions-array/src/extract.rs#L224-L231

**Comment by yutannihilation** [comment]
Oh, great! Sorry that I didn't look at the latest code. I'm closing.
