### ISSUE TITLE
Merge `ScalarUDFImpl`'s `invoke_no_args` and `invoke` into one method

### ISSUE THREAD

**Issue by lewiszlw** [apache/datafusion#10773]
### Is your feature request related to a problem or challenge?

Current api design does not look very elegant. And users need handle no args and args separately.

### Describe the solution you'd like

Propose a solution
```rust
pub trait ScalarUDFImpl: Debug + Send + Sync {
    fn invoke(&self, _args: &[ColumnarValue], info: InvokeInfo) -> Result<ColumnarValue>;
    ...
}

pub struct InvokeInfo {
    number_rows: usize
    // we could add more info in the future
}
```

**Comment by alamb** [comment]
Thank you @lewiszlw 

I agree that your design with an additional `InvokeInfo` is more elegant / easier to use and if we were starting today without any existing code / user defined functions it would likely be the best solution

If we had an additional usecase for more information to pass to `invoke` (e.g. the `//we could add more info in the future`)  I think that would make the argument for adding `info` more compelling. But the no rows case is so special it is hard to justify a large API churn in my opinion

We have a large number of existing functions (not just in DataFusion itself but many other places) so I think changing the API would require substantial downstream changes.

Given how specialized the usecase is ([159 `invoke`](https://github.com/search?q=repo%3Aapache%2Fdatafusion%20invoke&type=code), [7 `invoke_no_args`](https://github.com/search?q=repo%3Aapache%2Fdatafusion+invoke_no_args&type=code) I personally think adding `InvokeInfo` would be a larger cost than it would benefit.



cc @jayzhan211  for your thoughts

**Comment by jayzhan211** [comment]
> Thank you @lewiszlw
> 
> I agree that your design with an additional `InvokeInfo` is more elegant / easier to use and if we were starting today without any existing code / user defined functions it would likely be the best solution
> 
> If we had an additional usecase for more information to pass to `invoke` (e.g. the `//we could add more info in the future`) I think that would make the argument for adding `info` more compelling. But the no rows case is so special it is hard to justify a large API churn in my opinion
> 
> We have a large number of existing functions (not just in DataFusion itself but many other places) so I think changing the API would require substantial downstream changes.
> 
> Given how specialized the usecase is ([159 `invoke`](https://github.com/search?q=repo%3Aapache%2Fdatafusion%20invoke&type=code), [7 `invoke_no_args`](https://github.com/search?q=repo%3Aapache%2Fdatafusion+invoke_no_args&type=code) I personally think adding `InvokeInfo` would be a larger cost than it would benefit.
> 
> cc @jayzhan211 for your thoughts

Totally agree, this is the reason why it is designed like this.

If a situation arises where a function needs both arguments and row information, we can reconsider whether we need the `InvokeInfo`

**Comment by lewiszlw** [comment]
Ok, got it. We can improve it when we have real need.
