### ISSUE TITLE
`array_slice` panicked when called with empty args

### ISSUE THREAD

**Issue by jonahgao** [apache/datafusion#10791]
### Describe the bug

thread 'main' panicked at datafusion/functions-array/src/extract.rs:255:39:
index out of bounds: the len is 0 but the index is 0

### To Reproduce

Run the query in CLI
```sh
DataFusion CLI v38.0.0
> select array_slice();

thread 'main' panicked at datafusion/functions-array/src/extract.rs:255:39:
index out of bounds: the len is 0 but the index is 0
```

### Expected behavior

Return an error instead of panic.

**Comment by jayzhan211** [comment]
This should be handled by signature

**Comment by jonahgao** [comment]
> This should be handled by signature

It panicked at [display_name](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/functions-array/src/extract.rs#L255), happened before checking the signature. 
Maybe we can check the signature earlier, but for now, I plan to fix the display_name directly.
