### ISSUE TITLE
Implement `ScalarValue::TimestampMillisecond` -> String Support

### ISSUE THREAD

**Issue by phillipleblanc** [apache/datafusion#10797]
### Is your feature request related to a problem or challenge?

Part of #9494 to complete support for Unparsing LogicalPlan to SQL String.

Converting LogicalPlans back to SQL is valuable for several usecases such as using DataFusion in federated databases (e.g. generate SQL to push down) or using DataFusion's expr APIs to programmatically create SQL.

### Describe the solution you'd like

Support converting expression that are scalar timestamp millisecond values:

Here `ts` is a column with the schema: `Timestamp(Millisecond, None)`

```
> describe timestamp_test;
+----------------+------------------------------+-------------+
| column_name    | data_type                    | is_nullable |
+----------------+------------------------------+-------------+
...
| time           | Timestamp(Millisecond, None) | YES         |
```

```
sql> select * from timestamp_test where ts > to_timestamp_millis('2024-01-01');
External error: This feature is not implemented: Unsupported DataType: conversion: Timestamp(Millisecond, None)
```

The logical plan derived from parsing the above query should be able to be turned back into SQL.

### Describe alternatives you've considered

The basic pattern is:

Implement the Expr --> AST reverse code in Unparser::expr_to_sql([source link](https://github.com/apache/datafusion/blob/16346022ed4564211c0fb4bf20ac165f2c481a90/datafusion/sql/src/unparser/expr.rs#L93-L94))
Add a test to [expr_to_sql_ok](https://github.com/apache/datafusion/blob/16346022ed4564211c0fb4bf20ac165f2c481a90/datafusion/sql/src/unparser/expr.rs#L912-L913)
Note you can run the tests like

```
cargo test -p datafusion-sql -- expr_to_sql_ok
```

**Comment by pingsutw** [comment]
take

**Comment by goldmedal** [comment]
Hi @pingsutw, are you still working on this issue? I think this issue is very similar to #10984. If you have no idea how to implement this, I think it may be helpful for you.
If you're no longer working on this, I would like to take over this issue if you don't mind. 
Thanks.

**Comment by pingsutw** [comment]
> I think this issue is very similar to https://github.com/apache/datafusion/pull/10984. If you have no idea how to implement this, I think it may be helpful for you.

Thank you! this is really helpful. I'll work on it today
