### ISSUE TITLE
Efficiently and correctly Extract Page Index statistics into `ArrayRef`s

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10806]
### Is your feature request related to a problem or challenge?

Related to https://github.com/apache/datafusion/issues/10453

There are at least two types of statistics stored in Parquet files

1. `ColumnChunk` level statistics (a min/max/null_count per column per row group): [`RowGroupMetadata`](https://docs.rs/parquet/latest/parquet/file/metadata/struct.RowGroupMetaData.html) --> [ColumnChunkMetaData](https://docs.rs/parquet/latest/parquet/file/metadata/struct.ColumnChunkMetaData.html) --> [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<&[Statistics](https://docs.rs/parquet/latest/parquet/file/statistics/enum.Statistics.html)>
2. "Page Index" statistics (stored per page, may be more than one page per column per row group): [ColumnChunkMetaData](https://docs.rs/parquet/latest/parquet/file/metadata/struct.ColumnChunkMetaData.html) --> [read_columns_indexes](https://docs.rs/parquet/latest/parquet/file/page_index/index_reader/fn.read_columns_indexes.html#) --> [Vec](https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html)<[Index](https://docs.rs/parquet/latest/parquet/file/page_index/index/enum.Index.html)>

As part of  https://github.com/apache/datafusion/issues/10453 we have pulled conversion of the `ColumnChunk` level statistics into `StatisticsConverter` and https://github.com/apache/datafusion/pull/10802 prunes the row groups using this API

It would be good to apply the same treatment to the statistics in the page index

### Describe the solution you'd like

1. Add a clear API to efficiently extract page statistics outside of DataFusion
2. Ensure that API is well tested
3. Ensure the API is fast

### Describe alternatives you've considered

1. Move / refactor the code to extract `ArrayRef` from Index in page_filter ([source link](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L394-L567)) to `StatisticsConverter` ([source](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L363))
2. Update the tests in arrow_statistics  ([source](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/core/tests/parquet/arrow_statistics.rs#L180-L237)) to also verify that the page statistics are correct (I believe the page min/maxes should be the same as the row group min/maxes)
3. Update the parquet code `prune_pages_in_one_row_group` ([source](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L301-L365)) to use the new `StatisticsExtractor` code
4. Update the benchmark ([source](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/core/benches/parquet_statistic.rs#L152)) for extracting page statistics and use that to ensure the statistics extraction code is reasonably performant

**Comment by marvinlanhenke** [comment]
@alamb 
I was briefly looking at this, trying to understand whats needed here (since I'm very unfamiliar here).

Do we already have a helper fn at place to write a parquet file with `Page Index` statistics? While I was "prototyping" I tried to get the `metadata.column_index()` by using the existing `make_test_file_rg` - but it seems page index stats are not written (None)? 

I'll keep on looking - but perhaps you have a quick pointer here, where to look?

**Comment by alamb** [comment]
Thanks @marvinlanhenke 🙏 

To write the relevant structues into Parquet, the [statistics_enable](https://docs.rs/parquet/latest/parquet/file/properties/struct.WriterProperties.html#method.statistics_enabled) field needs to be [Page](https://docs.rs/parquet/latest/parquet/file/properties/enum.EnabledStatistics.html#variant.Page)

To read them back, the reader needs to be configured with [with_page_index](https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ArrowReaderOptions.html#method.with_page_index) I think

Also I have a proposed change to the Statistics code in https://github.com/apache/datafusion/pull/10802

If that gets merged, then the API for extracting the mins from data pages might look like

```rust
        // get relevant index statistics somehow
        let data_page_statatistics: Vec<&Statistics> = todo!();
        let converter = StatisticsConverter::try_new(
            column_name,
            reader.schema(),
            reader.parquet_schema(),
        );
        // get mins from the ColumnIndex
        let mins = converter.column_index_mins(data_page_statatistics).unwrap();
```

**Comment by marvinlanhenke** [comment]
The proposed Api looks nice 👌Until the merge I can use the time to explore and prototype. Thanks for the pointers

**Comment by marvinlanhenke** [comment]
@alamb 
...while prototyping I ran into an "issue" or some questions, perhaps you can help here.

Since we could have more than one page per column per row-group, I implemented the e.g. `min` statistics as an Iterator to yield the global minimum across all pages. First of all does this even make sense here?
```Rust
impl<'a, I> Iterator for MinInt64PageStatsIterator<'a, I>
where
    I: Iterator<Item = Option<&'a Index>>,
{
    type Item = Option<i64>;
    fn next(&mut self) -> Option<Self::Item> {
        let next = self.iter.next();
        next.flatten().map(|index| match index {
            Index::INT64(native_idx) => native_idx
                .indexes
                .iter()
                .flat_map(|page_idx| page_idx.min)
                .min(),
            _ => None,
        })
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.iter.size_hint()
    }
}
```

If it does make sense to "coalesce" into a global page minimum, I'll run into trouble later on when I create those iterators for `f32, f64` since the trait `Ord` is not implemented. We could workaround this by using `reduce(f32::min)` - but I want to check if I'm on the right track at all - or perhaps I should coalesce the page minimum into a global?

**Comment by marvinlanhenke** [comment]
@alamb 
...just to confirm my current understanding.

Since we can have more than one page per column per row group, I can get multiple statistics. Or put differently one ArrayRef per Page.

For example if we have a column A with row_group R1 and Pages P1 & P2, I would retrieve statistics for P1 & P2? 
- A.R1.P1 {min: Some(2), max: Some(5), ...}
- A.R1.P2 {min: Some(1), max: Some(4), ...}

Thus, instead of extracting a single `Result<ArrayRef>` in the `StatisticsExtractor` we should return a `Result<Vec<ArrayRef>>`?

I think we have to do this, in order to use the new API within `prune_pages_in_one_row_group` which creates an Vec<ArrayRef> when pruning against the predicate [here](https://github.com/apache/datafusion/blob/main/datafusion/core/src/physical_optimizer/pruning.rs#L885)?

**Comment by marvinlanhenke** [comment]
@alamb
I'm currently thinking about how to integrate `StatisticsConverter` with the existing code `prune_pages_in_one_row_group`.

This is what I originally had in mind for the converter method:
```Rust
    pub fn column_index_mins(&self, metadata: &ParquetMetaData) -> Result<ArrayRef> {
        let data_type = self.arrow_field.data_type();

        let Some(parquet_column_index) = metadata.column_index() else {
            return Ok(self.make_null_array(data_type, metadata.row_groups()));
        };

        let Some(parquet_index) = self.parquet_index else {
            return Ok(self.make_null_array(data_type, metadata.row_groups()));
        };

        let row_group_page_indices = parquet_column_index
            .into_iter()
            .map(|x| x.get(parquet_index));
        min_page_statistics(Some(data_type), row_group_page_indices)
    }
```
So we would simply create an iterator for all row groups column indices, match the index and apply the stats_func. Which works - all tests are passing.

However, the API, or the integration with `prune_pages_in_one_row_group` feels kind of strange:
- a lot of work the StatisticConverter does is already done [here](https://github.com/apache/datafusion/blob/main/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L155-L187)
- we already iterate over each row_group individually, extracting a single Option<&Index> [here](https://github.com/apache/datafusion/blob/main/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L169-L196) and passing it into `prune_pages_per_one_row_group`

Now, my API has to change. I'm wondering how specific it should be? 
If we pass `&Index` as a parameter, I can match the index and extract the statistic as done [here](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L394-L567). However, I'm not sure this is the way to go. We'd simply move the `get_min_max_values_for_page_index` method, and basically have no need for the StatisticConverter?

Maybe I'm missing something, but I think it would help to maybe outline the scope of the refactor you had in mind.

**Comment by alamb** [comment]
Thank you @marvinlanhenke -- excellent analysis. 

> * a lot of work the StatisticConverter does is already done [here](https://github.com/apache/datafusion/blob/main/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L155-L187)

Yes. It is my eventual goal for all of the code to convert `Index` to `ArrayRef` in `page_filter.rs` is gone and `page_filter.rs` only calls `StatisticsConverter`. 

To avoid a massive PR, however, I think it makes sense to add new code to `StatisticsConverter` for extracting page values, and then when it is complete enough switch `page_filter.rs` to use `StatisticsConverter`

> * we already iterate over each row_group individually, extracting a single Option<&Index> [here](https://github.com/apache/datafusion/blob/main/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L169-L196) and passing it into `prune_pages_per_one_row_group`

Indeed that is how it works today (one row group at a time). I eventually hope/plan to apply the same treatment to data page filtering as I did to row group filtering in https://github.com/apache/datafusion/pull/10802 (that is, make a single call to `PruningPredicate::prune` for the all the remaining row groups. 

> Now, my API has to change. I'm wondering how specific it should be? If we pass `&Index` as a parameter, I can match the index and extract the statistic as done [here](https://github.com/apache/datafusion/blob/ece7ae5eca451bb2599f13f9f9197fd93b2a8bc2/datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs#L394-L567). However, I'm not sure this is the way to go. We'd simply move the `get_min_max_values_for_page_index` method, and basically have no need for the StatisticConverter?

let me play around with some options and get back to you

**Comment by alamb** [comment]
@marvinlanhenke  -- I whipped up something (actually I had been playing with it yesterday) https://github.com/apache/datafusion/pull/10843

**Comment by marvinlanhenke** [comment]
Thank you so much - I quickly skimmed the draft you uploaded (will take a closer look tomorrow). However, the main question should be answered, for now we are iterating over each row group one by one using a row group index.

I also agree about the scope for now, however can see the overall picture where this is going somewhat clearer now, so thanks for explaining that.

I'll try to incorporate your suggestions and upload a draft myself, so we have something more concrete to reason about.

**Comment by alamb** [comment]
Follow on work tracked in https://github.com/apache/datafusion/issues/10922
