### ISSUE TITLE
Convert `stddev` to udaf

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10827]
### Is your feature request related to a problem or challenge?

Similar to #10713 and others in #8708

1. Move code from `datafusion/physical-expr/src/aggregate/stddev.rs` to `datafusion/functions-aggregate/src/stddev.rs`
2. Add expression api in roundtrip_expr_api in datafusion/proto/tests/cases/roundtrip_logical_plan.rs
3. Use lowercase for `name`

**Comment by goldmedal** [comment]
take

**Comment by goldmedal** [comment]
Hi @jayzhan211,
Although this issue only mentions `stddev`, I'm thinking about `stddev_pop`. Should I also convert it to UDAF? I found that #10713 only converted `var_sample` but left `variance_pop`. Is there any reason we didn't convert `variance_pop` too?

**Comment by jayzhan211** [comment]
> Hi @jayzhan211, Although this issue only mentions `stddev`, I'm thinking about `stddev_pop`. Should I also convert it to UDAF? I found that #10713 only converted `var_sample` but left `variance_pop`. Is there any reason we didn't convert `variance_pop` too?

We should also convert population function, variance pop is tracked at https://github.com/apache/datafusion/issues/10668.
stddev_pop is also on the todo list in #8708.

**Comment by goldmedal** [comment]
Got it. I think I can convert them in the same PR. Thanks.
