### ISSUE TITLE
Implement `approx_distinct` using HyperLogLog

### ISSUE THREAD

**Issue by jimexist** [apache/datafusion#1083]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

Implement [HyperLogLog functions](https://trino.io/docs/current/functions/hyperloglog.html)

**Describe the solution you'd like**

Similar to that of [presto/trino](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/ApproximateCountDistinctAggregation.java)

**Describe alternatives you've considered**

**Additional context**

**Comment by Jimexist** [comment]
@houqp @alamb is this of any use to your usecases?

**Comment by Jimexist** [comment]
relevant links:
1. [smhasher](https://github.com/aappleby/smhasher/wiki)
2. [`hyperloglog.c` from redis](https://github.com/yahoo/redislite/blob/master/redis.submodule/src/hyperloglog.c)
3. [`xxhash` v.s. `murmur3`](https://aras-p.info/blog/2016/08/02/Hash-Functions-all-the-way-down/)
