### ISSUE TITLE
Stop changing the case for COPY TO option values

### ISSUE THREAD

**Issue by tinfoil-knight** [apache/datafusion#10853]
### Describe the bug

Currently, we're changing the case of every option value passed with the COPY statement:

https://github.com/apache/datafusion/blob/3773fb7fb54419f889e7d18b73e9eb48069eb08e/datafusion/sql/src/statement.rs#L891-L900

This causes an issue in cases where the option values for some external integrations might be case sensitive (eg. like access keys).

@xinlifoobar found this while working on adding an integration to huggingface in https://github.com/apache/datafusion/pull/10792.

See previous discussion here: https://github.com/apache/datafusion/pull/9723#discussion_r1632879391

### Expected behavior

There should be some way to pass option values as is for certain integrations.

**Comment by alamb** [comment]
fyi @metesynnada

**Comment by xinlifoobar** [comment]
Sorry if I mislead you. I encountered this issue in the `CREATE EXTERNAL TABLE` statement as 

https://github.com/apache/datafusion/blob/3773fb7fb54419f889e7d18b73e9eb48069eb08e/datafusion/sql/src/statement.rs#L1017-L1025

How has such an issue typically been resolved previously? If adding a `ParseOptions`, e.g., `enable_options_value_normalization`, is a reasonable way to fix it, I could help there.

https://github.com/apache/datafusion/blob/47026a2a3dd41a5c87e44ade58d91a89feba147b/datafusion/sql/src/planner.rs#L97-L100

**Comment by berkaysynnada** [comment]
I believe we can remove the lowercase conversion here and instead add it when we set `ConfigField`'s (via `alter_with_string_hash_map`) for the cases where we can ignore case sensitivity.

**Comment by berkaysynnada** [comment]
If no one else is working on this issue, I'll take it. My plan is to remove the automatic conversion of values to lowercase and to create a lookup table for keys. This table will indicate the specific standardization methods.

**Comment by alamb** [comment]
Another potential option is to follow the model of the `datafusion.sql_parser.enable_ident_normalization` [configuration setting](https://datafusion.apache.org/user-guide/configs.html) to control if the options should be case sensitive or not. That might be the "least surprising" to people who are used (or not used) to SQL identifier normalization rules

I don't remember wll the usecases for configuration option case sensitivity, so please ignore this suggestion if it doesn't make sense

**Comment by xinlifoobar** [comment]
> enable_options_value_normalization

I draft #11330 to discuss this. Let me know your thoughts!
