### ISSUE TITLE
Support for contains function in datafusion substrait consumer

### ISSUE THREAD

**Issue by richtia** [apache/datafusion#10861]
### Is your feature request related to a problem or challenge?

Datafusion does not have a contains function and will return an exception if a substrait plan contains it

```
Exception: DataFusion error: NotImplemented("Unsupported function name: \"contains:str_str\"")
```

### Describe the solution you'd like

When the datafusion consumer sees the `contains` function, it can convert it to a combination of `strpos` + `>`

```
strpos(lit("abcd"), lit("de") > 0
```

**Comment by Lordworms** [comment]
take

**Comment by Lordworms** [comment]
Do we really need this conversion? what about adding a new ScalarFunction 'contains'? @alamb I would like to receive your advice here.

**Comment by alamb** [comment]
I am not sure @Lordworms  -- maybe @waynexia  or @Blizzara  have more context / understanding 

@richtia does this request come from a particular query you are runniing?

**Comment by richtia** [comment]
My preference would actually be to add the function as well. The request came from trying to run a query with the contains function.

**Comment by Blizzara** [comment]
+1 to adding the function into DataFusion (+ the relevant mapping into Substrait) if it doesn't exist yet.

Seems like Arrow has a `contains` function but I cannot find it in DataFusion so maybe it doesn't indeed exist yet, dunno if the Arrow version can somehow be easily used?

**Comment by Lordworms** [comment]
> +1 to adding the function into DataFusion (+ the relevant mapping into Substrait) if it doesn't exist yet.
> 
> Seems like Arrow has a `contains` function but I cannot find it in DataFusion so maybe it doesn't indeed exist yet, dunno if the Arrow version can somehow be easily used?

Sure, I'll file a PR later today

**Comment by richtia** [comment]
> +1 to adding the function into DataFusion (+ the relevant mapping into Substrait) if it doesn't exist yet.
> 
> Seems like Arrow has a `contains` function but I cannot find it in DataFusion so maybe it doesn't indeed exist yet, dunno if the Arrow version can somehow be easily used?

I didn't see the function in DataFusion either.  I also couldn't find it in Arrow, at least not under any compute function.

**Comment by Lordworms** [comment]
> > +1 to adding the function into DataFusion (+ the relevant mapping into Substrait) if it doesn't exist yet.
> > Seems like Arrow has a `contains` function but I cannot find it in DataFusion so maybe it doesn't indeed exist yet, dunno if the Arrow version can somehow be easily used?
> 
> I didn't see the function in DataFusion either. I also couldn't find it in Arrow, at least not under any compute function.

<img width="791" alt="image" src="https://github.com/apache/datafusion/assets/48054792/0915aa1f-656f-4fc6-8689-570f2f5e9e45">
I think DuckDB got a similar function, let me know if it is ok for me to implement similar behavior like this

**Comment by richtia** [comment]
Yeah, duckdb has a contains function as well as the substrait support.  The same substrait plans that gave me the datafusion errors were able to execute against the DuckDB substrait consumer.
