### ISSUE TITLE
`array_to_string` panic on dictionary values

### ISSUE THREAD

**Issue by appletreeisyellow** [apache/datafusion#10862]
### Describe the bug

`array_to_string` function panic's when running a query on data that has dictionary data type. To fix the panic, `array_to_string` needs to support dictionary type

### To Reproduce

1. Use DataFusion CLI:
```shell
# in dir datafusion/datafusion-cli
$ cargo build
$ ./target/debug/datafusion-cli
```

2. Write sample data
```sql
CREATE TABLE table1 AS VALUES (1, arrow_cast('foo', 'Dictionary(Int32, Utf8)')), (2, arrow_cast('bar', 'Dictionary(Int32, Utf8)'));
```

3. Run query
```sql
> SELECT array_to_string(array_agg(column2),',') FROM (SELECT column2 FROM table1);
thread 'main' panicked at .../datafusion/datafusion/functions-array/src/string.rs:298:17:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

```sql
> SELECT array_to_string(array_agg(column2),',') FROM (SELECT column2 FROM table1);
+------------------------------------------------------+
| array_to_string(ARRAY_AGG(table2.column2),Utf8(",")) |
+------------------------------------------------------+
| foo,bar                                              |
+------------------------------------------------------+
```

### Additional context

1. Here are the data types that `array_to_string` currently supports:
https://github.com/apache/datafusion/blob/59120255916bcd624161ce8f5df255f2cc838406/datafusion/functions-array/src/string.rs#L63-L101

2. instead of panic, it would be better to throw an error

**Comment by alamb** [comment]
I think this is a good first issue as it is well documented , has a test case and the desired behavior is well understood

**Comment by evegaval** [comment]
I would like to take this one.

**Comment by evegaval** [comment]
take

**Comment by EduardoVega** [comment]
take
