### ISSUE TITLE
Convert `ApproxPercentileCont` and ``ApproxPercentileContWithWeight` to UDAF

### ISSUE THREAD

**Issue by goldmedal** [apache/datafusion#10870]
### Is your feature request related to a problem or challenge?

Similar to #10838 and others #8708
However, there're some challenge to convert `ApproxPercentileCont`.
I discussed with @jayzhan211 in https://github.com/apache/datafusion/issues/10838#issuecomment-2156419089

**Comment by goldmedal** [comment]
take

**Comment by goldmedal** [comment]
Hi @jayzhan211,

Continuing from our previous discussion in https://github.com/apache/datafusion/issues/10838#issuecomment-2156459652, I believe there are still some issues.

We create `AccumulatorArgs` in 
https://github.com/apache/datafusion/blob/main/datafusion/physical-expr-common/src/aggregate/mod.rs#L287.

However, `AggregateFunctionExpr` only takes `args` that are `PhysicalExpr`. I think `AccumulatorArgs` is a logical plan struct that should be placed in `datafusion-expr`. It can't access `PhysicalExpr`.

Curiously, is it possible to convert `PhysicalExpr` back to `Expr`?
If not, I plan to pass the original `Expr` to `AggregateFunctionExpr` (just like `sort_exprs: Vec<Expr>`), then pass it to `AccumulatorArgs`.

Does this make sense? What do you think?
Thanks

**Comment by jayzhan211** [comment]
> is it possible to convert PhysicalExpr back to Expr?

I think it is possible, but in this case, we can pass the `Expr: Vec<Expr>` to `AggregateFunctionExpr ` like `SortExpr` it
