### ISSUE TITLE
`fetch_statistics` for a given ParquetMetaData

### ISSUE THREAD

**Issue by NGA-TRAN** [apache/datafusion#10877]
### Is your feature request related to a problem or challenge?

In InfluxDB, we want to have a a function similar to [fetch_statistics](https://github.com/apache/datafusion/blob/47026a2a3dd41a5c87e44ade58d91a89feba147b/datafusion/core/src/datasource/file_format/parquet.rs#L458-L536) but the given input is not the `ObjectStore` and `ObjectMeta` but the `ParquetMetaData`

### Describe the solution you'd like

Refactor  [fetch_statistics](https://github.com/apache/datafusion/blob/47026a2a3dd41a5c87e44ade58d91a89feba147b/datafusion/core/src/datasource/file_format/parquet.rs#L458-L536)  to add one more function that accepts `ParquetMetaData` as input

**Comment by NGA-TRAN** [comment]
@alamb I am working on this

**Comment by alamb** [comment]
Done in https://github.com/apache/datafusion/pull/10880
