### ISSUE TITLE
Convert `Grouping` to UDAF

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10906]
### Is your feature request related to a problem or challenge?

Similar to other issues in #8708

**Comment by Rachelint** [comment]
can I have a try to take it?

**Comment by jayzhan211** [comment]
> can I have a try to take it?

Sure!

**Comment by dharanad** [comment]
Hello @Rachelint I'm writing to follow up on this issue. Since there is no update in the past two weeks, and I wanted to check in and see if i can pick this up. I'd be happy to pick it up.
cc : @jayzhan211

**Comment by Rachelint** [comment]
> Hello @Rachelint I'm writing to follow up on this issue. Since there is no update in the past two weeks, and I wanted to check in and see if i can pick this up. I'd be happy to pick it up. cc : @jayzhan211

Sorry.. I am busy recently... and I am trying to code it yesterday and today.
