### ISSUE TITLE
Convert `BitAnd`, `BitOr`, `BitXor` to UDAF

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10907]
### Is your feature request related to a problem or challenge?

Similar to other issues in #8708

**Comment by dharanad** [comment]
@jayzhan211  I'm really excited about getting involved with this project. This particular issue! Even though it's not marked as a 'good first issue,' I'm feeling confident and eager to dive in, give i have been spend a decent amount of time exploring this project.

I'm confident I can make some progress within a week or two, if not i will assigned it back.

**Comment by dharanad** [comment]
take
