### ISSUE TITLE
Implement equality `=` and inequality `<>` support for `StringView`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10919]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/10918, `[StringViewArray`](https://docs.rs/arrow/latest/arrow/array/type.StringViewArray.html) support in DataFusion

There are several queries in the [clickbench](https://github.com/apache/datafusion/blob/11b7b5c215012231e5768fc5be3445c0254d0169/benchmarks/queries/clickbench/queries.sql#L11-L15) suite like follows:

```sql
SELECT "MobilePhone", "MobilePhoneModel", COUNT(DISTINCT "UserID") AS u FROM hits WHERE "MobilePhoneModel" <> '' GROUP BY "MobilePhone", "MobilePhoneModel" ORDER BY u DESC LIMIT 10;
SELECT "SearchPhrase", COUNT(*) AS c FROM hits WHERE "SearchPhrase" <> '' GROUP BY "SearchPhrase" ORDER BY c DESC LIMIT 10;
SELECT "SearchPhrase", COUNT(DISTINCT "UserID") AS u FROM hits WHERE "SearchPhrase" <> '' GROUP BY "SearchPhrase" ORDER BY u DESC LIMIT 10;
SELECT "SearchEngineID", "SearchPhrase", COUNT(*) AS c FROM hits WHERE "SearchPhrase" <> '' GROUP BY "SearchEngineID", "SearchPhrase" ORDER BY c DESC LIMIT 10;
```

where `"MobilePhoneModel"` and `"SearchPhrase"` are string columns with predicates (in this case checking for empty string)

### Describe the solution you'd like

In order to improve performance of these queries we will need the ability to actually compare `StringViewArrays`  to constant strings (and likely to each other)

Thus I would like to be able to run 

`StringViewColumn = scalar`
`StringViewColumn = StringViewColumn`

(and likewise for BinaryView)

I basically want to to run the following queries (where table `foo` has `StringView` columns)

```sql
> create table foo as values ('Andrew', 'X'), ('Xiangpeng', 'Xiangpeng'), ('Raphael', 'R');
0 row(s) fetched.
Elapsed 0.002 seconds.

> select * from foo where column1 = 'Andrew';
+---------+---------+
| column1 | column2 |
+---------+---------+
| Andrew  | X       |
+---------+---------+
1 row(s) fetched.
Elapsed 0.003 seconds.

> select * from foo where column1 <> 'Andrew';
+-----------+-----------+
| column1   | column2   |
+-----------+-----------+
| Xiangpeng | Xiangpeng |
| Raphael   | R         |
+-----------+-----------+
2 row(s) fetched.
Elapsed 0.001 seconds.

> select * from foo where column1 = column2;
+-----------+-----------+
| column1   | column2   |
+-----------+-----------+
| Xiangpeng | Xiangpeng |
+-----------+-----------+
1 row(s) fetched.
Elapsed 0.002 seconds.

> select * from foo where column1 <> column2;
+---------+---------+
| column1 | column2 |
+---------+---------+
| Andrew  | X       |
| Raphael | R       |
+---------+---------+
2 row(s) fetched.
Elapsed 0.001 seconds.
```

### Describe alternatives you've considered

I suspect we will need to update the coercion logic and maybe also the arrow equality kernels like https://docs.rs/arrow/latest/arrow/compute/kernels/cmp/fn.eq.html

**Comment by Weijun-H** [comment]
I am glad to pick this ticket.

**Comment by Weijun-H** [comment]
This issue must wait until #10920 because there is currently no convenient way to create a `StringViewArray` in Datafusion. If I am mistaken, please correct me.

**Comment by alamb** [comment]
> This issue must wait until #10920 because there is currently no convenient way to create a `StringViewArray` in Datafusion. If I am mistaken, please correct me.

I think you are right -- conveniently @XiangpengHao has one here https://github.com/apache/datafusion/pull/10925

**Comment by XiangpengHao** [comment]
Hi @Weijun-H , great to know you are working on this!
 I believe implementing this feature will eventually require https://github.com/apache/arrow-rs/issues/5897 to be solved, so I'm working on that issue so you won't be blocked

**Comment by alamb** [comment]
BTW I made a branch to work on StringView in DataFusion: https://github.com/apache/datafusion/issues/10961

**Comment by alamb** [comment]
StringView comparison added in https://github.com/apache/datafusion/pull/10985
