### ISSUE TITLE
`StatisticsConverter::row_group_null_counts` incorrect for missing column

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10926]
### Describe the bug

 I noticed this while working on https://github.com/apache/datafusion/pull/10852 with @marvinlanhenke

Basially, when generating statistics for a non existent column, the StatisticsExtractor will return a null array of the type of the column not a UInt64Array

Specifically https://github.com/apache/datafusion/blob/2f4347647172f6997448b2e24d322b50c856f3a0/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L871-L886

The same problem exists for  `data_page_null_counts` and `data_page_row_counts` (not for `row_group_row_counts`

### To Reproduce

Try to call row_group_null_counts for a column that isn't in the parquet file

### Expected behavior

1. row_group_null_counts should always return an `UInt64Array` (not an `ArrayRef`)
2. If there is not a column, the UInt64Array should be all nulls

**Comment by marvinlanhenke** [comment]
take

**Comment by marvinlanhenke** [comment]
@alamb 
...should we also change the signature and return `Result<Uint64Array>`? 
This however, would require to downcast_ref the result from `new_null_array` and clone the result. 

Something like:
```Rust
let Some(parquet_index) = self.parquet_index else {
            return Ok(self
                .make_null_array(&DataType::UInt64, metadatas)
                .as_any()
                .downcast_ref::<UInt64Array>()
                .expect("failed to downcast array")
                .clone());
        };
```

**Comment by alamb** [comment]
> Should we also change the signature and return Result<Uint64Array>?

Yes I think so

> Should we also change the signature and return Result<Uint64Array>?

I actually think using `new_null_array` is wrong here. It returns the wrong type -- for example if we are getting row counts for a `Utf8` column, using new_null_arrray will return a `StringArray` rather than a `UInt64Array`. 

I actually hit this issue when working on https://github.com/apache/datafusion/pull/10924 

And I had to change it to 

```rust
        let Some(parquet_index) = self.parquet_index else {
            let num_row_groups = metadatas.into_iter().count();
            return Ok(Arc::new(UInt64Array::from_iter(
                std::iter::repeat(None).take(num_row_groups),
            )));
        };
```

To make a test pass

**Comment by marvinlanhenke** [comment]
> I actually think using `new_null_array` is wrong here. It returns the wrong type

I passed `&DataType::UInt64` into `new_null_array(...)`. However, your approach solves the issue with downcasting the result from new_null_array so it makes more sense here. Thank you.

Just to confirm my understanding (regarding my second question) `row_group_row_counts` should also return a null_array when we reference a non-existing column correct?
