### ISSUE TITLE
Update ListingTable to use `StatisticsConverter`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10923]
### Is your feature request related to a problem or challenge?

Thanks to https://github.com/apache/datafusion/issues/10453, we now have the very nice `StatisticsConverter` API ([code link](https://github.com/apache/datafusion/blob/9ab597b2511b23dc951c9f35d00d38c2071e9fea/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L566-L589)) that extracts statistics from parquet row groups and is well tested. 

However, there is a different code path that extracts and summarizes statistics in `ListingTable` used for pruning files https://github.com/apache/datafusion/blob/9ab597b2511b23dc951c9f35d00d38c2071e9fea/datafusion/core/src/datasource/file_format/parquet.rs#L310-L373

In addition to being more code, this also seems like it doesn't properly convert the data types

Which is used https://github.com/apache/datafusion/blob/ea21b08e477cc48f458917c132f79c4980c957c1/datafusion/core/src/datasource/file_format/parquet.rs#L511-L535

- @NGA-TRAN  recently made this API public in https://github.com/apache/datafusion/pull/10880 but I think we can do better

### Describe the solution you'd like

I would like to update the code to use `StatisticsConverter` and rather than converting row/column at a time

**Comment by xinlifoobar** [comment]
I did not notice there was a PR already. Feel free to close mine.
