### ISSUE TITLE
Support extracting `Int8`, `Int16`, `Int32` statistics from Parquet Data Pages

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10928]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/10922

We are adding APIs to efficiently convert the data stored in Parquet's "PageIndex" into `ArrayRef`s -- which will make it significiantly easier to use this information for pruning and other tasks.

### Describe the solution you'd like

Add support to `StatisticsConverter::min_page_statistics` and `StatisticsConverter::max_page_statistics` for the types above

https://github.com/apache/datafusion/blob/2f4347647172f6997448b2e24d322b50c856f3a0/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L637-L656

### Describe alternatives you've considered

1. Update the test for the listed data types following the model of  `test_int64` https://github.com/apache/datafusion/blob/2f4347647172f6997448b2e24d322b50c856f3a0/datafusion/core/tests/parquet/arrow_statistics.rs#L475 (note this API will change slightly in https://github.com/apache/datafusion/pull/10927)
2. Add any required implementation in https://github.com/apache/datafusion/blob/2f4347647172f6997448b2e24d322b50c856f3a0/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L575-L586 (follow the model of the row counts, https://github.com/apache/datafusion/blob/2f4347647172f6997448b2e24d322b50c856f3a0/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L90)

**Comment by alamb** [comment]
FYI @marvinlanhenke

**Comment by Weijun-H** [comment]
take
