### ISSUE TITLE
Convert `Hyperloglog` to UDAF

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10944]
### Is your feature request related to a problem or challenge?

Similar to other issues in #8708

**Comment by dharanad** [comment]
take

**Comment by dharanad** [comment]
Hey @jayzhan211 
I noticed the `approx_distinct` UDAF implemented in `datafusion/functions-aggregate/src/approx_distinct.rs`. It appears to be using a `HyperLogLog` (HLL) structure defined in `datafusion/functions-aggregate/src/hyperloglog.rs`.

What is the expected outcome of this issue. Could you provide some insights into the intended use of this UDAF?

**Comment by jayzhan211** [comment]
yeah, I didn't take a look carefully, we actually don't need this. Let me close this
