### ISSUE TITLE
push down unnest filter only on non-unnest column

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#10989]
### Is your feature request related to a problem or challenge?

In #10974, we push down unnest filter what ever the filter plan is, but if we filter on unnest column, we should not push down the filter plan since the unnest column is not evaluated yet.

```
# test unnest with filter
statement ok
create table t (a int[]) as values ([1,2,3]), ([4,5,6]);

query error DataFusion error: External error: Arrow error: Invalid argument error: Invalid comparison operation: List\(Field \{ name: "item", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: \{\} \}\) > Int32
select ua from (select unnest(a) as ua from t) where ua > 3;
```

The expected result is

```
query
select ua from (select unnest(a) as ua from t) where ua > 3;
----
4
5
6
```

Push down filter plan only if the column is non-unnest.

**Comment by jonahgao** [comment]
It seems to be supported on the [main](https://github.com/apache/datafusion/commit/5cb1917f8c911184b030599f0a3cb86e2d602031) branch.
```sh
DataFusion CLI v39.0.0
> create table t (a int[]) as values ([1,2,3]), ([4,5,6]);
0 row(s) fetched.
Elapsed 0.030 seconds.

> select ua from (select unnest(a) as ua from t) where ua > 3;

+----+
| ua |
+----+
| 4  |
| 5  |
| 6  |
+----+
3 row(s) fetched.
Elapsed 0.009 seconds.
```

**Comment by jayzhan211** [comment]
> It seems to be supported on the [main](https://github.com/apache/datafusion/commit/5cb1917f8c911184b030599f0a3cb86e2d602031) branch.
> 
> ```shell
> DataFusion CLI v39.0.0
> > create table t (a int[]) as values ([1,2,3]), ([4,5,6]);
> 0 row(s) fetched.
> Elapsed 0.030 seconds.
> 
> > select ua from (select unnest(a) as ua from t) where ua > 3;
> 
> +----+
> | ua |
> +----+
> | 4  |
> | 5  |
> | 6  |
> +----+
> 3 row(s) fetched.
> Elapsed 0.009 seconds.
> ```

I still get the error 🤔

**Comment by jayzhan211** [comment]
At the point of `push down filter`, we no longer have `Expr::Unnest` but Expr::Column or Expr::Binary

```
expr: BinaryExpr(BinaryExpr { left: Column(Column { relation: None, name: "unnest(t.a)" }), op: Gt, right: Literal(Int32(3)) })
```

Instead of checking whether there is `unnest` contained in filter expression, should we move the conversion of Expr::Unnest to LogicalPlan::Unnest `try_process_unnest` to the optimization step, specifically at some point **AFTER** push down filter step? I think we can check whether `unnest` exists by `Expr::Unnest`, and also I think we don't need to specialize `LogicalPlan::Unnest` in `push down filter` step, we can deal with `LogicalPlan::Projection` only, Expr::Unnest should be part of the `LogicalPlan::Unnest`. After `push down filter`, we convert Expr::Unnest to `LogicalPlan::Unnest`
