### ISSUE TITLE
Improve filter predicates with `Utf8View` literals

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#10998]
Part of https://github.com/apache/datafusion/issues/10918

### Is your feature request related to a problem or challenge?

DataFusion's predicate creation doesn't work as ideally for Utf8View constants

Specifically, I added a test i https://github.com/apache/datafusion/pull/10997

```sql
explain SELECT column1_utf8 from test where column1_utf8 = arrow_cast('Andrew', 'Utf8View');
logical_plan
01)Filter: CAST(test.column1_utf8 AS Utf8View) = Utf8View("Andrew")
02)--TableScan: test projection=[column1_utf8]
```

This plan is non ideal as it casts the column rather than the constant

### Describe the solution you'd like

Instead of 
```
CAST(test.column1_utf8 AS Utf8View) = Utf8View("Andrew")
```

the filter should be

```
test.column1_utf8 =  Utf8("Andrew")
```

So the expected plan should look like

```sql
explain SELECT column1_utf8 from test where column1_utf8 = arrow_cast('Andrew', 'Utf8View');
logical_plan
01)Filter: test.column1_utf8 = Utf8("Andrew")
02)--TableScan: test projection=[column1_utf8]
```

**Comment by doki23** [comment]
I wonder why #11043 isn't able to close this issue.

**Comment by alamb** [comment]
> I wonder why #11043 isn't able to close this issue.

I agree -- https://github.com/apache/datafusion/pull/11043 should have closed it -- thank you @doki23
