### ISSUE TITLE
Add more support for ScalarValue::Float16 where Float32 and Float64 are supported

### ISSUE THREAD

**Issue by LorrensP-2158466** [apache/datafusion#11083]
### Is your feature request related to a problem or challenge?

When fixing #11076, I noticed that not every method in `ScalarValue `supports a `ScalarValue::Float16` while supporting Float32 and Float64:
For example in (from  #11076):
https://github.com/apache/datafusion/blob/3051d1928eae8f684e1049a2cb00a8e721d70182/datafusion/common/src/scalar/mod.rs#L1170-L1170
We see that F32 and F64 are supported, but not F16
https://github.com/apache/datafusion/blob/3051d1928eae8f684e1049a2cb00a8e721d70182/datafusion/common/src/scalar/mod.rs#L1178-L1179

### Describe the solution you'd like

- Every method that supports Float32 and Float64 should support Float16 (including constructors)
- implement `From<f16>` for ScalarValue
- Add tests
- More to do?

`half::f16` supports many of these operations, so I think it is doable. `ArrowNativeType` and `ArrowNativeTypeOp` are also implemented so we can use a lot of functions from that trait.

### Describe alternatives you've considered

Maybe show in docs why Float16 is not supported in some cases?

### Additional context
Can this be a "good first issue" ?
_No response_

**Comment by Lordworms** [comment]
I'll take it since it is an issue related to me
