### ISSUE TITLE
`gcd` returns negative results

### ISSUE THREAD

**Issue by jonahgao** [apache/datafusion#11098]
### Describe the bug

According to the [Binary GCD algorithm](https://en.wikipedia.org/wiki/Binary_GCD_algorithm), its result cannot be a negative number.

<img width="964" alt="截屏2024-06-24 21 31 30" src="https://github.com/apache/datafusion/assets/26053282/ff33090f-8c7c-408e-9b35-e0f975c73fa9">

### To Reproduce

```sh
DataFusion CLI v39.0.0
> select gcd(-100, 0), gcd(0, -100);
+---------------------------+---------------------------+
| gcd(Int64(-100),Int64(0)) | gcd(Int64(0),Int64(-100)) |
+---------------------------+---------------------------+
| -100                      | -100                      |
+---------------------------+---------------------------+
```

### Expected behavior

In PostgreSQL
```sh
postgres=# select gcd(-100, 0), gcd(0, -100);
 gcd | gcd
-----+-----
 100 | 100
(1 row)
```

**Comment by LorrensP-2158466** [comment]
I really thought I fixed this, damn, thanks!
