### ISSUE TITLE
Register SQL planners in `SessionState::new()`

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#11216]
It might make sense to move the registering of these planners into the constructor of SessionState rather than here (so users could potentially more carefully control the planner content). But we can do that as a follow on PR

_Originally posted by @alamb in https://github.com/apache/datafusion/pull/11208#discussion_r1662469258_

**Comment by dharanad** [comment]
hello @jayzhan211 , i would like to work on this. QQ: Is this issue any straight as it sounds or there is more to it?

**Comment by jayzhan211** [comment]
> hello @jayzhan211 , i would like to work on this. QQ: Is this issue any straight as it sounds or there is more to it?

A little more than it. Ideally we need to update map capacity in provider with the number of references. But, I think you can try it.
https://github.com/apache/datafusion/blob/75b9c9bea28757ec66d7e6a88997bd6f30c367f5/datafusion/core/src/execution/session_state.rs#L590-L608

**Comment by dharanad** [comment]
take

**Comment by dharanad** [comment]
> > hello @jayzhan211 , i would like to work on this. QQ: Is this issue any straight as it sounds or there is more to it?
> 
> A little more than it. Ideally we need to update map capacity in provider with the number of references. But, I think you can try it.
> 
> https://github.com/apache/datafusion/blob/75b9c9bea28757ec66d7e6a88997bd6f30c367f5/datafusion/core/src/execution/session_state.rs#L590-L608

Do you mean something like this
```
        let mut provider = SessionContextProvider {
            state: self,
            tables: HashMap::with_capacity(references.len() + self.user_defined_sql_planners.len()),
        };
```

**Comment by alamb** [comment]
Update here is I think the current formulation is about as optimal as we can get it:
https://github.com/apache/datafusion/blob/dce77db316beb5bf5dc2326c350b2d642edbfed8/datafusion/core/src/execution/session_state.rs#L234-L242

(namely to make a Vec with a size known at compile time
