### ISSUE TITLE
Support `COUNT()` in addition to `COUNT(*)`

### ISSUE THREAD

**Issue by tshauck** [apache/datafusion#11228]
### Is your feature request related to a problem or challenge?

It'd be nice if it was possible to do `SELECT COUNT()` when running SQL. It's not super common (tho duckdb supports it), but is a nice quality of life item.

### Describe the solution you'd like

Be able to use `COUNT()` anywhere `COUNT(*)` is supported.

**Comment by findepi** [comment]
> It'd be nice if it was possible to do `SELECT COUNT()` when running SQL. It's not super common (tho duckdb supports it), but is a nice quality of life item.

i believe it's also SQL spec-compliant, to +1 from me.
