### ISSUE TITLE
Replace `println!` with `assert!` if possible in DataFusion examples

### ISSUE THREAD

**Issue by comphead** [apache/datafusion#11230]
we can use `assert!` in DataFusion examples to let the user know the expected output

_Originally posted by @comphead in https://github.com/apache/datafusion/pull/11088#discussion_r1662795223_

**Comment by alamb** [comment]
I added this as a subtask of https://github.com/apache/datafusion/issues/11230

I would like to propose we migrate some of the smaller examples over from datafusion-examples and into the user guide (to make them more discoverable)

Perhaps we can update them to use `assert` at the same time, as I found I had to do in https://github.com/apache/datafusion/pull/11217

**Comment by Nishi46** [comment]
take

**Comment by ShreyasSN** [comment]
take
