### ISSUE TITLE
Consider renaming `UserDefinedSQLPlanner` to `ExprPlanner`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11304]
### Is your feature request related to a problem or challenge?

@samuelcolvin  notes on https://github.com/apache/datafusion/issues/11207 https://github.com/apache/datafusion/issues/11207#issuecomment-2206608686 

> Given how much UserDefinedSQLPlanner is being used for existing stuff within datafusion, perhaps it should be called just SQLPlanner or CustomSQLPlanner?

Since we haven't released this API yet, the name could be changed in the next few days before https://github.com/apache/datafusion/issues/11077 without  causing too much downstream churn.

### Describe the solution you'd like

I recommend renaming it to `ExprPlanner` as it is being used to plan specific exprs which seems good https://github.com/apache/datafusion/issues/11207#issuecomment-2207397190

**Comment by andygrove** [comment]
@alamb @samuelcolvin  This seems to be the only issue blocking the release. Is anyone planning on working on this? If not, I'll pick it up.
