### ISSUE TITLE
Remove additional unnecessary qualified names in the code

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11317]
### Is your feature request related to a problem or challenge?

As @findepi  noted and improved in  https://github.com/apache/datafusion/pull/11292, there are places in the DataFusion codebase that use fully (or more fully) qualified names that necessary

For example since `Result` was already in scope via `use arrow_schema::Field` the code can be simplified like this:

```diff
-    fn state_fields(&self, args: StateFieldsArgs) -> Result<Vec<arrow_schema::Field>> {
+    fn state_fields(&self, args: StateFieldsArgs) -> Result<Vec<Field>> {
```

As @findepi  reportes in https://github.com/apache/datafusion/pull/11292#issuecomment-2211795858:

> RustRover has nice inspections and can detect unnecessary use of qualified names.
> Sadly it can't fix them automatically (yet), so it's currently manual & requires proper review. That's why I fixed only some of these.

### Describe the solution you'd like

It would be nice for someone to review other instances of these unecessary qualified names and remove them too, following the model of https://github.com/apache/datafusion/pull/11292

**Comment by Weijun-H** [comment]
take

**Comment by Weijun-H** [comment]
Consider if there is a better way to automatically detect this issue in Clippy or other crates. 🤔

**Comment by alamb** [comment]
> Consider if there is a better way to automatically detect this issue in Clippy or other crates. 🤔

I think @findepi  said there was some feature in RustRover that did it. A clippy lint would be even better

**Comment by findepi** [comment]
seems there is no Clippy check for this (https://github.com/rust-lang/rust-clippy/issues/4707), but there rustc check: `unused_qualifications`.

**Comment by Weijun-H** [comment]
Since @findepi suggested a simple and accessible solution, this issue could be a good first issue for new contributors who are unfamiliar with Datafusion.

**Comment by findepi** [comment]
@Weijun-H thanks for adding the label!

btw @dhegberg is already working on this (https://github.com/apache/datafusion/pull/13086).

**Comment by alamb** [comment]
And we are done!
