### ISSUE TITLE
Let `CASE` expression only accept boolean in `WHEN` branch

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#11313]
### Is your feature request related to a problem or challenge?

Now `CASE` expression's `WHEN` branch can accept numbers, maybe it's better to let it only accept boolean due to:
1. Avoid confusion caused by implicit conversion
2. PostgreSQL's convention is only accept `BOOLEAN` (IIRC datafusion tries to follow postgres conventions when possible)

### Table creation
```
create table t1 (v1 int);
insert into t1 values (-1),(0),(1),(null);
```
### DataFusion Example
```
> select count(case when v1 then 1 else null end) from t1;
+----------------------------------------------------+
| count(CASE WHEN t1.v1 THEN Int64(1) ELSE NULL END) |
+----------------------------------------------------+
| 2                                                  |
+----------------------------------------------------+
```
### PostgreSQL Example
```
postgres=# select count(case when v1 then 1 else null end) from t1;
ERROR:  argument of CASE/WHEN must be type boolean, not type integer
LINE 1: select count(case when v1 then 1 else null end) from t1;
```

**Comment by jayzhan211** [comment]
We not only follow Postgres but also DuckDB or others.

We have the same result as DuckDB in this case, so I think we don't need to convert it to error.

**Comment by 2010YOUY01** [comment]
> We not only follow Postgres but also DuckDB or others. We usually follow the majority, otherwise we choose either of them (usually Postgres, but not restricted to)
> 
> We have the same result as DuckDB in this case, so I think we don't need to convert it to error.

So many SQL dialects 🤣 

It's just my preference to not use number in boolean expressions: treating non-zero as true seems like a historical and C-specific convention, using this rule in SQL can cause confusion (like WHERE in SQL doesn't allow numeric expression too)

Since I'm not planning to implement it,  so close this issue, feel free to reopen it when necessary
