### ISSUE TITLE
Extract registering default features from `SessionState` and into its own function

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11320]
### Is your feature request related to a problem or challenge?

Using `SessionContext` provides a batteries included experience, as it configures and installs many functions, rewrites, data providers, etc. 

However, for those people who want to more carefully control how DataFusion works (as we do in InfluxDB and I think delta.rs does with `DeltaTable`s) it is somewhat akward to do so.  It also makes it harder to 

One of the major challenges is that `SessionState's` constructor basically installs the "pre-provided" functionality (like data sources, rewrites, udfs, etc)

https://github.com/apache/datafusion/blob/78055fe13b64cdfb4accd131e9a462770c21a934/datafusion/core/src/execution/session_state.rs#L190-L295

This pre-installation also makes it hard to split SessionState / catalog information out of the core as discussed in  https://github.com/apache/datafusion/issues/11182 

### Describe the solution you'd like

I would like to be able to construct SessionState with the minimal built in features, and have a separate function / configuration system 

That way it would still be easy to use DataFusion with a minimal `SessionState` but also easily register all the built in extensions 🤔 

## Idea 1: function in `SessionContext`

`SessionContext` like `SessionContext::register_built_ins` that would register things like listing table, information schema, etc. 

Then `SessionContext::new()` etc could call this function but there should be a way to create a `SessionState` without calling it (for minimal use)

### Additional context

This came up most recently with @rtyler  in https://github.com/apache/datafusion/pull/11180#discussion_r1667729599. I am not sure if it is quite the same thing, but I think the symptoms are at least similar

@jayzhan211 @Omega359 and @ahirner and I discussed this in the context of 
https://github.com/apache/datafusion/issues/11182 --  https://github.com/apache/datafusion/issues/11182#issuecomment-2200327993

**Comment by jayzhan211** [comment]
Should we cut it even more granularly to several of `register_*` functions or configure them like existing `create_default_catalog_and_schema`?

**Comment by Omega359** [comment]
Would we want to then deprecate the SessionState::new_with_config_rt and SessionState::new_with_config_rt_and_catalog_list as well (basically all the SessionState::new_* functions) leaving the builder as the preferred method to create a SessionState ?

**Comment by Omega359** [comment]
take
