### ISSUE TITLE
Remove the uses of `termtree` dependency

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11389]
### Is your feature request related to a problem or challenge?

Whatever we can do to make it faster/easier to test and compile datafusion is good, and this includes keeping the dependency chain small. Reducing the dependency chain is also a good way to reduce potential security attacks. 

I noticed in https://github.com/apache/datafusion/pull/11383 that we were upgrading a package called termtree that is only used in a single test. 

### Describe the solution you'd like

Remove the uses of `termtree` package 

https://github.com/search?q=repo%3Aapache%2Fdatafusion%20termtree&type=code

BTW you can run the test in question via:

```shell
cargo test --package datafusion-physical-plan --lib
```

### Describe alternatives you've considered

I think it could be replaced with a `Display` impl and a function that printed out the leaves at the appropriate level

I don't think this requires deep database knowledge, just some rust skills 

### Additional context

cc @avantgardnerio as I think you are the original author

**Comment by avantgardnerio** [comment]
I added it because it was a quick and easy way to debug & document tree-related tests. I think seeing it visually is helpful, but I have no strong opinion about how that is done. Re-implementing this functionality manually in the `Display` trait doesn't seem overly difficult.

**Comment by Kev1n8** [comment]
take
