### ISSUE TITLE
Improve error messages for parallel parquet writer "Unable to send array to writer!"

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11397]
@devinjdangelo noted on https://github.com/apache/datafusion/pull/11345 that if an error happens deep in the parallel parquet writer it often is not returned to the user and instead we get a generic message `"Unable to send array to writer!"`

              I think we need to update several map_err statements to propagate inner error messages rather than ignore them. E.g. 

https://github.com/apache/datafusion/blob/b96186fdef1ff410663ec8fce41186c018f8e09a/datafusion/core/src/datasource/file_format/parquet.rs#L880-L884

change to something like

```rust
            col_array_channels[next_channel]
                .send(c)
                .await
                .map_err(|e| internal_datafusion_err!("Unable to send array to writer due to error {e}"))
```

_Originally posted by @devinjdangelo in https://github.com/apache/datafusion/pull/11345#discussion_r1672594976_

**Comment by wiedld** [comment]
take
