### ISSUE TITLE
Document the Map function in the documentation

### ISSUE THREAD

**Issue by goldmedal** [apache/datafusion#11435]
### Is your feature request related to a problem or challenge?

We implemented `map` and `make_map` functions in #1136. We're better to have the corresponding documentation for them.

### Describe the solution you'd like

As @alamb mentioned in https://github.com/apache/datafusion/pull/11361#pullrequestreview-2169857325, we can follow the https://datafusion.apache.org/user-guide/sql/scalar_functions.html#struct-functions to do it.

**Comment by Weijun-H** [comment]
take
