### ISSUE TITLE
Support Arrays for the Map scalar functions

### ISSUE THREAD

**Issue by goldmedal** [apache/datafusion#11436]
### Is your feature request related to a problem or challenge?

As @alamb mentioned in https://github.com/apache/datafusion/pull/11361#discussion_r1672743943, we should support not only scalar lists but also arrays for the `map` and `make_map` functions. However, I encountered some challenges, which I detailed in https://github.com/apache/datafusion/pull/11361#discussion_r1674235631. I left the disabled test cases in https://github.com/apache/datafusion/blob/1dfac86a89750193491cf3e04917e37b92c64ffa/datafusion/sqllogictest/test_files/map.slt#L200-L214.

**Comment by dharanad** [comment]
take

**Comment by jayzhan211** [comment]
MakeMap is possible to be removed after #11434, so you can find out array support for `MapFunc` only

**Comment by dharanad** [comment]
Apologies for the delay, prioritizing this issue.

**Comment by dharanad** [comment]
Sharing my observation from `DuckDB`, both `Map` exprssion and `map` function are meant to do two different things.
But in Datafusion we are using `map` function to support `Map` expression. 
In case of `DuckDB` `Map` expr & `map` function would yeild different result for same input.
Shouldn't we have two different function to support these two use cases ? Or any ideas on how should we support both usecases using using single `map` function.
### Observations
```
D create table t as values
· ('a', 1, 'k1', 10, ['k1', 'k2'], [1, 2], 'POST', [[1,2,3]]),
· ('b', 2, 'k3', 30, ['k3'], [3], 'PUT', [[4]]),
‣ ('d', 4, 'k5', 50, ['k5'], [5], null, [[1,2]]);

D select map(col4, col5) from t;
┌───────────────────────┐
│    map(col4, col5)    │
│ map(varchar, integer) │
├───────────────────────┤
│ {k1=1, k2=2}          │
│ {k3=3}                │
│ {k5=5}                │
└───────────────────────┘

D select Map {col4: col5} from t;
┌────────────────────────────────────────────────────────┐
│ main.map(main.list_value(col4), main.list_value(col5)) │
│               map(varchar[], integer[])                │
├────────────────────────────────────────────────────────┤
│ {[k1, k2]=[1, 2]}                                      │
│ {[k3]=[3]}                                             │
│ {[k5]=[5]}                                             │
└────────────────────────────────────────────────────────┘
```

In the meantime i will continue my investigation.

**Comment by alamb** [comment]
> Shouldn't we have two different function to support these two use cases ? Or any ideas on how should we support both usecases using using single map functio

In general, I think DataFuion strives not to invent / determine semantics, so in my opinion we should follow other implementations rather than having our own custom behavior whenever possible. 

I think by default we should follow the postgres model

If postgres doesn't support maps / this syntax then I think we should follow the DuckDB model

**Comment by jayzhan211** [comment]
@dharanad  I think `select Map {col4: col5} from t;` is equivalent to `SELECT MAP([col4], [col5]);`, so we just need to rewrite the syntax the existing map function.

**Comment by dharanad** [comment]
> > Shouldn't we have two different function to support these two use cases ? Or any ideas on how should we support both usecases using using single map functio
> 
> In general, I think DataFuion strives not to invent / determine semantics, so in my opinion we should follow other implementations rather than having our own custom behavior whenever possible.
> 
> I think by default we should follow the postgres model
> 
> If postgres doesn't support maps / this syntax then I think we should follow the DuckDB model

I totally agree with you.

**Comment by dharanad** [comment]
> @dharanad I think `select Map {col4: col5} from t;` is equivalent to `SELECT MAP([col4], [col5]);`, so we just need to rewrite the syntax to the existing map function.

Thanks for clarifying, i will have to say that i totally misunderstood the problem here. Should have checked what Postgres/DuckDB were doing & clarified the problem.
