### ISSUE TITLE
Implement nested identifier access ( "Nested identifiers not yet supported" )

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11445]
### Is your feature request related to a problem or challenge?

This came up on discord: https://discord.com/channels/885562378132000778/885562378132000781/1261359404197089443

```sql
> create or replace view foo as select  {'field1': { 'subfield1': 'foo', subfield2: 'bar', subfield3: [10,20,30,40]}} as "the_column";
0 row(s) fetched.
Elapsed 0.001 seconds.

> select * from foo;
+-------------------------------------------------------------------------+
| the_column                                                              |
+-------------------------------------------------------------------------+
| {field1: {subfield1: foo, subfield2: bar, subfield3: [10, 20, 30, 40]}} |
+-------------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.002 seconds.

> select the_column.field1.subfield3[2] from foo;
Internal error: Nested identifiers not yet supported for column foo.the_column.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Describe the solution you'd like

The query should work and return `20`

### Describe alternatives you've considered

Single level access works fine:

```sql
> create or replace view foo as select { 'subfield1': 'foo', subfield2: 'bar', subfield3: [10,20,30,40]} as "field1" ;
0 row(s) fetched.
Elapsed 0.008 seconds.

> select * from foo;
+---------------------------------------------------------------+
| field1                                                        |
+---------------------------------------------------------------+
| {subfield1: foo, subfield2: bar, subfield3: [10, 20, 30, 40]} |
+---------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.003 seconds.

> select field1.subfield3[2] from foo;
+----------------------------------------------------+
| get_field(foo.field1, Utf8("subfield3"))[Int64(2)] |
+----------------------------------------------------+
| 20                                                 |
+----------------------------------------------------+
1 row(s) fetched.
Elapsed 0.002 seconds.
```

**Comment by kavirajk** [comment]
take

**Comment by kavirajk** [comment]
@alamb kinda stuck on this. I track down [where the error is coming from](https://github.com/apache/arrow-datafusion/blob/main/datafusion/sql/src/expr/identifier.rs#L120-L126). 

But don't know which datatype (I assume `Datatype::Struct`?) methods [needs to be modified to allow nested access here in getfield.rs](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/core/getfield.rs). Appreciate any leads/tips? thanks.

**Comment by alamb** [comment]
Sorry @kavirajk  I am not super familar with the struct access so I can't offer any code specific suggestions

What I would probably do is remove the check, then write some tests, and then work to get all the tests passing.

**Comment by kavirajk** [comment]
Thanks @alamb good idea.

**Comment by Lordworms** [comment]
based on the duckdb implementation, I think implement struct_extract function first might be a good start, I'll do that
![image](https://github.com/user-attachments/assets/3ed75b2b-d14b-4375-8134-7252dbf5a72d)
