### ISSUE TITLE
Support `to_json` function on `struct` type

### ISSUE THREAD

**Issue by dharanad** [apache/datafusion#11441]
### Is your feature request related to a problem or challenge?

This request is to support `to_json` in comet https://github.com/apache/datafusion-comet/issues/631. Rather implementing this in comet, i think we should have this function over here and let comet rely on datafusion. Since we also support `struct` now, this would be a good to have feature.

`to_json` function Converts a column containing a structs to JSON string. We can incrementally support this functions for other types.

### Describe the solution you'd like

TBD

**Comment by wjones127** [comment]
I wonder if this would belong in this repo instead: https://github.com/datafusion-contrib/datafusion-functions-json

**Comment by dharanad** [comment]
> I wonder if this would belong in this repo instead: https://github.com/datafusion-contrib/datafusion-functions-json

I think `datafusion-functions-json` is the place. Will re open this issue over there.
