### ISSUE TITLE
ExprPlanner not propagated to SqlToRel

### ISSUE THREAD

**Issue by wjones127** [apache/datafusion#11477]
### Describe the bug

When upgrading to DataFusion 40, I kept on encountering this error:

```
Internal error: Expected a simplified result, but none was found.
```

This happened when parsing a array literal. It seems in order to parse it, we need to register the proper `ExprPlanner` on the `SessionState`. We use `SessionState::default()`, which registers it for us. But then it's not being propagated to `SqlToRel`, so it fails. (Note the `planners: vec![]`)

https://github.com/apache/datafusion/blob/f204869ff55bb3e39cf23fc0a34ebd5021e6773f/datafusion/sql/src/planner.rs#L206-L213

### Expected behavior

I'm not sure I understand the design, but it seems odd we don't propagate these. At the very least, we should provide a warning in the docs.

### Additional context

Current workaround:

```
for planner in context_provider.state.expr_planners() {
    sql_to_rel = sql_to_rel.with_user_defined_planner(planner.clone());
}
```

**Comment by wjones127** [comment]
@jayzhan211 could you confirm what the intended behavior is for this?

**Comment by jayzhan211** [comment]
We assume planner should exist, at least with datafusion's builtin one, otherwise we don't know how to handle it thus throws error for the case.

**Comment by jayzhan211** [comment]
After https://github.com/apache/datafusion/pull/11403, I think you can easily get the default planners with

```rust
SessionStateBuilder::new()
            .with_default_features()
            .build()
```

**Comment by wjones127** [comment]
> We assume planner should exist, at least with datafusion's builtin one, otherwise we don't know how to handle it thus throws error for the case.

I'm not sure I understand your answer. When we call `SessionState::default()`, all the correct planners are registered. For example, it already has the `ArrayFunctionPlanner` it should need to parse array literals.

What I'm confused by is that I have to do this additional step to propagate it to `SqlToRel`:

```rust
let session_state: SessionState = ...;
let mut sql_to_rel = SqlToRel::new(...);
for planner in session_state.expr_planners() {
    sql_to_rel = sql_to_rel.with_user_defined_planner(planner.clone());
}
```

Why do I have to do that? Why doesn't `SqlToRel` copy the expression planners from the `ContextProvider` that was passed in?

**Comment by jayzhan211** [comment]
I see. You are right, we can get the planners without additional step.

**Comment by jayzhan211** [comment]
I see. Let me see if it is possible to avoid the additional copied

**Comment by alamb** [comment]
Cross referencing -- a related discussion on https://github.com/apache/datafusion/pull/11180 https://github.com/apache/datafusion/pull/11180#discussion_r1667729599
