### ISSUE TITLE
Move spill related functions to `spill.rs`

### ISSUE THREAD

**Issue by comphead** [apache/datafusion#11496]
maybe eventually the spill related untilities could go into `physical-plan/src/spill.rs` though I see this PR simply follows the existing pattern so I think it is find

_Originally posted by @alamb in https://github.com/apache/datafusion/pull/11218#discussion_r1676552575_

**Comment by findepi** [comment]
take

**Comment by comphead** [comment]
I created this issue too early as it will create conflicts in #11218 😁

**Comment by alamb** [comment]
Sorry!

**Comment by findepi** [comment]
i think you did alright (otherwise, how would you keep track of the follow-up issues without creating them).
maybe i created the PR too early. apologies @comphead

**Comment by comphead** [comment]
nw, folks, I shoulda added the PR dependency manually, nw, I already resolved it.
