### ISSUE TITLE
Consolidate optimizer readme into datafusion user guide

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11497]
### Is your feature request related to a problem or challenge?

The DataFusion optimizer has a great readme:

https://github.com/apache/datafusion/tree/main/datafusion/optimizer#readme

However, I don't think it is as discoverable as the Library guide on the docs site: https://datafusion.apache.org/library-user-guide/index.html

### Describe the solution you'd like

Consolidate the content from https://github.com/apache/datafusion/tree/main/datafusion/optimizer#readme into https://datafusion.apache.org/library-user-guide/index.html

I think we could start with simply moving the content and leaving a link in the readme and then update the content in subsquent PRs

**Comment by devesh-2002** [comment]
May I take this issue?

**Comment by alamb** [comment]
Thank you @devesh-2002  -- that would be super helpful
