### ISSUE TITLE
Implement `evaluate_bounds` for math unary functions

### ISSUE THREAD

**Issue by tshauck** [apache/datafusion#11583]
### Is your feature request related to a problem or challenge?

I noticed during https://github.com/apache/datafusion/pull/11559 that evaluate_bounds, which is used as part of determining a functions mononicity was not implemented so the trait default is used.

For many of these functions (e.g. `cos`) and more narrow set of bounds can be used.

### Describe the solution you'd like

Update the unary math scalar function macro to take an evaluate bounds function, and implement that function where appropriate.

**Comment by tshauck** [comment]
take

**Comment by alamb** [comment]
FYO @mustafasrepo and @boazberman
