### ISSUE TITLE
Typo in doc of datafusion::physical_plan::Partitioning

### ISSUE THREAD

**Issue by waruto210** [apache/datafusion#11593]
### Describe the bug

In https://docs.rs/datafusion/latest/datafusion/physical_plan/enum.Partitioning.html
![image](https://github.com/user-attachments/assets/ea26e8b4-3ed9-4df1-a80c-3af238ab209d)

According to my understanding, the left side of the diagram shows logical plan, while the right side represents the physical data flow. Therefore, the right side should have three inputs and one output, but in reality, it's the opposite.

**Comment by alamb** [comment]
Yes I agree with this @waruto210  -- thank you 

Perhaps the easiest change would be to update the example description to say "RepartitionExec with 1 input partition and 3 output partitions"

**Comment by waruto210** [comment]
> Yes I agree with this @waruto210  -- thank you 
> 
> 
> 
> Perhaps the easiest change would be to update the example description to say "RepartitionExec with 1 input partition and 3 output partitions"

Ok, I'll submit a pr.
