### ISSUE TITLE
Serialization of UDF might lose aliases

### ISSUE THREAD

**Issue by edmondop** [apache/datafusion#11595]
### Describe the bug

As a part of migrating min/max to user-defined aggregate function, the test `'cases::roundtrip_physical_plan::roundtrip_scalar_udf_extension_codec' (datafusion/proto/tests/cases/roundtrip_physical_plan.rs) fails

https://github.com/apache/datafusion/blob/ecf5323eaa38869ed2f911b02f98e17aa6db639a/datafusion/proto/tests/cases/roundtrip_physical_plan.rs#L952-L964

After investigating the failure (see https://github.com/apache/datafusion/actions/runs/10040552648/job/27746844799?pr=11013#step:4:5769) it appears that the signature, the aliases and the name are lost in serialization/deserialization
<img width="2449" alt="Screenshot 2024-07-22 at 8 37 51 AM" src="https://github.com/user-attachments/assets/6c41f2c6-0d81-4687-9ce0-3a4c16459ec5">

This doesn't appear to be a problem related to migrating min/max to user-defined functions but rather a general problem we only encounter because that's the only roundtrip serialization/deserialization tests that involve UDF

### Expected behavior

Roundtrip should work correctly and restore aliases, as well as correct names and signature

**Comment by Lordworms** [comment]
take

**Comment by edmondop** [comment]
take
