### ISSUE TITLE
Write a blog post about implementing StringView in DataFusion

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11603]
As part part of the InfluxData / @pauldix philosophy of "write cool software and tell people about it" we plan to tell people about the great work that went into making StringView work in DataFusion

As part of https://github.com/apache/datafusion/issues/10918 and the intern process at InfluxData, @XiangpengHao plans to write a blog post about the experience and what it takes to do this kind of performance optimization

I am filing this ticket to give it visibility

We plan to publish the blog on InfluxData's blog first, but then will propose cross-posting on the DataFusion blog.

If anyone is interested in reviewing or helping, please let us know

**Comment by alamb** [comment]
@XiangpengHao  -- can you possibly comment / take this issue (I can't assign it to you without you having first commented on it 😆 )

**Comment by XiangpengHao** [comment]
take

**Comment by alamb** [comment]
We are done with the draft. We expect it to be published in the next few weeks (it turns out to be a two part series)

**Comment by alamb** [comment]
In case anyone wants an overview of adding StringView to DataFusion, here is a presentation and slides
Video: https://www.youtube.com/watch?v=RVLshX6fbds
Slides: https://drive.google.com/file/d/1Qqd8V6cfS9rSQ_-JrinasQJwI79qlUEV/view?usp=drive_link

Blog is coming soon

**Comment by alamb** [comment]
Part 1: https://www.influxdata.com/blog/faster-queries-with-stringview-part-one-influxdb/

**Comment by alamb** [comment]
Part 2: https://www.influxdata.com/blog/faster-queries-with-stringview-part-one-influxdb/

cc @XiangpengHao 

I would like to also make a copy of this content on the DataFusion blog as it is entirely about DataFusion and might be easier to discover there

**Comment by alamb** [comment]
I made a PR to add a copy of these blogs to the DataFusion site: https://github.com/apache/datafusion-site/pull/25

**Comment by alamb** [comment]
Still waiting on a committer to approve https://github.com/apache/datafusion-site/pull/25 and then I will close this ticket
