### ISSUE TITLE
Allow custom planning behavior for selecting wildcard expression

### ISSUE THREAD

**Issue by goldmedal** [apache/datafusion#11639]
### Is your feature request related to a problem or challenge?

Currently, DataFusion always expands the wildcard expression to the list of columns when planning a `SELECT` statement. This causes problems for those who want to check the wildcard expression in the logical plan layer.

For example, given a table "A" with three columns: c1, c2, and c3, it is difficult to distinguish between `SELECT * FROM A` and `SELECT c1, c2, c3 FROM A` in the logical plan layer.

If we provide a way for users to customize the behavior of wildcard expression planning, it will be easier to distinguish between these two cases.

### Describe the solution you'd like

I plan to implement this feature based on `ExprPlanner`. I guess we can add a method called `plan_select_wildcard` and putting the default expression expansion there. Then, invoke this method in `SqlToRel::sql_select_to_rex`.
https://github.com/apache/datafusion/blob/main/datafusion/sql/src/select.rs#L594

### Additional context

My current project, [Wren engine](https://github.com/Canner/wren-engine), is a semantic engine based on the DataFusion Logical Plan. We have a type of column called a "calculated field" that can be selected specifically but won't be included when querying using the wildcard expression. Since it could trigger some joins for its parent table, we want to ensure that it is only used when the user specifically selects it.
This feature helps us align with the native behavior of DataFusion.

**Comment by goldmedal** [comment]
take

**Comment by alamb** [comment]
> Could we remove the expansion behavior in the builder? (I guess that's what the comment purposes.)

I think that is my understanding as well

I believe @jayzhan211  and @tshauck  have had some recent discussion about this as well, so maybe they remember more than do I

**Comment by tshauck** [comment]
We were working on the related `COUNT(*)`. At least in that case the `*` is just intercepted as the argument and replaced with `1`, so I don't think there'd be a conflict.

**Comment by tshauck** [comment]
It was part of the work to support `COUNT()` (no `*`): https://github.com/apache/datafusion/pull/11229

**Comment by jayzhan211** [comment]
@goldmedal If we move the expression expansion to analyzer as the comment said, I guess you can still tell the different from `SELECT * FROM A and SELECT c1, c2, c3 FROM A`. I think expand expression in builder is quite early, if there are 1000 columns, we need to carry those columns around in many places. It is better to delay expansion *lazily* as long as possible.

**Comment by goldmedal** [comment]
> @goldmedal If we move the expression expansion to analyzer as the comment said, I guess you can still tell the difference from `SELECT * FROM A and SELECT c1, c2, c3 FROM A` _before optimizer_. I think expand expression in builder is quite early, if there are 1000 columns, we need to carry those columns around in many places. It is better to delay expansion _lazily_ as long as possible.

I think I got it. So, ideally, we don't do any expansions in the planner or builder. We need to have an analyze rule or optimize rule to expand the expression. If we move this to analyze or optimizer, I can get the wildcard expression before optimizing, even if we don't add a customized behavior in ExprPlanner, right?

**Comment by jayzhan211** [comment]
Correct

**Comment by goldmedal** [comment]
I have drafted a version https://github.com/apache/datafusion/pull/11681 for moving wildcard expansions to the analyzer. I think it's better than #11673. I might change the purpose of this PR. WDYT @alamb, @jayzhan211 ?

By the way, I'm thinking about handling `replace` syntax. We can discuss this issue in the PR if you have some ideas.

**Comment by jayzhan211** [comment]
I think handling replace item in options is a good idea. We store the replace item in Expr::Wildcard in planning stage and convert it to expanded columns with expected replace items in analyzer.
