### ISSUE TITLE
Clippy CI failures on main after Rust 1.80 release

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11651]
### Describe the bug

Clippy started failing in main. For example

* https://github.com/apache/datafusion/actions/runs/10093623012/job/27910077621
* https://github.com/apache/datafusion/actions/runs/10093623012/job/27910075998

Given that a new rust version was just released today I suspect it is that clippy has gotten more stringent
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-180-2024-07-25

### Expected behavior

CI should be passing

### Additional context

I believe @nrc has fixed some of these already in https://github.com/apache/datafusion/pull/11467, but we got stuck there on tests that only failed once we properly passed through `hash_collisions`

**Comment by findepi** [comment]
To prevent all PR builds from failing we can maybe restore the previous Clippy version?
At least this is what I am trying in https://github.com/apache/datafusion/pull/11655.

https://github.com/apache/datafusion/pull/11467 fixes some of the problems (notably `force_hash_collisions` related)
I found some other formatting issues that new clippy complains about: https://github.com/apache/datafusion/pull/11654

**Comment by findepi** [comment]
https://github.com/apache/datafusion/pull/11655 fixed CI by downgrading Clippy
https://github.com/apache/datafusion/issues/11657 covers the errors and re-upgrading Clippy.

should we close this issue?
