### ISSUE TITLE
`join_inner_two`, `join_inner_one_two_parts_left` and `join_inner_one_two_parts_right` fail with `force_hash_collisions`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11658]
### Describe the bug

The `force_hash_collisions` feature flag is intended to ensure DataFusion works correctly even in the very unlikely event that hash values collide.

The new version of clippy in Rust 1.80 found we had not been running some tests with this flag  https://github.com/apache/datafusion/issues/11651

And it turns out when we started running the tests with the hash collision they failed

we commented them out in https://github.com/apache/datafusion/pull/11654 but we should really figure out why they failed

Maybe the test needs to be updated or maybe there is a real bug

### To Reproduce

Remove these lines from the tests mentioned above

```rust
    #[cfg(not(feature = "force_hash_collisions"))]
```

Then run 

```shell
cargo test -p datafusion-physical-plan --features=force_hash_collisions
```

### Expected behavior

Tests should pass

**Comment by Kev1n8** [comment]
take

**Comment by Kev1n8** [comment]
[Here](https://github.com/apache/datafusion/pull/11701#issuecomment-2262167044) is some info I found for anyone who wants to dig into it. I hope that helps.
