### ISSUE TITLE
Get Clippy clean for Rust 1.80 and run it on CI

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11657]
### Is your feature request related to a problem or challenge?

A new Rust version was released that causes CI to fail -- see https://github.com/apache/datafusion/issues/11651

@findepi made a PR to pin CI to use Rust 1.79 while we work out the clippy failures: https://github.com/apache/datafusion/pull/11655

We should remove the wokaround and use the latest rust once we have sorted out clippy

### Describe the solution you'd like

Remove the workaround file and use the latest rust again

**Comment by alamb** [comment]
Note  I believe @nrc has fixed some of these already in https://github.com/apache/datafusion/pull/11467, but we got stuck there on tests that only failed once we properly passed through hash_collisions

**Comment by findepi** [comment]
https://github.com/apache/datafusion/pull/11654 includes https://github.com/apache/datafusion/pull/11467 and passes clippy 1.80 locally

>  but we got stuck there on tests that only failed once we properly passed through hash_collisions

outstanding action item

**Comment by alamb** [comment]
I am filing some tickets to track the new test failures

**Comment by alamb** [comment]
I will handle this item (now that https://github.com/apache/datafusion/pull/11654 is merged)

**Comment by alamb** [comment]
https://github.com/apache/datafusion/pull/11661 is up
