### ISSUE TITLE
Support string concat `||` for `StringViewArray`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11766]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

```shell
datafusion-cli
```

Then run 
```sql
DataFusion CLI v40.0.0
> create table foo as values ('value1', arrow_cast('one', 'Utf8View')), ('value1', arrow_cast('two', 'Utf8View'));
0 row(s) fetched.
> select column2||'ff' from foo;
Internal error: Data type Utf8View not supported for binary operation 'concat_elements' on string arrays.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**Describe the solution you'd like**
I would like the query to work 

**Describe alternatives you've considered**
 We can probably get the query to work by fixing the coercion logic to coerce to `Utf8`, but that will be less efficient than implementing native StringView support for `concat` 

The coercion is here: https://github.com/apache/datafusion/blob/6e2ff2955d96cacba905d24993353c7e5fe0cf93/datafusion/expr/src/type_coercion/binary.rs#L116-L122

The physical expression implementation starts here

https://github.com/apache/datafusion/blob/6e2ff2955d96cacba905d24993353c7e5fe0cf93/datafusion/physical-expr/src/expressions/binary.rs#L661

**Additional context**

**Comment by dharanad** [comment]
i'm really interested in working on this issue. Feeling little doubtful, but let me try. I'm might seek some help, if not i will unassign myself .

**Comment by alamb** [comment]
Thanks @dharanad  --- I would recommend starting with a test in `string_view.slt` that shows the problem

Then I would recommend trying to change the coercion logic so the arguments are coerced to `Utf8` (not `Utf8view`) to get the query passing 

Then in a second PR  (or maybe even ticket) we can figure out how to implement the native opreration of concat (that is likely much tricker than coercing)

**Comment by dharanad** [comment]
take

**Comment by dharanad** [comment]
Linked issue : https://github.com/apache/datafusion/issues/11881

@alamb I was thinking the right way to solve the issue would to add support for `StringViewArray` in `arrow::compute::kernels::concat_elements` by into introducing a function named `concat_elements_utf8view`. 

Do you have any alternative approaches in mind? If so, any pointers would be greatly appreciated.

**Comment by alamb** [comment]
> @alamb I was thinking the right way to solve the issue would to add support for `StringViewArray` in `arrow::compute::kernels::concat_elements` by into introducing a function named `concat_elements_utf8view`.

Yes, I agree this would be ideal. I recommend calling it `concate_elements_bytes_view` to be consistent with

https://docs.rs/arrow/latest/arrow/compute/kernels/concat_elements/fn.concat_elements_bytes.html

I started looking into how to explain wiring this into binary.rs and it was a mess, so I just made a skeleton PR here: 
https://github.com/apache/datafusion/pull/11995

Perhaps you can use that a template ?
