### ISSUE TITLE
Align UDF names to lowercase or uppercase

### ISSUE THREAD

**Issue by edmondop** [apache/datafusion#11779]
### Describe the bug

As a part of performing [this](https://github.com/apache/datafusion/pull/11013) change, @jayzhan211 recommended to use `min` and `max` as a default name for the new UDFs rather than the lowercase. However, performing this change makes test fails because in several places we use MAX and MIN, for example:

https://github.com/apache/datafusion/blob/0332eb569a5428ac385fe892ce7b5fb40d52c8c0/datafusion/sqllogictest/test_files/tpch/q15.slt.part use MAX uppercase that would cause build failure when comparing LogicalPlan like in the following build:
https://github.com/apache/datafusion/actions/runs/10215600305/job/28265554129?pr=11013

In the rust tests as well we use `avg` but `MAX`, so we need to update those tests as well

https://github.com/apache/datafusion/blob/0332eb569a5428ac385fe892ce7b5fb40d52c8c0/datafusion/core/src/dataframe/mod.rs#L2059

### Additional context

I have not verified if MAX and MIN are the only UDF for which we use uppercase rather than lowercase.  I personally prefer to have all SQL KEYWORDS (including UDF names) uppercase for readability

**Comment by edmondop** [comment]
Agreed,I think it's better to read

SELECT MAX(stuff) rather than SELECT max(stuff) and keep the lowercase for columns and non-keyword

**Comment by jayzhan211** [comment]
> Agreed,I think it's better to read
> 
> SELECT MAX(stuff) rather than SELECT max(stuff) and keep the lowercase for columns and non-keyword

The lowercase/uppercase conversion is quite painful since you need to change many places.  Especially for dataframe test

It is worth to find out an easy way to update the dataframe test beforehand https://github.com/apache/datafusion/issues/10373
