### ISSUE TITLE
Aggregate SQL query with filter not working in datafusion CLI

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#11783]
### Describe the bug

Aggregate function with filter is supported, see this [testcase](https://github.com/apache/datafusion/blob/0332eb569a5428ac385fe892ce7b5fb40d52c8c0/datafusion/sqllogictest/test_files/aggregate.slt#L4246-L4256)
But the same query can't run in datafusion-cli
```
DataFusion CLI v40.0.0
> CREATE TABLE test_table (c1 INT, c2 INT, c3 INT);
0 row(s) fetched.
Elapsed 0.115 seconds.

> INSERT INTO test_table VALUES
  (1, 10, 50),
  (1, 20, 60),
  (2, 10, 70),
  (2, 20, 80),
  (3, 10, NULL);
+-------+
| count |
+-------+
| 5     |
+-------+
1 row(s) fetched.
Elapsed 0.064 seconds.

> SELECT c1, SUM(c2) FILTER (WHERE c2 >= 20), SUM(c2) FILTER (WHERE c2 < 1) FROM test_table GROUP BY c1;
  🤔 Invalid statement: sql parser error: Expected end of statement, found: (
```

**Comment by haohuaijin** [comment]
For an aggregate function with a filter, you should enable PostgreSQL dialect by using `set datafusion.sql_parser.dialect = 'Postgres';`

**Comment by 2010YOUY01** [comment]
> For an aggregate function with a filter, you should enable PostgreSQL dialect by using `set datafusion.sql_parser.dialect = 'Postgres';`

I see, thank you
