### ISSUE TITLE
Improve performance of boolean aggregates: implement `convert_to_state`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11818]
### Is your feature request related to a problem or challenge?

@korowa added "skip partial aggregation mode" in https://github.com/apache/datafusion/pull/11627 which helps with high cardinality aggregates by doing minimal work for the first phase of the aggregation. This mode is triggered dynamically based on how effective the first aggregation phase is working.

In order to use this new mode, the corresponding `GroupsAccumulator` needs to implement the `convert_to_state` method

https://github.com/apache/datafusion/blob/c340b6ab7a2875c6924f825782f0c5ea408aff3d/datafusion/expr/src/groups_accumulator.rs#L166-L213

### Describe the solution you'd like

Implement `covert_to_state` for 

https://github.com/apache/datafusion/blob/2eb38bd5e0aeac69dd7b032386729379a160883e/datafusion/physical-expr-common/src/aggregate/groups_accumulator/bool_op.rs#L64

Add tests in https://github.com/apache/datafusion/blob/c340b6ab7a2875c6924f825782f0c5ea408aff3d/datafusion/sqllogictest/test_files/aggregate_skip_partial.slt#L18-L19

**Comment by 2010YOUY01** [comment]
take
