### ISSUE TITLE
Remove `AggregateExpr` abstraction layer

### ISSUE THREAD

**Issue by lewiszlw** [apache/datafusion#11810]
### Is your feature request related to a problem or challenge?

Now all aggr functions have been migrated to UDAF. The `AggregateExpr` trait just has one implementation.
```
impl AggregateExpr for AggregateFunctionExpr {
    ...
}
```
Should we remove unnecessary `AggregateExpr` abstraction layer?

**Comment by jayzhan211** [comment]
It is not clear to me whether it is a good idea. Maybe hold on and review it after the refactor #11359 ?

**Comment by lewiszlw** [comment]
Sure. We could wait to see more opinions.

**Comment by alamb** [comment]
> Now all aggr functions have been migrated to UDAF. The AggregateExpr trait just has one implementation.

This seems like a compelling reason to remove `AggregateExpr` (it is unecessary and makes the code more complicated)

> It is not clear to me whether it is a good idea. Maybe hold on and review it after the refactor https://github.com/apache/datafusion/issues/11359 ?

Now that https://github.com/apache/datafusion/issues/11359 is done, @jayzhan211  do you have any additional thoughts? 


I agree with your comment on https://github.com/apache/datafusion/pull/11989/files#r1720745280 that there is room for improvement here

**Comment by jayzhan211** [comment]
I think we could try removing `trait AggregateExpr` and see whether this simplified the code.

**Comment by lewiszlw** [comment]
`trait AggregateExpr` and `AggregateFunctionExpr` live in different crates. We should solve dependency problem first...

**Comment by jayzhan211** [comment]
I think the code that has `AggregateExpr` are all in physical layer, replacing `AggregateExpr` with `AggregateFunctionExpr ` directly doesn't have dependency issue, did I miss anything?
