### ISSUE TITLE
CSV headers not recognized

### ISSUE THREAD

**Issue by jgranduel** [apache/datafusion#11848]
### Describe the bug

Giving a new try to `datafusion-cli`, I followed the first examples in documentation [Local Files/Directories](https://datafusion.apache.org/user-guide/cli/datasources.html):
```
$ echo "a,b" > data.csv
$ echo "1,2" >> data.csv
```
then
```
> datafusion-cli.exe
DataFusion CLI v40.0.0
> select * from './data.csv';
+----------+----------+
| column_1 | column_2 |
+----------+----------+
| a        | b        |
| 1        | 2        |
+----------+----------+
2 row(s) fetched.
```

I thought the mistake was due to Windows default settings (I set EOL as '\n' without success), then installed `datafusion-cli 40.0.0` on WSL with same results. Loading from a directory gave the same results:

```
> datafusion-cli.exe
DataFusion CLI v40.0.0
> select * from './data_dir/';
+----------+----------+
| column_1 | column_2 |
+----------+----------+
| a        | b        |
| 1        | 2        |
| a        | b        |
| 3        | 4        |
+----------+----------+
4 row(s) fetched.
```

### To Reproduce

see above

### Expected behavior

a and b should be headers. Maybe headers could be a defaulted option only.

**Comment by alamb** [comment]
Thank you @jgranduel 

@korowa  has a doc update here https://github.com/apache/datafusion/pull/11919 and I made a proposal to just fix the default config value here https://github.com/apache/datafusion/issues/11936 so the example works as expected
