### ISSUE TITLE
[Minor] TPC-DS query 27 sql is different from the one in DuckDB

### ISSUE THREAD

**Issue by gruuya** [apache/datafusion#11866]
### Is your feature request related to a problem or challenge?

There's a substantial mismatch between the TPC-DS Q27 in DataFusion
https://github.com/apache/datafusion/blob/117ab1b8c861f431b2d04443e2028ca16fafc57c/datafusion/core/tests/tpc-ds/27.sql#L3-L22
and DuckDB
https://github.com/duckdb/duckdb/blob/main/extension/tpcds/dsdgen/queries/27.sql

The base DF version is effectively just a CTE in DuckDB, with some additional non-trivial operations afterwards.

### Describe the solution you'd like

Not sure which one is more up-to-date with the latest [spec](https://www.tpc.org/tpc_documents_current_versions/current_specifications5.asp), nor whether this warrants any changes at all.

Potentially indicates that other tpc-ds queries need to be aligned too.

### Additional context

We use DuckDB-generated TPC-H/DS queries for integration testing.

**Comment by andygrove** [comment]
We are using the official TPC-DS queries as generated by the official tools. It looks like DuckDB are hand-tuning them for better performance.

You can find all the generated queries in the datafusion-benchmarks repo:

https://github.com/apache/datafusion-benchmarks/tree/main/tpcds/queries

**Comment by gruuya** [comment]
Ah I see, thanks! I guess we should be using those ones too.
