### ISSUE TITLE
CASE expr with NULL literals panics `'WHEN expression did not return a BooleanArray'`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#1189]
Reproducer:

```sql
> select CASE WHEN NULL THEN 'foo' ELSE 'bar' END;
thread 'main' panicked at 'WHEN expression did not return a BooleanArray', datafusion/src/physical_plan/expressions/case.rs:381:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The correct output is `'bar'`

I think the solution will likely be to teach `CaseExpr` about type coercion (as is done in `BinaryExpr` and function calls) once coercion knows about the null type (and that it can be cast to any other type). See https://github.com/apache/arrow-datafusion/issues/1184 for more details

**Comment by WinkerDu** [comment]
rough fix here #2197
