### ISSUE TITLE
CI fails with `Binary files a/datafusion/core/example.parquet and b/datafusion/core/example.parquet differ` after changing the version

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11892]
### Describe the bug

When we last updated the version in https://github.com/apache/datafusion/pull/11889 the CI doc CI job failed  with 

https://github.com/apache/datafusion/actions/runs/10303822317/job/28525946989

> Binary files a/datafusion/core/example.parquet and b/datafusion/core/example.parquet differ

### To Reproduce

Change the version numbers, following model of https://github.com/apache/datafusion/pull/11889

### Expected behavior

CI should pass

### Additional context

@andygrove  says:  https://github.com/apache/datafusion/pull/11889#issuecomment-2276269252

> Not sure about the CI failure:
> 
> ```
> Binary files a/datafusion/core/example.parquet and b/datafusion/core/example.parquet differ
> ```
> 
> Re-triggered to verify it.

The `example.parquet` file will change every time we increase the version number, because we store metadata in the parquet file witht the version of DataFusion that was used when writing. This is not ideal... for now I will regenerate this file as part of this PR.

**Comment by andygrove** [comment]
I did update the release documentation in https://github.com/apache/datafusion/pull/11889 to add a `cargo test` step, which will re-generate this file. Maybe that is good enough. Another option is to have the example explicitly set `datafusion.execution.parquet.created_by` to a constant value.

**Comment by alamb** [comment]
Here is a proposed fix: https://github.com/apache/datafusion/pull/12034
