### ISSUE TITLE
Change default value of `datafusion.catalog.has_header` to `true`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11936]
### Is your feature request related to a problem or challenge?

As @jgranduel  notes in  https://github.com/apache/datafusion/issues/11848

I think most people would expect when reading this data as a csv file, we would get two columns `a` and `b`

```csv
a,b
1,2
```

However, datafusion currently treats the CSV file as "without header" by default resulting in 

```
> datafusion-cli.exe
DataFusion CLI v40.0.0
> select * from './data_dir/';
+----------+----------+
| column_1 | column_2 |
+----------+----------+
| a        | b        |
| 1        | 2        |
+----------+----------+
4 row(s) fetched.
```

### Describe the solution you'd like

I propose removing this "rough edge" and changing the datafusion default behavior to be what I think most people would expect

```sql
+---+---+
| a | b |
+---+---+
| 1 | 2 |
+---+---+
```

### Describe alternatives you've considered

I think we should change the default vale of `datafusion.catalog.has_header` from `false` to `true`

https://github.com/apache/datafusion/blob/79fa6f9098be9a6e5b269cd3642694765b230ff1/datafusion/common/src/config.rs#L184-L186

**Comment by korowa** [comment]
I think it'll be fine because there is already CSVReadOptions with default `has_header: true` ([link](https://github.com/apache/datafusion/blob/fd237f8705b18fa089fdfb8dd5b04655ccb4d691/datafusion/core/src/datasource/file_format/options.rs#L100)), which produces some inconsistency in default handling csv.

**Comment by alamb** [comment]
I think default to "no headers" is unlikely to have been a conscious choice (I suspect it was a historical accident)
