### ISSUE TITLE
Window functions create unwanted projection

### ISSUE THREAD

**Issue by timsaucer** [apache/datafusion#11982]
### Describe the bug

When using a window function, you get an additional projection that is not expected.

### To Reproduce

```
    let schema = Schema::new(vec![
        Field::new("a", DataType::Int32, true),
    ]);

    let batch = RecordBatch::try_new(
        Arc::new(schema.clone()),
        vec![
            Arc::new(Int32Array::from(vec![1, 2, 3, 4, 5])),
        ],
    )?;

    let ctx = SessionContext::new();

    let provider = MemTable::try_new(Arc::new(schema), vec![vec![batch]])?;
    ctx.register_table("t", Arc::new(provider))?;

    let df = ctx.table("t").await?;

    let func = Expr::WindowFunction(WindowFunction::new(
        WindowFunctionDefinition::BuiltInWindowFunction(BuiltInWindowFunction::RowNumber),
        vec![],
    )).alias("row_num");

    df.clone().select(vec![col("a"), func.clone()])?.show().await?;

    df.with_column("r", func)?.show().await?;
```

### Expected behavior

When using the `select()` operation you get the desired result:

```
+---+---------+
| a | row_num |
+---+---------+
| 1 | 1       |
| 2 | 2       |
| 3 | 3       |
| 4 | 4       |
| 5 | 5       |
+---+---------+
```

But when using `with_column()` you get this additional projection:

```
+---+-----------------------------------------------------------------------+---+
| a | ROW_NUMBER() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING | r |
+---+-----------------------------------------------------------------------+---+
| 1 | 1                                                                     | 1 |
| 2 | 2                                                                     | 2 |
| 3 | 3                                                                     | 3 |
| 4 | 4                                                                     | 4 |
| 5 | 5                                                                     | 5 |
+---+-----------------------------------------------------------------------+---+
```

**Comment by devanbenz** [comment]
What's the priority of this bug? I would love to take it on but it may take a bit since I'm newer to the df codebase.

**Comment by timsaucer** [comment]
For me this is very annoying, but not blocking any of my work.

**Comment by timsaucer** [comment]
If you're looking for a good issue to start on, https://github.com/apache/datafusion/labels/good%20first%20issue

**Comment by devanbenz** [comment]
Sounds good! Appears most of the recent `good first issue`'s are currently assigned and I don't really see too many `bug`'s as good first issues. I wonder if: https://github.com/apache/datafusion/issues/5004 is still something that needs to be done. Will take a look. I'm hoping to help out with some bug fixes :)

**Comment by devanbenz** [comment]
That being said since this is a newer bug I'll take it on for now and if I have issues I may unassign. 👍

**Comment by devanbenz** [comment]
take

**Comment by timsaucer** [comment]
Thanks!

**Comment by devanbenz** [comment]
@timsaucer I have a fix out for this specific issue: https://github.com/apache/datafusion/pull/12000
To be perfectly honest I don't know if this will cause any downstream affects. All the tests are passing. I'm wondering if you could think of any edge cases that may not get caught by these changes?

**Comment by timsaucer** [comment]
Thanks! I'll try to look at this tonight
