### ISSUE TITLE
Speed up rpad implementation to use StringBuilder

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11997]
# Usecase

@Omega359  made a nice improvement to `lpad` in https://github.com/apache/datafusion/pull/11987 to make the code cleaner and faster. 

This ticket tracks the work to apply the same treatment of https://github.com/apache/datafusion/pull/11987 to `rpad` -- which @Lordworms ported in https://github.com/apache/datafusion/pull/11942

              rpad update with utf8view wasn't committed yet. I know it would work anyways but I think now that rpad update is committed it's good to uncomment.

_Originally posted by @Omega359 in https://github.com/apache/datafusion/pull/11987#discussion_r1717559901_

**Comment by Lordworms** [comment]
take
