### ISSUE TITLE
Remove unused config value `scalar_update_factor`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11998]
### Is your feature request related to a problem or challenge?

I noticed while looking at other things I noticed that `scalar_update_factor` is no longer used

https://github.com/search?q=repo%3Aapache%2Fdatafusion%20scalar_update_factor&type=code

### Describe the solution you'd like

Remove the unused config option from the code / comments

### Describe alternatives you've considered

We could leave it in -- it isn't really harming anything

**Comment by caicancai** [comment]
i want to try it

**Comment by caicancai** [comment]
take

**Comment by jc4x4** [comment]
take
