### ISSUE TITLE
Improve performance of `REPEAT` functions

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#11990]
I think you could make this perform much better by avoiding the `String` and instead building the output directly with `StringViewBuilder` 

https://docs.rs/arrow/latest/arrow/array/type.StringViewBuilder.html

here is an example of how to use them: https://github.com/apache/arrow-rs/pull/6240

I realize this just follows the same model as was here. However, if we are messing with the code it might be nice to make it faster while we are at it

_Originally posted by @alamb in https://github.com/apache/datafusion/pull/11962#discussion_r1715778889_
            

The idea would be to 
1. Create a benchmark for the REPEAT function for StringArray, LargeStringArray and StringViewArray
2. Optimize the performance of REPEAT (likely by not creating `String`s but instead creating the values directly into a StringBuilder / StringViewArray builder somehow

## Benchmarks:
Benchmarks likely would go into https://github.com/apache/datafusion/blob/main/datafusion/functions/benches  follow the model of an existing one (e.g. [ltrim.rs](https://github.com/apache/datafusion/blob/main/datafusion/functions/benches/ltrim.rs)).

**Comment by tlm365** [comment]
take

**Comment by alamb** [comment]
FWIW https://github.com/apache/datafusion/pull/11987 from @Omega359  is a good example of this type of optimization
