### ISSUE TITLE
Internal error in `approx_percentile_cont()` aggregate function (SQLancer)

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#12012]
### Describe the bug

Reproducer:
1. Run datafusion-cli under latest main branch
```sh
(base) arrow-datafusion/datafusion-cli|main🌝| >>> git pull public main
From https://github.com/apache/arrow-datafusion
 * branch                main       -> FETCH_HEAD
Already up to date.
(base) arrow-datafusion/datafusion-cli|main🌝| >>> git checkout 2a16704db

...

(base) arrow-datafusion/datafusion-cli|2a16704db🌝| >>> cargo run
```
2. Execute queries
```
DataFusion CLI v41.0.0
> create table t1(v1 double);
0 row(s) fetched.
Elapsed 0.078 seconds.

> select approx_percentile_cont(v1,v1) from t1;
Internal error: PhysicalExpr Column references column 'v1' at index 0 (zero-based) but input schema only has 0 columns: [].
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

I think this query is invalid, the second argument have to be a literal number instead of column reference, to make this query meaningful.
However an internal error should not be thrown, it always represent a potential bug in DataFusion.
So we have to further investigate if it's a actual bug or misused internal error

### Additional context

Found by SQLancer https://github.com/apache/datafusion/issues/11030

**Comment by goldmedal** [comment]
I tried to reproduce this bug but I got a different error message:
```
DataFusion CLI v41.0.0
> create table t1(v1 double);
0 row(s) fetched. 
Elapsed 0.003 seconds.

> select approx_percentile_cont(v1,v1) from t1;
Schema error: No field named t1.v1.
```

Although the error is weird 🤔, I didn't get the internal error.
BTW, I used the latest `datafusion-cli 41.0.0` installed by `Homebrew`.

**Comment by 2010YOUY01** [comment]
> I tried to reproduce this bug but I got a different error message:
> 
> ```
> DataFusion CLI v41.0.0
> > create table t1(v1 double);
> 0 row(s) fetched. 
> Elapsed 0.003 seconds.
> 
> > select approx_percentile_cont(v1,v1) from t1;
> Schema error: No field named t1.v1.
> ```
> 
> Although the error message is weird 🤔, I didn't get the internal error. BTW, I used the latest `datafusion-cli 41.0.0` installed by `Homebrew`.

I'm running datafusion-cli under latest main, looks like this internal error was introduced by a very recent change 🤔 
I have also updated the issue to specify the commit hash, I will make this clear for future bug reports
