### ISSUE TITLE
Panics in `MIN()/MAX()` aggregate functions (SQLancer)

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#12011]
### Describe the bug

See reproducer in datafusion-cli

```
DataFusion CLI v41.0.0
> select min(1,2);
thread 'main' panicked at /Users/yongting/Desktop/code/my_datafusion/arrow-datafusion/datafusion/functions-aggregate/src/min_max.rs:71:5:
assertion `left == right` failed
  left: 2
 right: 1
```

```
DataFusion CLI v41.0.0
> select max(2,1);
thread 'main' panicked at /Users/yongting/Desktop/code/my_datafusion/arrow-datafusion/datafusion/functions-aggregate/src/min_max.rs:71:5:
assertion `left == right` failed
  left: 2
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

Note those queries are invalid since `MIN/MAX` only takes one argument, but it should still return an error instead of crash

### Additional context

Found by SQLancer https://github.com/apache/datafusion/issues/11030

**Comment by jayzhan211** [comment]
Both postgres and duckdb does not support min/max more than one argument. I suggest we leave it alone too.

**Comment by tlm365** [comment]
> Both postgres and duckdb does not support min/max more than one argument. I suggest we leave it alone too.

I have the same thought, but I think it would be nice if we throw an error with a message instead of panic and crash.

**Comment by 2010YOUY01** [comment]
> Both postgres and duckdb does not support min/max more than one argument. I suggest we leave it alone too.

I have updated the issue for clarification (expecting an error instead of crash)
BTW I think this is introduced by a recent change
