### ISSUE TITLE
Cannot infer common string type for string concat operation Dictionary(Int32, Utf8) || Dictionary(Int32, Utf8)

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12101]
### Describe the bug

When I try to concat two dictionary encoded columns it doesn't work

### To Reproduce

Concat constants

```sql
> select arrow_cast('foo', 'Dictionary(Int32, Utf8)') || arrow_cast('bar', 'Dictionary(Int32, Utf8)');
Error during planning: Cannot infer common string type for string concat operation Dictionary(Int32, Utf8) || Dictionary(Int32, Utf8)
```

Concat columns
```sql
> create table t as values (arrow_cast('foo', 'Dictionary(Int32, Utf8)'), arrow_cast('bar', 'Dictionary(Int32, Utf8)'));
0 row(s) fetched.
Elapsed 0.010 seconds.

> select column1 || column2 from t;
Error during planning: Cannot infer common string type for string concat operation Dictionary(Int32, Utf8) || Dictionary(Int32, Utf8)
```

### Expected behavior

Both queries should result in the single string `foobar`

### Additional context

Found this working on https://github.com/apache/datafusion/pull/12063 with @dharanad 

I believe the fix will be to extend `string_concat_coercion` (also changed in https://github.com/apache/datafusion/pull/12063) to also handle dictionaries.

We can likely follow the model of dictionary comparison coercion: https://github.com/apache/datafusion/blob/121f330a6ccca008da4bf6ffc4efa4ffbf961fd7/datafusion/expr-common/src/type_coercion/binary.rs#L886

**Comment by alamb** [comment]
I think this is a good first issue as there is a clear and small reproducer and the place in the code is known

It should also include some new sqllogictests

Here are the instructions: https://github.com/apache/datafusion/tree/main/datafusion/sqllogictest

Ideally you should be able to extend one of the existing test files in https://github.com/apache/datafusion/tree/main/datafusion/sqllogictest/test_files 

(you could uncomment the test in `string_view.slt` that was added in https://github.com/apache/datafusion/pull/12063)

**Comment by thinh2** [comment]
take
