### ISSUE TITLE
Support protobuf serialization  for `ScalarValue::Utf8View` and `ScalarValue::BinaryView`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12117]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/11752

We are trying to enable DataFusion to use StringViewArray by default. If we do that it means `ScalarValue::Utf8View` and `ScalarValue::BinaryView` will be more likely to be used in plans

### Describe the solution you'd like

Thus we need to ensure `ScalarValue::Utf8View` and `ScalarValue::BinaryView`  can be serialized using datafusion-proto

### Describe alternatives you've considered

I recommend adding coverage for `ScalarValue::Utf8View` and `ScalarValue::BinaryView to the tests here

https://github.com/apache/datafusion/blob/cb1e3f0e5cfd04195ae0c933b74f3eb3fcbe1b45/datafusion/proto/tests/cases/roundtrip_logical_plan.rs#L1233-L1234

And then update the code to get the tests to pass

**Comment by Lordworms** [comment]
take
