### ISSUE TITLE
Add the possibility to work with plan clones directly in `inline_table_scan`

### ISSUE THREAD

**Issue by askalt** [apache/datafusion#12120]
### Is your feature request related to a problem or challenge?

I use the implementation of several TableProviders that allow for concurrent modification of the logical plan they store. A bit of context: this is necessary for implementing mutable views. Several views depend on view A and have TableProvider(A) in their logical plan. Then, when view A is modified, the logical plan for it is updated via some synchronization primitive, so all dependent views see the updated plan.

I would like the plans for the views to be inlined during the optimization phase in my implementation. However, the current TableProvider API forces me to return a shared reference to the internal logical plan for inlining, even though a copy would suffice. 

I propose adding a `get_logical_plan_cloned(...)` method to the TableProvider trait, which would be used by passes that don't require a shared reference to the internal logical plan.

**Comment by askalt** [comment]
There is the possible implementation
https://github.com/apache/datafusion/pull/12113

**Comment by jayzhan211** [comment]
Couldn't you get the cloned by `get_logical_plan` with `cloned()` afterward? I don't get it why we need another API for `cloned()`.

**Comment by askalt** [comment]
I have approximately the following struct:

```rust
struct MyProvider {
     plan: std::sync::Mutex<LogicalPlan>
}

impl TableProvider for MyProvider {
   ...
   fn get_logical_plan(&self) -> Option<&LogicalPlan> {
       //// ???
   }
}
```

(I use it to implement CREATE OR REPLACE VIEW). 
But I can't implement get_logical_plan because MyProvider can't give the shared reference to the inner plan.
