### ISSUE TITLE
Panic in `substring()` scalar function (SQLancer)

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#12129]
### Describe the bug

It's expected to return an error instead of crash for bad input

See reproducer in datafusion-cli
(Run under latest main, compiled using `cargo run`, commit 00b3f3be5)
```
DataFusion CLI v41.0.0
> select substring('foo', 9223372036854775807 + 1, 1);
thread 'main' panicked at /Users/yongting/Desktop/code/my_datafusion/arrow-datafusion/datafusion/functions/src/unicode/substr.rs:154:47:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Additional context

Found by SQLancer https://github.com/apache/datafusion/issues/11030

**Comment by findepi** [comment]
There are two bugs actually.

1. `9223372036854775807 + 1` overflows https://github.com/apache/datafusion/issues/12140
2. `select substring('foo', -9223372036854775808, 1);` panics (this issue)
