### ISSUE TITLE
Support `map_keys` function for Map type

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#12147]
### Is your feature request related to a problem or challenge?

Description | Return a list of all keys in the map.
-- | --
Example | map_keys(map([100, 5], [42,43]))
Result | [100, 5]

### Additional context

https://docs.databricks.com/en/sql/language-manual/functions/map_keys.html#map_keys-function
https://duckdb.org/docs/sql/functions/map.html#map_keysmap

**Comment by dharanad** [comment]
take
