### ISSUE TITLE
Support `map_values` for MAP type

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#12148]
### Is your feature request related to a problem or challenge?

Description | Return a list of all values in the map.
-- | --
Example | map_values(map([100, 5], [42, 43]))
Result | [42, 43]

### Additional context

https://duckdb.org/docs/sql/functions/map.html#map_valuesmap
https://docs.databricks.com/en/sql/language-manual/functions/map_values.html

**Comment by dharanad** [comment]
take

**Comment by dharanad** [comment]
@Weijun-H  This can be closed

**Comment by Weijun-H** [comment]
complete via #12194
