### ISSUE TITLE
not support similar to expr run in physical expr?

### ISSUE THREAD

**Issue by zhuliquan** [apache/datafusion#12155]
### Describe the bug

There is `SimilarTo` expr in logical expr
https://github.com/apache/datafusion/blob/23ccca9cd9bdf1791985f2b4abb6d5d8a4fc5ece/datafusion/expr/src/expr.rs#L241
However, there is not arm for SimilarTo expr in func `create_physical_expr` (in datafusion/physical-expr/src/planner.rs:L106)
If I write sql include `SimilarTo` expr will got a panic which throw from below code
https://github.com/apache/datafusion/blob/23ccca9cd9bdf1791985f2b4abb6d5d8a4fc5ece/datafusion/physical-expr/src/planner.rs#L345-L347

For example:
```text
> select * from t1 where c1 similar to 'x*';
This feature is not implemented: Physical plan does not support logical expression SimilarTo(Like { negated: false, expr: Column(Column { relation: Some(Bare { table: "t1" }), name: "c1" }), pattern: Literal(Utf8("x*")), escape_char: None, case_insensitive: false })
```

### Additional context

Whether to consider removing the `SimilarTo` expression from the logical expression or add arm for it to convert to a special physical expression in func `create_physical_expr`

**Comment by theirix** [comment]
take
