### ISSUE TITLE
Support record delimiter ("terminator" in Arrow terms) for CSV reading

### ISSUE THREAD

**Issue by Blizzara** [apache/datafusion#12215]
### Is your feature request related to a problem or challenge?

Current CSV reading / writing already supports a bunch of options, like field delimiter and quote chars. However, record delimiter (usually something like "\n" or "\r\n") is not supported in DF. It (as "terminator") [is supported in arrow-csv](https://docs.rs/arrow-csv/latest/arrow_csv/reader/struct.ReaderBuilder.html#method.with_terminator) though, should be easy plumbing to add to DF as well.

**Comment by goldmedal** [comment]
take
