### ISSUE TITLE
Add Scalar and Aggregate Distance UDFs

### ISSUE THREAD

**Issue by austin362667** [apache/datafusion#12210]
### Is your feature request related to a problem or challenge?

1. Since there are aggregate functions like `corr` and `covar`, it makes sense to me that we should add aggregate `distance`.
2. Beyond the aggregate function, it might also be valuable to add scalar UDFs like `list_distance`/`array_distance`, similar to DuckDB, along with other methods of distance measurement (e.g., like `cosine` etc). Please check https://github.com/apache/datafusion/issues/8782

This function is particularly useful for scenarios involving spatial analysis, clustering, or similarity computations, where distance metrics are crucial. 

### Describe the solution you'd like

XREF: DuckDB [list functions](https://duckdb.org/docs/sql/functions/list.html#list_distancelist1-list2), [array functions](https://duckdb.org/docs/sql/functions/array#array_distancearray1-array2)
> side note: `list` and `array` are different by their own definition.

**Comment by Weijun-H** [comment]
related #8782

**Comment by austin362667** [comment]
Thanks for bringing up the related issues.  I updated the second part of this issue.

**Comment by austin362667** [comment]
Closing because aggregate `distance` might not be as helpful as `array_distance`,
