### ISSUE TITLE
Round Robin Polling Between Multiple Winners of Loser Tree in SPM

### ISSUE THREAD

**Issue by berkaysynnada** [apache/datafusion#12231]
### Is your feature request related to a problem or challenge?

Assume a scenario where SPM (SortPreservingMergeExec) polls from 3 partitions, each of them gives the same value for the order expression for a very long time. Currently, we poll from the same partition until a new value comes from the other partitions. Continuously polling the same partition gets all upstream operator buffers and channels grow. However, we can execute a round-robin fashioned polling mechanism for the tied partitions. 

### Describe the solution you'd like

Loser tree can re-order the tied values of partitions.

### Additional context

This is the PR resolving a similar problem in the initialization phase: https://github.com/apache/datafusion/pull/12230

**Comment by athultr1997** [comment]
> Continuously polling the same partition gets all upstream operator buffers and channels grow

@berkaysynnada Any idea why this happens ?

**Comment by berkaysynnada** [comment]
> @berkaysynnada Any idea why this happens ?

Because of eagerly polling mechanisms like RepartitionExec channels
