### ISSUE TITLE
Support `entropy` in Aggregation function

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#12247]
### Is your feature request related to a problem or challenge?

Calculates [Shannon entropy](https://en.wikipedia.org/wiki/Entropy_(information_theory)) of a column of values.

### Describe the solution you'd like

```
D CREATE TABLE entropy (vals UInt32,strings String);
D INSERT INTO entropy VALUES (1, 'A'), (1, 'A'), (1,'A'), (1,'A'), (2,'B'), (2,'B'), (2,'C'), (2,'D');
D
D SELECT entropy(vals), entropy(strings) FROM entropy;
┌───────────────┬──────────────────┐
│ entropy(vals) │ entropy(strings) │
│    double     │      double      │
├───────────────┼──────────────────┤
│           1.0 │             1.75 │
└───────────────┴──────────────────┘

```

### Additional context

https://duckdb.org/docs/sql/functions/aggregates#entropyx
https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/entropy

**Comment by dharanad** [comment]
Haven't worked on a problem like this before. I would like to give this a try.

**Comment by thinh2** [comment]
take

**Comment by alamb** [comment]
Given https://github.com/apache/datafusion/issues/12357 we may want to move this function to some other repo rather than the core

**Comment by thinh2** [comment]
thank for notify @alamb

**Comment by alamb** [comment]
Suggestion: https://github.com/apache/datafusion/issues/12254#issuecomment-2353615046

**Comment by alamb** [comment]
We are going to implement these in a different repository so closing this ticket to avoid: https://github.com/apache/datafusion/issues/12254#issuecomment-2374446425
