### ISSUE TITLE
Support `mode` in Aggregation function

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#12248]
### Is your feature request related to a problem or challenge?

The most frequent value.

### Describe the solution you'd like

```sql
D SELECT mode(col) FROM VALUES ([1, 2]), ([1, 2]), ([2, 3]) AS tab(col);
┌───────────┐
│ mode(col) │
│  varchar  │
├───────────┤
│ [1, 2]    │
└───────────┘

-- The function returns either 1 or 2, but not 3
> SELECT mode(col) FROM VALUES (1), (1), (2), (2), (3) AS tab(col);
 1

> SELECT mode(col) FROM VALUES (NULL), (NULL) AS tab(col);
 NULL
```

### Additional context

https://duckdb.org/docs/sql/functions/aggregates#modex
https://docs.databricks.com/en/sql/language-manual/functions/mode.html

**Comment by dmitrybugakov** [comment]
take

**Comment by dmitrybugakov** [comment]
ready for primitive/float, working on bytes

**Comment by alamb** [comment]
Given https://github.com/apache/datafusion/issues/12357 we may want to move this function to some other repo rather than the core

**Comment by alamb** [comment]
Suggestion: https://github.com/apache/datafusion/issues/12254#issuecomment-2353615046

**Comment by dmitrybugakov** [comment]
Implemented: [mode.rs](https://github.com/datafusion-contrib/datafusion-functions-extra/blob/f89f200971bc054bb32d2d1f4a9923b622ff8a24/src/mode.rs#L48)

**Comment by alamb** [comment]
We are going to implement these in a different repository so closing this ticket to avoid: https://github.com/apache/datafusion/issues/12254#issuecomment-2374446425
