### ISSUE TITLE
Support `max_by` in Aggregation function

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#12252]
### Is your feature request related to a problem or challenge?

[max_by(arg, val)](https://duckdb.org/docs/sql/functions/aggregates#max_byarg-val)

Description | Finds the row with the maximum val. Calculates the arg expression at that row. This function is affected by ordering.
-- | --
Example | max_by(A, B)
Alias(es) | argMax(arg, val), arg_max(arg, val)

### Describe the solution you'd like

``` sql
D SELECT max_by(x, y) FROM VALUES ('a', 10), ('b', 50), ('c', 20) AS tab(x, y);
┌──────────────┐
│ max_by(x, y) │
│   varchar    │
├──────────────┤
│ b            │
└──────────────┘
```

### Additional context

https://duckdb.org/docs/sql/functions/aggregates#max_byarg-val
https://docs.databricks.com/en/sql/language-manual/functions/max_by.html

**Comment by Lordworms** [comment]
take

**Comment by korowa** [comment]
This probably could be an aliases (with some additional transformations) for first/last aggregation functions -- otherwise there it'll end with two implementations of basically the same function (not something bad, but still redundant).

Relevant discussion -- https://github.com/apache/datafusion/issues/12075

**Comment by alamb** [comment]
Given https://github.com/apache/datafusion/issues/12357 we may want to move this function to some other repo rather than the core

**Comment by alamb** [comment]
Suggestion: https://github.com/apache/datafusion/issues/12254#issuecomment-2353615046

**Comment by alamb** [comment]
We are going to implement these in a different repository so closing this ticket to avoid confusion: https://github.com/apache/datafusion/issues/12254#issuecomment-2374446425

**Comment by findepi** [comment]
I'd love to see `min_by` & `max_by` within DataFusion repository.
