### ISSUE TITLE
Support `kurtosis_pop` in Aggregation function 

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#12251]
### Is your feature request related to a problem or challenge?

The excess kurtosis (Fisher’s definition) without bias correction.

### Describe the solution you'd like

```
D SELECT kurtosis_pop(col) FROM VALUES (1), (10), (100), (10), (1) as tab(col);
┌─────────────────────┐
│  kurtosis_pop(col)  │
│       double        │
├─────────────────────┤
│ 0.19432323191699075 │
└─────────────────────┘
```

### Additional context

https://duckdb.org/docs/sql/functions/aggregates#kurtosis_popx
https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/kurtpop

**Comment by goldmedal** [comment]
take
