### ISSUE TITLE
Support `kurtosis(x)` in Aggregation function

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#12250]
### Is your feature request related to a problem or challenge?

The excess kurtosis (Fisher's definition) with bias correction according to the sample size.

### Describe the solution you'd like

```
D SELECT kurtosis(col) FROM VALUES (1), (10), (100), (10), (1) as tab(col);
┌───────────────────┐
│   kurtosis(col)   │
│      double       │
├───────────────────┤
│ 4.777292927667962 │
└───────────────────┘
```

### Additional context

https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/kurtsamp
https://duckdb.org/docs/sql/functions/aggregates#kurtosisx

**Comment by jatin510** [comment]
take

**Comment by alamb** [comment]
Given https://github.com/apache/datafusion/issues/12357 we may want to move this function to some other repo rather than the core

**Comment by alamb** [comment]
Suggestion: https://github.com/apache/datafusion/issues/12254#issuecomment-2353615046

**Comment by alamb** [comment]
We are going to implement these in a different repository so closing this ticket to avoid confusion: https://github.com/apache/datafusion/issues/12254#issuecomment-2374446425
