### ISSUE TITLE
Converting binary data to utf8 string

### ISSUE THREAD

**Issue by nathanielc** [apache/datafusion#12326]
### Is your feature request related to a problem or challenge?

I often work with a column with a binary type however its known that the binary data is a valid utf8 string. I'd like a mechanism to easily work with such data so that I can use other string scalar functions on the data.

### Describe the solution you'd like

Add a scalar function to interpret a binary column as a utf8 string. This allows for explicit conversion between the data types.  The function could be named `str_from_utf8` or similar.

How should non valid utf8 be handled. I see two options: 

* Report an error thus causing the entire query to fail.
* Return null for that row.

I can see both being useful, does this mean we want two functions or a single function with a flag for its error behavior. Or is there a convention to follow for failable scalar functions?

### Describe alternatives you've considered

We could also add an encoding format to the `encode` and `decode` functions as they already have the function signature of binary <-> utf8. However the existing formats are about encoding arbitrary bytes not about interpreting bytes as another format.

### Additional context

I'd be happy to contribute this scalar function if we decide its a good solution to the problem.

**Comment by alamb** [comment]
> Add a scalar function to interpret a binary column as a utf8 string. This allows for explicit conversion between the data types. The function could be named str_from_utf8 or similar.

I think you can convert binary to utf8 using a cast like `col::varchar`:

```sql
> create table foo as values (X'123');
0 row(s) fetched.
Elapsed 0.011 seconds.

> select * from foo;
+---------+
| column1 |
+---------+
| 0123    |
+---------+
1 row(s) fetched.
Elapsed 0.004 seconds.

> select arrow_typeof(column1) from foo;
+---------------------------+
| arrow_typeof(foo.column1) |
+---------------------------+
| Binary                    |
+---------------------------+
1 row(s) fetched.
Elapsed 0.003 seconds.

> select column1::varchar from foo;
+-------------+
| foo.column1 |
+-------------+
| #          |
+-------------+
1 row(s) fetched.
Elapsed 0.002 seconds.
```

However, I don't think this mechanism allows you to control the casting behavior (error or null), though the underlying arrow cast kernels do:

https://docs.rs/arrow/latest/arrow/compute/fn.cast_with_options.html

Specifically [CastOptions::safe](https://docs.rs/arrow/latest/arrow/compute/struct.CastOptions.html)

**Comment by nathanielc** [comment]
@alamb Thanks I was expecting it to be builtin but didn't find it. Thanks for the docs. For now I am fine with the safe mode of returning nulls.
