### ISSUE TITLE
Optimize `strpos()` string function with ASCII fast path

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#12366]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/12306

https://github.com/apache/datafusion/issues/12306 has introduced the rationale for ASCII fast path in detail

This optimization has already been implemented on `char_length()` string function and got some performance improvement.
(In PR https://github.com/apache/datafusion/pull/12356)

### Describe the solution you'd like

Implement ASCII fast path for `strpos()` function

**Comment by goldmedal** [comment]
take
