### ISSUE TITLE
Implement grouping aggregate function

### ISSUE THREAD

**Issue by timsaucer** [apache/datafusion#12377]
### Is your feature request related to a problem or challenge?

This function has a placeholder udaf but is not yet implemented.

### Describe the solution you'd like

Implement per spec.

### Additional context

Placeholder udaf is located in `datafusion/functions-aggregate/src/grouping.rs`

**Comment by eejbyfeldt** [comment]
Is this a duplicate of https://github.com/apache/datafusion/issues/5647

**Comment by bgjackma** [comment]
I can take this on

**Comment by bgjackma** [comment]
take

**Comment by timsaucer** [comment]
Closing in favor of #5647 . @bgjackma can you coordinate on that one? Thank you @eejbyfeldt for catching this.
