### ISSUE TITLE
Improve performance of *TRIM functions for StringViewArray

### ISSUE THREAD

**Issue by Kev1n8** [apache/datafusion#12387]
### Is your feature request related to a problem or challenge?

StringView provides us a way to directly modify views of an array instead of generating a new StringArray when it comes to string operations like `substr`, which was done in #12044. I think we can play a similar trick in `trim`.

### Describe the solution you'd like

I've looked into the implementation of [`general_trim`](https://github.com/apache/datafusion/blob/f5c47fa274d53c1d524a1fb788d9a063bf5240ef/datafusion/functions/src/string/common.rs#L51), it uses the `str::trim_xxx_matches` methods the obtain the "substring". Furthermore, inside the `str::trim_xxx_matches` method, it first computes the `[start, end)` boundary and slices the `str`. The index here is useful for modifying views. Unfortunately, currently the feature `Pattern` it uses is `unstable`.

### Describe alternatives you've considered

I'm not very sure what alternatives we have. Perhaps either implement our own `trim` or wait until `Pattern` is stable in Rust.

**Comment by Rachelint** [comment]
Seems we can get the index through this way:
- Convert the originanl `str1`  to `ptr1(*const [u8])` first.
- Then we use `trim_xxx_matches` first to get the `str2`.
- Convert the `str2` to `ptr2(*cosnt [u8])`, and we get the index through `ptr1 - ptr2`?

Maybe I can try it.

**Comment by Kev1n8** [comment]
Nice great! @Rachelint

**Comment by Rachelint** [comment]
take

**Comment by Rachelint** [comment]
Finally, after reminding from @alamb ,  I found we can get the index in safe way, detail can see:
https://github.com/Rachelint/arrow-datafusion/blob/f8174626e47d147e90c6715f5052ccfa269f0493/datafusion/functions/src/string/common.rs#L80
