### ISSUE TITLE
`FilterNullJoinKeys` wrong optimization with `null_equals_null`

### ISSUE THREAD

**Issue by Dandandan** [apache/datafusion#12403]
### Describe the bug

https://github.com/apache/datafusion/pull/12348 had a small regression: if join has `null_equals_null` true, it is incorrect to push down nulls

**Comment by alamb** [comment]
I think this was fixed in https://github.com/apache/datafusion/pull/12404

**Comment by Dandandan** [comment]
Yes, thanks
