### ISSUE TITLE
`Utf8View` column produced incorrect result in a natural join query (SQLancer-NoREC)

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#12468]
### Describe the bug

See the reproducer in datafusion-cli (compiled from the latest main, commit 468a5a805)

`table1` and `table1_stringview` are two tables with logically equivalent data, but with different physical in-memory representations for string column, so given a random query, if we swap tables (`table1` <-> `table1_stringview`), the mutated query should generate the same query result, but the inconsistency has been found:
```
ataFusion CLI v42.0.0
> create table table1(v1 string);
insert into table1 values('foo'), (NULL);
create table table1_stringview as select arrow_cast(v1, 'Utf8View') as v1 from table1;
0 row(s) fetched.
Elapsed 0.068 seconds.

+-------+
| count |
+-------+
| 2     |
+-------+
1 row(s) fetched.
Elapsed 0.044 seconds.

0 row(s) fetched.
Elapsed 0.014 seconds.

> select * from table1 as t1 natural join table1 as t2;
+-----+
| v1  |
+-----+
| foo |
+-----+
1 row(s) fetched.
Elapsed 0.035 seconds.

> select * from table1 as t1 natural join table1_stringview as t2;
+-----+
| v1  |
+-----+
| foo |
|     |
| foo |
|     |
+-----+
4 row(s) fetched.
Elapsed 0.006 seconds.
```

### Additional context

Found by SQLancer https://github.com/apache/datafusion/issues/11030

**Comment by dmitrybugakov** [comment]
take

**Comment by dmitrybugakov** [comment]
Problem still exists. Resuming work on this.

**Comment by dmitrybugakov** [comment]
The query analyzer coerces types as expected.

```
Projection: t1.v1
  Inner Join: Using CAST(t1.v1 AS Utf8View) = t2.v1
    SubqueryAlias: t1
      TableScan: table1 projection=[v1]
    SubqueryAlias: t2
      TableScan: table1_stringview projection=[v1]
```

However, the `EliminateCrossJoin` optimizer rule converts this inner join into a cross join for some reason, which seems to be incorrect.

https://github.com/apache/datafusion/blob/818ce3f01efe1213a9a1eda5dff1542bb9d457f7/datafusion/optimizer/src/eliminate_cross_join.rs#L78
