### ISSUE TITLE
Make required_guarantees output deterministic in displayable plans

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#12473]
### Is your feature request related to a problem or challenge?

I am writing tests that compare a query plan to an expected query plan stored in a text file. I am using `displayable` to create the text representations of these plans. The results are not deterministic.

Here are two variations that I see

```
required_guarantees=[l_shipmode in (SHIP, FOB)]
required_guarantees=[l_shipmode in (FOB, SHIP)]
```

### Describe the solution you'd like

I would like the output to be determinstic, so would be good if we could sort this collection before output

**Comment by austin362667** [comment]
I can repro the issue. Will open a PR.
