### ISSUE TITLE
Add expected answers to `DataFrame` method examples

### ISSUE THREAD

**Issue by comphead** [apache/datafusion#12527]
I feel it would benefit understanding for Dataframe methods if we also include the expected answer of calling the method in `datafusion/core/src/dataframe/mod.rs`

Currently we have a usage example and it would be great adding the expected answer

_Originally posted by @comphead in https://github.com/apache/datafusion/pull/12520#discussion_r1765376444_

**Comment by Eason0729** [comment]
Hi, I haven't contribute here before and would like to take this issue.

**Comment by Eason0729** [comment]
I have added expected result in my fork.

Could I also change doctest data to make methods' usage more apparent?
