### ISSUE TITLE
Support adding a single new table factory to `SessionStateBuilder`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12552]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/12550

While working on https://github.com/datafusion-contrib/datafusion-dft I want to register various types of extensions while configuring the SessionContext, ideally adding each extension to the [`SessionStateBuilder`](https://docs.rs/datafusion/latest/datafusion/execution/session_state/struct.SessionStateBuilder.html) each time. 

However, I found that there were a few APIs missing on SessionStateBuilder so I had to implement my own workaround builder here: https://github.com/datafusion-contrib/datafusion-dft/blob/8247555f9464058c1ac3370196739ac2b19343ee/src/extensions/builder.rs#L84-L98

[`SessionStateBuilder`](https://docs.rs/datafusion/latest/datafusion/execution/session_state/struct.SessionStateBuilder.html) has [`SessionStateBuilder::with_table_factories`](https://docs.rs/datafusion/latest/datafusion/execution/session_state/struct.SessionStateBuilder.html#method.with_table_factories) method to set *all* the table factories, but no way to just append a new table factory

### Describe the solution you'd like

I would like a way to append just a single new `TableFactory` to the list of factories being constructed

Also it should have 
1. Documentation
2. Tests (ideally a doc test with an example of how to use to use it)

### Describe alternatives you've considered

I recommend adding a new function `SessionStateBuilder::with_table_factory` that works like this:

```rust
let state = SessionStateBuilder::new() 
  .with_table_factory("DELTA", factory1)
  .wth_table_facotry("ICEBERG", facotry2)
  // resulting state has both factory1 and factory2
  .build()
```

**Comment by alamb** [comment]
I think this is a good first issue as it is clearly described and straightforward to implement. It would be a good introduction to DataFusion I think

**Comment by Weijun-H** [comment]
\take

**Comment by alamb** [comment]
> \take

BTW since you are now a committer, I think you can also just assign github issues directly to yourself :)
