### ISSUE TITLE
Make it clearer that `RuntimeEnv::new()` is fallable

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12554]
### Is your feature request related to a problem or challenge?

While working on https://github.com/datafusion-contrib/datafusion-dft it was not clear that [`RuntimeEnv::new()`](https://docs.rs/datafusion/latest/datafusion/execution/runtime_env/struct.RuntimeEnv.html#method.new) actually returns a `Result` as the typical rust convention is a function `new()` is infallable and a function like `try_new()` is fallable. While this isn't a big deal it was a small usability papercut

### Describe the solution you'd like

I would like `RuntimeEnv` to follow standard rust conventions to make it easier to use

### Describe alternatives you've considered

I suggest:
1. Deprecating [`RuntimeEnv::new()`](https://docs.rs/datafusion/latest/datafusion/execution/runtime_env/struct.RuntimeEnv.html#method.new)
2. Add a new function `RuntimeEnv::try_new()` that does the same thing
3. Update all the datafusion code to use `try_new` instead

**Comment by alamb** [comment]
I think this is a good first issue as it is clearly described and straightforward to implement. It would be a good introduction to DataFusion I think

**Comment by OussamaSaoudi** [comment]
I'd like to take this :)

**Comment by OussamaSaoudi** [comment]
take
