### ISSUE TITLE
Potential regression in Schema / nullability calculations after upgrade to 42.0.0

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12560]
### Describe the bug

@phillipleblanc  and @itsjunetime  have both hit upgrades related to nullability and other metadata in schemas after the DataFusion 42 upgrade. 

In addition, @ion-elgreco has it something similar while updating in delta.rs (see https://github.com/delta-io/delta-rs/pull/2886)

I am filing this ticket to make this more visibility

### To Reproduce

Not sure (maybe someone could create a self contained reproducer of the problem)

### Additional context

This might have been introduced here: https://github.com/apache/datafusion/pull/11989

There is a discussion happening here https://github.com/apache/datafusion/pull/11989#issuecomment-2360601240

**Comment by itsjunetime** [comment]
I'm running into this behavior after #11989, specifically seeing schema mismatches where the only thing that is different is that a field's metadata disappears at some point (so the schemas are the same except for a field's metadata). E.g.:

```rust
&physical_input_schema = Schema {
    fields: [
        Field {
            name: "alias1",
            data_type: Utf8,
            nullable: true,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {},
        },
    ],
    metadata: {},
}
&physical_input_schema_from_logical = Schema {
    fields: [
        Field {
            name: "alias1",
            data_type: Utf8,
            nullable: true,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {
                "some_key": "some_value"
            },
        },
    ],
    metadata: {},
}
```

I've yet to figure out exactly where the metadata is being dropped and I haven't figured out a reproducer either. I suggested comparing only the fields' non-metadata fields [here](https://github.com/apache/datafusion/pull/11989#issuecomment-2361812330), but @jayzhan211 pointed out that that's more of a workaround than an actual fix, as it's still a problem if the metadata is disappearing.

The issue that I'm running into, though, seems to be somewhat different than the issue that others (like @phillipleblanc) are running into, where some fields completely disappear from the schema (see [here](https://github.com/apache/datafusion/pull/11989#issuecomment-2360822666)). I don't think these are the same issue, exactly (since they manifest differently), but they may have the same root cause/solution, so I think it's fair to keep them all under this issue unless needed otherwise.

I'll work on getting a fix or reproducer today

**Comment by hveiga** [comment]
Just to add to the visibility: we are also observing the same behavior after updating to `42.0.0`. This is the error message we are getting, to help with debugging:

```
Caused by:
    0: Arrow error: Invalid argument error: Column 'column1' is declared as non-nullable but contains null values
    1: Invalid argument error: Column 'column1' is declared as non-nullable but contains null values
```

We are getting this error when reading some parquet files using Datafusion. I have verified with other tools (parquet cli, DuckDB) `column1` does not contain any null values and metadata of the files is correct.

**Comment by jayzhan211** [comment]
> Just to add to the visibility: we are also observing the same behavior after updating to `42.0.0`. This is the error message we are getting, to help with debugging:
> 
> ```
> Caused by:
>     0: Arrow error: Invalid argument error: Column 'column1' is declared as non-nullable but contains null values
>     1: Invalid argument error: Column 'column1' is declared as non-nullable but contains null values
> ```
> 
> We are getting this error when reading some parquet files using Datafusion. I have verified with other tools (parquet cli, DuckDB) `column1` does not contain any null values and metadata of the files is correct.

Is there any small parquet file that has the same error, if we can reproduce the error easily, it is easier to find the root cause.

**Comment by hveiga** [comment]
> > Just to add to the visibility: we are also observing the same behavior after updating to `42.0.0`. This is the error message we are getting, to help with debugging:
> > ```
> > Caused by:
> >     0: Arrow error: Invalid argument error: Column 'column1' is declared as non-nullable but contains null values
> >     1: Invalid argument error: Column 'column1' is declared as non-nullable but contains null values
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We are getting this error when reading some parquet files using Datafusion. I have verified with other tools (parquet cli, DuckDB) `column1` does not contain any null values and metadata of the files is correct.
> 
> Is there any small parquet file that has the same error, if we can reproduce the error, it is easier to find the root cause.

We have been digging more regarding this error and it seems it is not related to the Datafusion upgrade, I apologize for the confusion. Therefore there's no file I can provide :(

**Comment by wiedld** [comment]
In [fixing one of the schema-metadata-drops](https://github.com/apache/datafusion/pull/12658), I ended by triggering the `Physical input schema should be the same as the one converted from logical input schema.` error in a test case.

I feel like [this introduced check](https://github.com/apache/datafusion/blob/322d83526909ab44cfbe34b982d1a1c36a4dbe8f/datafusion/core/src/physical_planner.rs#L676) is inadvertently surfacing other schema-handling bugs that we have. Note that I'm unclear if the reproducer I found is a bug, or if we expect additional metadata changes on physical plan creation (not familiar with that part of the code).

**Comment by alamb** [comment]
We have also been digging in what we saw in InfluxDB 3.0 and I filed https://github.com/apache/datafusion/issues/12687 to track it separately. Let's close this omnibus issue and we file individual issues for specific problems as we find them
