### ISSUE TITLE
Add insert_or_update and get_payloads methods to binary_map/binary_view_map

### ISSUE THREAD

**Issue by dmitrybugakov** [apache/datafusion#12594]
### Is your feature request related to a problem or challenge?

Currently, in the [datafusion-functions-extra repository](https://github.com/datafusion-contrib/datafusion-functions-extra/blob/main/src/common/collections), we have copied binary_map and binary_view_map from DataFusion. However, the `insert_or_update`and `get_payloads` methods are missing from the original binary_map and binary_view_map implementations in DataFusion.

To avoid code duplication and ensure that these methods are available in the original DataFusion project, it would be beneficial to move these methods to the core DataFusion repository.

**Comment by dmitrybugakov** [comment]
take

**Comment by jayzhan211** [comment]
> in the [datafusion-functions-extra repository](https://github.com/datafusion-contrib/datafusion-functions-extra/blob/main/src/common/collections), we have copied binary_map and binary_view_map

Is there any reason why can't we just import from datafusion but require copying the code?

**Comment by dmitrybugakov** [comment]
The reason we copied the map instead of importing directly from DataFusion is that the version in datafusion-functions-extra includes two additional methods. To avoid waiting for the next DataFusion release, we copied the map and added those methods locally.

https://github.com/apache/datafusion/pull/12385#issuecomment-2364555142
