### ISSUE TITLE
Convert `BuiltInWindowFunction::{Rank, PercentRank, DenseRank}`  to a user defined functions

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12648]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/8709

There is now no difference between "built in" / "prepackaged"  scalar and aggregate functions in DataFusion, however there are still some ["built in" window functions ](https://github.com/apache/datafusion/blob/9b4f90ad1eefabdc0d5bbbfd99e58765b041bb77/datafusion/expr/src/built_in_window_function.rs#L42-L69) -- see the current source for [`BuiltInWindowFunction`](https://github.com/apache/datafusion/blob/main/datafusion/expr/src/built_in_window_function.rs) for the up to date list of what remains

The problem with having two different kinds of window functions is
1. There are some features that may not be available to User Defined Window Functions that rely on built in
2. Users can not easily choose which window functions to include or override the behavior if they need something different

### Describe the solution you'd like

I would like to remove the "built in" version of this function and convert it to a user defined function

### Describe alternatives you've considered

At a high level the process is:
1. Add a new [WindowUDFImpl](https://docs.rs/datafusion/latest/datafusion/logical_expr/trait.WindowUDFImpl.html) in the [`functions-window`](https://github.com/apache/datafusion/tree/main/datafusion/functions-window) crate
2. Port the code from the relevant existing implementation of the the built in functions in [datafusion/physical-expr/src/window](https://github.com/apache/datafusion/tree/main/datafusion/physical-expr/src/window)
3. Remove the `BuiltInWindowFunction` variant and then get everything to compile (the compiler will show you where the existing implementations are)

### Additional context

Here are some good examples:
* @jcsherin  ported `RowNumber` in https://github.com/apache/datafusion/pull/12030

**Comment by alamb** [comment]
I think this is a good first issue for someone skilled in rust that wants to get a handle on how datafusion works. If you hit issues, let us know

**Comment by dharanad** [comment]
take

**Comment by hailelagi** [comment]
take

**Comment by jatin510** [comment]
If you don't mind . Can i work on this issue @hailelagi ?

**Comment by jatin510** [comment]
take

Thanks @hailelagi

**Comment by jatin510** [comment]
take

**Comment by Omega359** [comment]
Convert BuiltInScalarFunction:: -> Convert BuiltInWindowFunction::{NthValue}

**Comment by SteNicholas** [comment]
@jatin510, are you working on this ticket? I'm new comer to contribute. Could this ticket assign to me? cc @alamb

**Comment by jatin510** [comment]
Thanks for reaching out. I’m actually already working on this issue, and it’s my first task in the project as well. I’d like to continue with it. @SteNicholas

**Comment by jcsherin** [comment]
@SteNicholas You maybe interested in picking up `ntile` window function? It is also pending conversion to a user-defined window function. It looks like a good first issue to me.

See [https://github.com/apache/datafusion/blob/main/datafusion/physical-expr/src/window/ntile.rs](https://github.com/apache/datafusion/blob/main/datafusion/physical-expr/src/window/ntile.rs).
