### ISSUE TITLE
Macros for user-defined window functions

### ISSUE THREAD

**Issue by jcsherin** [apache/datafusion#12688]
### Is your feature request related to a problem or challenge?

Add macros for creating `WindowUDF` and `WindowFunction` expression from user-defined window functions.

This will be similar to existing macros in function aggeregates:
https://github.com/apache/datafusion/blob/80848f2a0a08b61be441ac37a00073d4447e9603/datafusion/functions-aggregate/src/macros.rs#L54-L58

### Describe the solution you'd like

Existing code which will be replaced by macros:
https://github.com/apache/datafusion/blob/e1b992a7878e78e8a63b7e24425c665727bda493/datafusion/functions-window/src/row_number.rs#L35-L54

New code using a macro:
```rust
define_udwf_and_expr!(
    RowNumber,
    row_number,
    "Returns a unique row number for each row in window partition beginning at 1."
);
```

The above example combines creating both user-defined window function and expression function API. This should work for majority of the cases. 

But separate macros will also be provided for cases where they are necessary. 

### Describe alternatives you've considered

As we begin to convert remaining `BuiltinWindowFunction::*` to user-defined window functions this will save developer effort.

### Additional context

Part of #8709. 
Follow-on to PR #12030. 

Needed for #12649, #12648.

**Comment by SteNicholas** [comment]
@jcsherin, could you assign this ticket to me? Thanks.

**Comment by jcsherin** [comment]
@SteNicholas Sorry for the confusion. This was unassigned but I already have a PR in the works (#12693). 

I've filed a few more additional good first issues for window functions which needs to be converted.

- [Convert BuiltInWindowFunction::Ntile to a user defined window function #12694
](https://github.com/apache/datafusion/issues/12694)
- [Convert BuiltInWindowFunction::CumeDist to a user defined window function #12695
](https://github.com/apache/datafusion/issues/12695)

You can reply with "take" in the comments of an issue and it'll be automatically assigned to you. 

See https://datafusion.apache.org/contributor-guide/index.html#open-contribution-and-assigning-tickets
