### ISSUE TITLE
Convert `BuiltInWindowFunction::CumeDist` to a user defined window function

### ISSUE THREAD

**Issue by jcsherin** [apache/datafusion#12695]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/datafusion/issues/8709

There is now no difference between "built in" / "prepackaged" scalar and aggregate functions in DataFusion, however there are still some ["built in" window functions ](https://github.com/apache/datafusion/blob/9b4f90ad1eefabdc0d5bbbfd99e58765b041bb77/datafusion/expr/src/built_in_window_function.rs#L42-L69)-- see the current source for [BuiltInWindowFunction](https://github.com/apache/datafusion/blob/main/datafusion/expr/src/built_in_window_function.rs) for the up to date list of what remains

The problem with having two different kinds of window functions is
1. There are some features that may not be available to User Defined Window Functions that rely on built in
2. Users can not easily choose which window functions to include or override the behavior if they need something different

### Describe the solution you'd like

I would like to remove the "built in" version of this function and convert it to a user defined function

### Describe alternatives you've considered

At a high level the process is:

1. Add a new [WindowUDFImpl](https://docs.rs/datafusion/latest/datafusion/logical_expr/trait.WindowUDFImpl.html) in the [functions-window](https://github.com/apache/datafusion/tree/main/datafusion/functions-window) crate
2. Port the code from the relevant existing implementation of the the built in functions in [datafusion/physical-expr/src/window](https://github.com/apache/datafusion/tree/main/datafusion/physical-expr/src/window)
3. Remove the BuiltInWindowFunction variant and then get everything to compile (the compiler will show you where the existing implementations are)

### Additional context

Here are some good examples:
- Port of RowNumber in [Convert built-in row_number to user-defined window function #12030](https://github.com/apache/datafusion/pull/12030)

**Comment by jcsherin** [comment]
This is a good first issue.

**Comment by jonathanc-n** [comment]
@SteNicholas Just checking, do you have time to do this? If not, I can try to work on it or work on it with you in parallel.
