### ISSUE TITLE
Add `groupby` to dataframe API

### ISSUE THREAD

**Issue by Eason0729** [apache/datafusion#12696]
### Is your feature request related to a problem or challenge?

I am learning `datafusion` by creating a simple project using dataframe API, and I notice that dataframe is missing functionality of `GROUP BY` without using SQL.

### Describe the solution you'd like

Something similar to [pandas dataframe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)

### Additional context

For reference, here is what I am trying to do:

> Making a text search tool

- When user add new document, I get a list of term and a double for its importance.
- When user search for document, they type a collection of term, the application would show top `N` term whose SUM of importance is greatest.

And the `BatchRecord` look like

|document_id|term|importance|
|:-:|:-:|:-:|
|1|Hello|0.1|
|1|World|0.1|
|...|...|...|

**Comment by Kev1n8** [comment]
I think you may use the `aggregate` method provided by dataframe. Check out: https://github.com/apache/datafusion/blob/dcc018ee8fe8ccc768368ac1441d63983dfe3193/datafusion/core/src/dataframe/mod.rs#L494

**Comment by Eason0729** [comment]
It works, thank for pointing it out.

I will close this issue then.
