### ISSUE TITLE
Field Metadata Lost on UNION

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12735]
### Describe the bug

During upgrade of DataFusion in InfluxDB @itsjunetime  found that somewhere Field level metadata (aka [`Field::with_metadata`](https://docs.rs/arrow/latest/arrow/datatypes/struct.Field.html) is being lost during DataFusion logical planning 

This manifests itself as an error during the physical planning

```
Internal Error: Physical input schema should be the same as the one converted from logical input schema
```

### To Reproduce

Run this query in `metadata.slt`

```sql
# Regression test: missing field metadata, from the NULL field on the left side of the union
query ITT
(SELECT id, NULL::string as name, l_name FROM "table_with_metadata")
  UNION
(SELECT id, name, NULL::string as l_name FROM "table_with_metadata")
ORDER BY id, name, l_name;
```

### Expected behavior

No error during physical planning

**Comment by alamb** [comment]
I believe @wiedld  plans to work on this

**Comment by wiedld** [comment]
take
