### ISSUE TITLE
Migrate documentation for all crypto functions from scalar_functions.md to code

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12828]
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/datafusion/issues/12740 this ticket is to migrate all the existing documentation for the above named functions from the static documentation to code and to remove them from the static file. 

Here is the current static content:
* doc source: https://github.com/apache/datafusion/blob/main/docs/source/user-guide/sql/scalar_functions.md
* rendered: https://datafusion.apache.org/user-guide/sql/scalar_functions.html
* Code source: https://github.com/apache/datafusion/tree/main/datafusion/functions/src/crypto

Need Functions:
(see source)

### Describe the solution you'd like

One (or more) PRs that
1. port the documentation for the above named functions from the static docs to code
2. Bonus points:  add sql examples should be added for all functions
3. Remove the documentation from the static docs

Here are some example PRs of doing this:
1. https://github.com/apache/datafusion/pull/12775 from @Omega359 
3. https://github.com/apache/datafusion/pull/12742

**Comment by alamb** [comment]
I think this is a good first issue as the scope is relatively small, and there are good examples of how to do this, and would help learn the code / project

**Comment by jonathanc-n** [comment]
take
