### ISSUE TITLE
Migrate documentation for aggregate functions from aggregate_functions.md to code

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12827]
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/datafusion/issues/12740 this ticket is to migrate all the existing documentation for aggregate functions from the static file to code and to remove them from the static file. 

Here is the current static content:
* doc source: https://github.com/apache/datafusion/blob/main/docs/source/user-guide/sql/aggregate_functions.md
* rendered: https://datafusion.apache.org/user-guide/sql/aggregate_functions.html
* Code source: https://github.com/apache/datafusion/tree/main/datafusion/functions-aggregate/src

Need Functions:

- [ ] Port / Add `Documentation` for ApproxDistinct
- [ ] Port / Add `Documentation` for ApproxMedian
- [ ] Port / Add `Documentation` for ApproxPercentileCont
- [ ] Port / Add `Documentation` for ApproxPercentileContWithWeight
- [ ] Port / Add `Documentation` for ArrayAgg
- [ ] Port / Add `Documentation` for Avg
- [ ] Port / Add `Documentation` for BoolAnd
- [ ] Port / Add `Documentation` for BoolOr
- [ ] Port / Add `Documentation` for Correlation
- [ ] Port / Add `Documentation` for Count
- [ ] Port / Add `Documentation` for CovarianceSample
- [ ] Port / Add `Documentation` for CovariancePopulation
- [ ] Port / Add `Documentation` for FirstValue
- [ ] Port / Add `Documentation` for LastValue
- [ ] Port / Add `Documentation` for Grouping
- [ ] Port / Add `Documentation` for Median
- [ ] Port / Add `Documentation` for Max
- [ ] Port / Add `Documentation` for Min
- [ ] Port / Add `Documentation` for NthValueAgg
- [ ] Port / Add `Documentation` for Regr
- [ ] Port / Add `Documentation` for Stddev
- [ ] Port / Add `Documentation` for StddevPop
- [ ] Port / Add `Documentation` for StringAgg
- [ ] Port / Add `Documentation` for Sum

### Describe the solution you'd like

One (or more) PRs that
1. port the documentation for the above named functions from the static docs to code
2. Bonus points:  add sql examples should be added for all functions
3. Remove the documentation from the static docs

Here are some example PRs of doing this:
1. https://github.com/apache/datafusion/pull/12775 from @Omega359 
3. https://github.com/apache/datafusion/pull/12742

**Comment by jonathanc-n** [comment]
take

**Comment by jonathanc-n** [comment]
Will work on this after @Omega359 approves of my first pr!
