### ISSUE TITLE
Change `MaybeNullBufferBuilder` into `Option<usize>` in `GroupColumn` code

### ISSUE THREAD

**Issue by Dandandan** [apache/datafusion#12826]
### Is your feature request related to a problem or challenge?

In `GroupColumn` code we track group values which are null.

However, as it's an aggregate, we don't have to track all null values but we should only need to track one index, saving some memory / cpu cycles while doing aggregates.

### Describe the solution you'd like

Change `MaybeNullBufferBuilder` to `Option<usize>` and update code accordingly.
Run benchmarks.

**Comment by jayzhan211** [comment]
Wow, it looks quite tricky at first glance but it makes sense

**Comment by Dandandan** [comment]
There is some existing code which does the same, so some inspiration could be taken from here https://github.com/apache/datafusion/blob/d83b3b26e897b87fb63c6928311526c8a2fe1aee/datafusion/physical-plan/src/aggregates/group_values/primitive.rs#L81

**Comment by Dandandan** [comment]
Forgot about that GroupColumn doesn't work this way - however there might be some other things we could do.
