### ISSUE TITLE
Regression on coercing Array of Structs

### ISSUE THREAD

**Issue by kazuyukitanimura** [apache/datafusion#12843]
### Describe the bug

https://github.com/apache/datafusion/pull/12753/files#diff-f1e354d4fe26237064d8194e10a6008efa4f88e2b68b8a8352086a5d011180b8R108 introduced to use `type_union_resolution`; however, this caused a regression on `coerce_types` against Array of Structs.

`type_union_resolution` returns `None` for  such cases and let the plan fail.

### To Reproduce

Found at https://github.com/apache/datafusion-comet/pull/1001#issuecomment-2403621922

### Expected behavior

The fix seems to be easy. We just need to addd 
```
                .or_else(|| struct_coercion(lhs_type, rhs_type))
```
at the end of `type_union_resolution_coercion`

Then, `type_union_resolution` returns `Some(...)` for Array of Structs.

**Comment by alamb** [comment]
@jayzhan211  has a PR to fix this here; https://github.com/apache/datafusion/pull/12839

> however, this caused a regression on coerce_types against Array of Structs.

Can someone help me understand what the end user query / behavior is expected when coercing arrays of structs? It is not clear what the semantics are supposed to be, and thus I am not sure if the PR completely implements the desired semantics

**Comment by jayzhan211** [comment]
I follow what DuckDB does, since they seem to have a mature support for struct type

**Comment by jayzhan211** [comment]
```
D create table t(s1 struct(a int, b varchar), s2 struct(a float, b varchar));
D insert into t values (row(1, 'r'), row(2.2, 'b'));
D select [s1, s2] from t;
┌──────────────────────────────────────────┐
│         main.list_value(s1, s2)          │
│       struct(a float, b varchar)[]       │
├──────────────────────────────────────────┤
│ [{'a': 1.0, 'b': r}, {'a': 2.2, 'b': b}] │
└──────────────────────────────────────────┘
D select coalesce(s1, s2) from t;
┌────────────────────────────┐
│      COALESCE(s1, s2)      │
│ struct(a float, b varchar) │
├────────────────────────────┤
│ {'a': 1.0, 'b': r}         │
└────────────────────────────┘
D select typeof(s1) from t;
┌──────────────────────────────┐
│          typeof(s1)          │
│           varchar            │
├──────────────────────────────┤
│ STRUCT(a INTEGER, b VARCHAR) │
└──────────────────────────────┘
```

Coercion rule is so inconsistent, array and coalesce converts int to float, but values doesn't
