### ISSUE TITLE
Migrate documentation for all datetime functions from scalar_functions.md to code

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#12859]
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/datafusion/issues/12740 this ticket is to migrate all the existing documentation for the above named functions from the static documentation to code and to remove them from the static file. 

Here is the current static content:
* doc source: https://github.com/apache/datafusion/blob/main/docs/source/user-guide/sql/scalar_functions.md
* rendered: https://datafusion.apache.org/user-guide/sql/scalar_functions.html
* Code source: https://github.com/apache/datafusion/tree/main/datafusion/functions/src/datetime

Need Functions:
(see source)

### Describe the solution you'd like

One (or more) PRs that
1. port the documentation for the above named functions from the static docs to code
2. Bonus points:  add sql examples should be added for all functions
3. Remove the documentation from the static docs
4. Run `./dev/update_function_docs.sh` to update the dynamic documentation

Here are some example PRs of doing this:
1. https://github.com/apache/datafusion/pull/12840 from @jonathanc-n 
1. https://github.com/apache/datafusion/pull/12775 from @Omega359 
3. https://github.com/apache/datafusion/pull/12742

**Comment by alamb** [comment]
I think this is a good first issue as the pattern is clear and it would be a good way to learn how the process works

**Comment by jatin510** [comment]
take

**Comment by jatin510** [comment]
take

**Comment by alamb** [comment]
Thanks @jatin510  🙏 

BTW @jonathanc-n notes on https://github.com/apache/datafusion/issues/12740#issuecomment-2406512268

> @alamb I think it should be mentioned here that ./dev/update_function_docs.sh should be ran, as it wasn't immediately obvious, and when I did my first migration I took a bit of time to find it.

**Comment by alamb** [comment]
Just checking in on how this is going @jatin510  -- if you don't have time, perhaps I can unassign you so others could work on it

**Comment by jatin510** [comment]
I will create a PR by tomorrow @alamb
