### ISSUE TITLE
Move StringArrayType, StringViewArrayBuilder, StringArrayBuilder & LargeStringArrayBuilder from functions/string/common.rs to a more common crate/module

### ISSUE THREAD

**Issue by Omega359** [apache/datafusion#12898]
### Is your feature request related to a problem or challenge?

Currently the StringArrayType trait and the String*Builder structs are in the string crate however these are used in other crates (unicode, soon to include regex) and thus should be moved out to a more common location to not introduce needless dependencies between function crates.

### Describe the solution you'd like

My first thought is to create a functions/string_common.rs file and move the above mentioned trait and structs to this file, update all code, remove crate dependencies and update any tests as required.

### Describe alternatives you've considered

Leave things alone and allow the crate dependencies to stay.

**Comment by Omega359** [comment]
Related to https://github.com/apache/datafusion/pull/12080

**Comment by tlm365** [comment]
I haven't checked the others thoroughly, but with `StringArrayType` I believe we can remove it now and reuse it from arrow-rs [here](https://github.com/apache/arrow-rs/blob/9633f14f8d9e5b9b8fdf3514b7acb77217b30584/arrow-string/src/like.rs#L160)

**Comment by Omega359** [comment]
take
