### ISSUE TITLE
CSV can't parse null value for non-string type (i32, i64, float)

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#12904]
### Describe the bug

As title, I would like to store null value in the csv table but couldn't.

### To Reproduce

Write a csv file to `datafusion/core/tests/data/data.csv` with
```csv
c1,c2
NULL,'a'
```

```
statement ok
CREATE EXTERNAL TABLE t (
c1 INT,
c2 VARCHAR,
)
STORED AS CSV
LOCATION '../core/tests/data/data.csv'
OPTIONS ('format.has_header' 'true');

query error DataFusion error: Arrow error: Parser error: Error while parsing value NULL for column 0 at line 1
select * from t;
```

### Expected behavior

Successfully store nulls for non-string type

### Additional context

String is fine

**Comment by Omega359** [comment]
I think this may be something best handled in the arrow-csv crate

**Comment by dhegberg** [comment]
take
