### ISSUE TITLE
Regex Match fails on `Dictionary` and `Utf8View`

### ISSUE THREAD

**Issue by blaginin** [apache/datafusion#12924]
### Describe the bug

`SELECT arrow_cast('abc', 'Utf8View') ~* arrow_cast('a.c', 'Dictionary(Int32, Utf8)');` fails on the latest build

<img width="1139" alt="RustRover-EAP 2024-10-14 20 45 54" src="https://github.com/user-attachments/assets/fcfec4ca-23bc-4bb5-8ece-ee1a46531cdc">

### Expected behavior

Regex Match should work the same way Like match does

<img width="857" alt="RustRover-EAP 2024-10-14 20 47 15" src="https://github.com/user-attachments/assets/49716064-5fc7-4282-b90b-69344432f590">

**Comment by blaginin** [comment]
@goldmedal Do you think we should add tests for something like this in your `sqllogictech` string files? It feels like operators on everything × everything should catch it. For example, I could find this issue by doing:

<img width="1049" alt="image" src="https://github.com/user-attachments/assets/19036990-b4b7-44f6-a92c-def996367bbb">

**Comment by Omega359** [comment]
https://github.com/apache/datafusion/issues/11911

**Comment by goldmedal** [comment]
> @goldmedal Do you think we should add tests for something like this in your `sqllogictech` string files? It feels like operators on everything × everything should catch it. For example, I could find this issue by doing:

Sure, I think it's good to have a test framework to test a string type with other string types. We only do this kind of thing at 
https://github.com/apache/datafusion/blob/fce331a4f7ca908ee7b4500d104fae9ec657f471/datafusion/sqllogictest/test_files/string/string_view.slt#L106-L110

If you want to add the test for `StirngView` specifically, I guess you can do it in this part. Or if you want to do it for all string types, you could create the testing data in https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/string/init_data.slt.part
and add the tests in
https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/string/string_query.slt.part

**Comment by blaginin** [comment]
> Or if you want to do it for all string types…
Yes, this feels more robust! Let’s wait for the original issue to be solved than and then add tests for all cases

**Comment by blaginin** [comment]
closed as a duplicate of https://github.com/apache/datafusion/issues/11911
