### ISSUE TITLE
`unnest` + field access of "list of struct" broken

### ISSUE THREAD

**Issue by crepererum** [apache/datafusion#12921]
### Describe the bug

See reproducer.

### To Reproduce

Use the following sqllogictest:

```text
statement ok
CREATE TABLE lists_of_structs_table
AS VALUES 
    ('row1', [named_struct('a', 1, 'b', 2), named_struct('a', 2, 'b', 3)]),
    ('row2', [named_struct('a', 4, 'b', 5)])
;

query T?
select column1, unnest(column2) from lists_of_structs_table;
----
row1 {a: 1, b: 2}
row1 {a: 2, b: 3}
row2 {a: 4, b: 5}

# unnest + struct element access
query error DataFusion error: Schema error: No field named b. Valid fields are lists_of_structs_table.column1, lists_of_structs_table.column2.
select column1, unnest(column2)["b"] from lists_of_structs_table;
```

### Expected behavior

Since `unnest` creates a struct column, I feel that this should work.

### Additional context

Tested w/ 5391c98f7a3fda1f8eef994591286b1596033bc5 .

**Comment by duongcongtoai** [comment]
let me take a look, i'm working on some cleanup regarding this feature: https://github.com/apache/datafusion/pull/12836

**Comment by duongcongtoai** [comment]
I think this is some problem with the parser, and perhaps not yet supported.
The query will be perform correctly if replace double quote with single quote

```
select column1, unnest(column2)["b"] from lists_of_structs_table;
```

The query with double quote will fail for normal queries, not just unnest

**Comment by crepererum** [comment]
Oh 🤦, I think I've tripped over the quoting then. I can never remember which is the string and which one is the identifier in SQL. In that case, the error message is actually correct, since my query tries to index the struct with a dynamic string from column `b`, which doesn't exist. The intention was to index with a static string `'b'` (as you suggested). So that's not actually a bug.
