### ISSUE TITLE
Revise and remove usages of make_function_scalar_inputs, make_function_scalar_inputs_return_type, make_function_inputs2

### ISSUE THREAD

**Issue by findepi** [apache/datafusion#12923]
In https://github.com/apache/datafusion/pull/12881, https://github.com/apache/datafusion/pull/12890 it turned out that `make_function_scalar_inputs_return_type` may lead to less performant code.

In https://github.com/apache/datafusion/pull/12909 it turned out that `make_function_inputs2` may lead to less performant code.

Revise remaining usages and improve. See above PRs for guidance.

**Comment by buraksenn** [comment]
Can I take this one @findepi ?

**Comment by buraksenn** [comment]
take
