### ISSUE TITLE
Migrate documentation for all array functions from scalar_functions.md to code

### ISSUE THREAD

**Issue by jonathanc-n** [apache/datafusion#12927]
### Is your feature request related to a problem or challenge?

Is your feature request related to a problem or challenge?
As part of https://github.com/apache/datafusion/issues/12740 this ticket is to migrate all the existing documentation for the above named functions from the static documentation to code and to remove them from the static file.

Here is the current static content:

doc source: https://github.com/apache/datafusion/blob/main/docs/source/user-guide/sql/scalar_functions.md
rendered: https://datafusion.apache.org/user-guide/sql/scalar_functions.html
Code source: https://github.com/apache/datafusion/tree/main/datafusion/functions-nested
Need Functions:
(see source)

Additional context
No response

### Describe the solution you'd like
One (or more) PRs that

port the documentation for the above named functions from the static docs to code
Bonus points: add sql examples should be added for all functions
Remove the documentation from the static docs
Run ./dev/update_function_docs.sh to update the dynamic documentation
Here are some example PRs of doing this:

https://github.com/apache/datafusion/pull/12840 from @jonathanc-n
 Migrate documentation for all string functions from scalar_functions.md to code  #12775 from @Omega359
https://github.com/apache/datafusion/pull/12742

**Comment by jonathanc-n** [comment]
take

**Comment by alamb** [comment]
> @alamb This can be added to the #12740

Done -- thank you @jonathanc-n
