### ISSUE TITLE
Ensure that scalar functions fulfil the ColumnarValue contract

### ISSUE THREAD

**Issue by jonahgao** [apache/datafusion#12959]
### Is your feature request related to a problem or challenge?

As said in PR #12922 
> If all UDF arguments are scalars, so should be the result.

In PR #12922, @joroKr21 implements it for math functions that use `make_math_*_udf` macros.

Maybe we should consider this problem for other scalar functions, such as math functions that don't use the macros.

**Comment by jatin510** [comment]
can I work on this issue @jonahgao

**Comment by jonahgao** [comment]
> can I work on this issue @jonahgao

Hi @jatin510 , there is already a PR #12965 for this issue.
