### ISSUE TITLE
[substrait] handle AggregateRel grouping_expressions field

### ISSUE THREAD

**Issue by vbarua** [apache/datafusion#12957]
### Is your feature request related to a problem or challenge?

https://github.com/apache/datafusion/pull/12863 updated DataFusion with changes from Substrait 0.58.0

The Substrait changes included https://github.com/substrait-io/substrait/pull/706, which added a new `grouping_expressions` field to the AggregateRel.

### Describe the solution you'd like

DataFusion should be updated to correctly read and write this new field, in line with the updated spec.

**Comment by akoshchiy** [comment]
take
