### ISSUE TITLE
Improve performance of `regexp_count`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13011]
### Is your feature request related to a problem or challenge?

@Omega359  and @xinlifoobar  added the `regexp_count` function in https://github.com/apache/datafusion/pull/12970

However, `regexp_count` seems to be significantly slower than `regexp_match` and `regexp_like`. (see https://github.com/apache/datafusion/pull/12080#issuecomment-2316755718 for a benchmark) 

### Describe the solution you'd like

I would like to review the benchmark for `regexp_count`  and figure out why it is slower and if so try to improve it

**Comment by buraksenn** [comment]
take

**Comment by Dandandan** [comment]
I am wondering if this is not really caused by doing more work - regexp_match only needs to find the first match and can return early, while regexp_count needs to find all matches and return the count.

**Comment by Omega359** [comment]
Possible @Dandandan however I don't think it would explain the difference with regexp_replace which I would think would have to do even more work.

**Comment by Dandandan** [comment]
Yeah that is suspicious I agree, I think it is worth checking whether regexp_replace in the benchmark does replace all matches or just the first value.

**Comment by alamb** [comment]
So is the conclusion we can't reproduce the difference in benchmark numbers, and thus we should close this ticket?

**Comment by Omega359** [comment]
It's still 50% slower than replace so I think it may be worth investigating at some point. Is it a huge blocker? Unlikely unless this is a hotspot in someone's processing pipeline
