### ISSUE TITLE
docs: Add section or page for special functions

### ISSUE THREAD

**Issue by Omega359** [apache/datafusion#13036]
### Is your feature request related to a problem or challenge?

As mentioned in https://github.com/apache/datafusion/pull/12948#discussion_r1802076218 there are a few scalar functions that are not normal UDF's and cannot be documented in the standard manner as per https://github.com/apache/datafusion/issues/12740 Thus we need to find a way to add documentation for those functions to the user guide once the scalar function documentation is completely migrated over to the new code driven design.

### Describe the solution you'd like

A few idea:

- Hardcode a section into the generated scalar-functions.md for these functions
- Add a new page to the documentation that outlines 'special' functions

**Comment by jonathanc-n** [comment]
take

**Comment by Omega359** [comment]
Here is a list of the remaining 'special' functions as I see it. Unnest is really the only special function, the others are just existing functions with different syntax such as `substring('Thomas' from 2 for 3) → hom`. 

- unnest (array), unnest(struct)
- extract - it's data_part, but with different syntax
- position - it's strpos, but with different syntax
- substring, it's substr, but with different syntax
- trim, it's one of the trim functions, but with different syntax

I am unsure right now how to properly document the 'different syntax' types of functions. Perhaps these should be covered in a page that covers things like `ilike`, `cube`, `trim`, etc.
