### ISSUE TITLE
Deprecate `LogicalPlan::CrossJoin`

### ISSUE THREAD

**Issue by Dandandan** [apache/datafusion#13057]
### Is your feature request related to a problem or challenge?

After https://github.com/apache/datafusion/pull/12985 we don't generate `LogicalPlan::CrossJoin` in the planner.
It would be good to deprecate / remove this in the future.

**Comment by ding-young** [comment]
take

**Comment by buraksenn** [comment]
Sorry @ding-young , I've already started working on this before typing `take` and just opened a PR.

**Comment by ding-young** [comment]
@buraksenn Ohh I see. Thank you for letting me know.

**Comment by buraksenn** [comment]
take
