### ISSUE TITLE
Deprecate `ScalarUDFImpl::invoke`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13064]
### Is your feature request related to a problem or challenge?

in https://github.com/apache/datafusion/pull/13001 @agscpp  added a general function `ScalarUDFImpl::invoke_batche` that handles inputs with 0 and more than 0 arguments. 

Previously, there were two separate functions to handle these cases:
1. https://docs.rs/datafusion/latest/datafusion/logical_expr/trait.ScalarUDFImpl.html#tymethod.invoke
2. https://docs.rs/datafusion/latest/datafusion/logical_expr/trait.ScalarUDFImpl.html#method.invoke_no_args

### Describe the solution you'd like

I would like to mark `invoke` and `invoke_no_args` deprecated 

### Describe alternatives you've considered

1. Mark the functions deprecated, with a message to implement `invoke_batch` instead. for example 
https://github.com/apache/datafusion/blob/c22abb4ac3f1af8bbdf176ef0198988fc7b0982c/datafusion/expr/src/expr.rs#L1125
2. Update the documentation so `invoke_batch` is the main API and the documentation reflects that
3. Update the DataFusion codebase so that the `ScalarUDFImpl`s use invoke_batch rather than `invoke` and `invoke_udf`

### Additional context

I think this is pretty well specified and largely mechanical so it would be a good first issue

**Comment by notfilippo** [comment]
take

**Comment by findepi** [comment]
Sorry for duplicating this in https://github.com/apache/datafusion/issues/13238. It's already in progress, so let's maybe close this one?
