### ISSUE TITLE
Document how long deprecated methods should be kept

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13077]
Btw @alamb we should have a policy for `deprecated` modules, how long we keep them, the similar as we do for MSRV

_Originally posted by @comphead in https://github.com/apache/datafusion/issues/13056#issuecomment-2430233472_

**Comment by comphead** [comment]
2 or 3 might be too short? Reg to https://crates.io/crates/datafusion/versions
DF gets released every month sometimes longer, changing API can be challenging. WDYT about 6 months or 6 major versions whichever is lower?

**Comment by alamb** [comment]
> 2 or 3 might be too short? Reg to https://crates.io/crates/datafusion/versions DF gets released every month sometimes longer, changing API can be challenging. WDYT about 6 months or 6 major versions whichever is lower?

Sounds like a good place to start with me
