### ISSUE TITLE
feat: Add `alternative_syntax` function for docs

### ISSUE THREAD

**Issue by jonathanc-n** [apache/datafusion#13139]
### Is your feature request related to a problem or challenge?

This is mentioned in #12741 from @Omega359. The doc migration is almost wrapped up, but there are a few functions that are listed in #12741 that have alternative syntax options.

### Describe the solution you'd like

Add an `alternative_syntax` to the docs.

**Comment by jonathanc-n** [comment]
take

**Comment by jonathanc-n** [comment]
@Omega359 @alamb Hopefully we can get this merged today, I have been working on nthvalue migration to udwf so hopefully we can get the entire doc migration finished by tomorrow. I will be free this week to work on this a little more.

**Comment by Omega359** [comment]
@jonathanc-n - It's my understanding that typically PR's are left approved but not merged for a day or so to give others an opportunity to comment. We are definitely close to closing out the doc work and I really do appreciate your help in getting this feature across the line! ❤️ I certainly would not have been able to get this far on my own so quickly with my current workload

**Comment by jonathanc-n** [comment]
I'm struggling quite a bit with migrating the ntile, because I need to delete all of the builtinwindow functionality which is causing many bugs in many places that I am not familiar with. Help for #12649 would be appreciated.

**Comment by alamb** [comment]
> @Omega359 @alamb Hopefully we can get this merged today, I can start working on nthvalue migration to udwf so hopefully we can get the entire doc migration finished by tomorrow. I will be free this week to work on this.

Thanks for all your work so far @jonathanc-n 

>  It's my understanding that typically PR's are left approved but not merged for a day or so to give others an opportunity to comment.

Yes exactly. This is explained in a bit more detail in https://datafusion.apache.org/contributor-guide/index.html#pull-request-overview

**Comment by Omega359** [comment]
> I'm struggling quite a bit with migrating the ntile, because I need to delete all of the builtinwindow functionality which is causing many bugs in many places that I am not familiar with. Help for #12649 would be appreciated.

If you can push to a branch in your git repo I may be able to take a look this week.

**Comment by jonathanc-n** [comment]
@Omega359 Sounds good, thank you!
