### ISSUE TITLE
substr function no longer coerces types previously accepted

### ISSUE THREAD

**Issue by Omega359** [apache/datafusion#13150]
### Describe the bug

In my test suite I have a test that includes the following:

` substr(error_code, 3)`

where error_code was an int32. In  previous versions of DF the error_code used to be automatically coerced to Utf8 however with https://github.com/apache/datafusion/pull/12308 a `coerce_types` impl was added that no longer will try to coerce types to Utf8.  Instead the sql needs to be changed to the following to work

`substr(error_code::varchar, 3)`

### To Reproduce

```sql
select substr(123456, 3);
```

### Expected behavior

type coercion should allow for this to work as it used to.

**Comment by jayzhan211** [comment]
In Postgres and DuckDB, they don't accept integer as the first input, I suggest we follow them.

**Comment by Omega359** [comment]
Oh, good point, I didn't think to check that @jayzhan211.
