### ISSUE TITLE
default impl for WindowUDFImpl::expressions should use all input expressions

### ISSUE THREAD

**Issue by Michael-J-Ward** [apache/datafusion#13168]
### Is your feature request related to a problem or challenge?

https://github.com/apache/datafusion/pull/12857  added the `expressions` method to the `WindowUDFImpl` trait.

The default impl currently only takes the first `input_expr` and discards the rest.

https://github.com/apache/datafusion/blob/444a673682a4823b98695568ecdab1087b5b6a60/datafusion/expr/src/udwf.rs#L314-L319

This altered behavior caused a regression in a two column Window UDF used in `datafusion-python` tests. See [this comment detailing the error](https://github.com/apache/datafusion-python/pull/905#issuecomment-2442642237) and this commit that [fixes it](https://github.com/apache/datafusion-python/pull/905/commits/3676b1d0c8bcb861b9c4cf00dc15206dd4bec713).

### Describe the solution you'd like

The default behavior should just return all the input expressions.

### Describe alternatives you've considered

I didn't find any justification for only taking the first `input_expr` as the default behavior, so probably I'm missing something.

@jcsherin - please let me know if there's a reason that I'm missing for this behavior.

**Comment by jcsherin** [comment]
In `lead`/`lag` user-defined window functions which accepts 1-3 arguments, the `shift_offset` (2nd argument) and `default_value` (3rd argument) are saved as fields of `WindowShiftEvaluator` struct which implements `PartitionEvaluator`. 

https://github.com/apache/datafusion/blob/223bb02fce886b47dc1ac81e2eda2bd3c6d60c3e/datafusion/functions-window/src/lead_lag.rs#L338-L344 

The arguments are parsed once and cached when the partition evaluator executes. So this allows correct operation even though `expressions()` returns only the first input expression to the partition evaluator.

Now based on your example downstream I see that this API is overly restrictive. I agree that the default behavior needs to be where `expressions()` returns all the input expressions. 

Apologies for the time you spent investigating this issue 🙏
