### ISSUE TITLE
Derive `Clone` for more ExecutionPlans

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13202]
### Is your feature request related to a problem or challenge?

In our code / optimizers we have a lot of code that looks like this when we are
trying to rewrite a SortExec node by making a copy and changing only some of the
fields. For example:

```rust
     new_plan = Ok(Arc::new(
                SortExec::new(sort_exec.expr().to_vec(), Arc::clone(sort_exec.input()))
                    .with_fetch(sort_exec.fetch())
                    .with_preserve_partitioning(true),
            ));
```

This is problematic and we have had bugs in the past when SortExec got a new field (like `fetch`)

We would like to simply be able to make a copy and modify appropriately:

```rust
     new_plan = Ok(Arc::new(sort_exec.clone().with_preserve_partitioning(true)));
```

Many ExecutionPlans like [`ParquetExec` already implement `Clone`](https://docs.rs/datafusion/latest/datafusion/datasource/physical_plan/parquet/struct.ParquetExec.html#impl-Clone-for-ParquetExec) so it is nice to
make the rest consistent

### Describe the solution you'd like

I would like to derive `Clone` for other plans

**Comment by findepi** [comment]
> This is problematic and we have had bugs in the past when SortExec got a new field (like `fetch`)
> 
> We would like to simply be able to make a copy and modify appropriately:
> 
> ```rust
>      new_plan = Ok(Arc::new(sort_exec.clone().with_preserve_partitioning(true)));
> ```

IMO the right answer in all cases is full destructuring and direct creation, without any shortcuts (like `..` or builders).
Why?

When a plan node gains new field, it's impossible to judge apriori about  all callsites using this plan node. Does the logic still hold with this new field being added? Does it need to change?
Each callsite needs to be revisited (unless this is printing for debug or whatever).
And the only known way to force this to happen is to _not_ have shortcuts like `..` / builders or cloning.

**Comment by findepi** [comment]
I thought it's an option to destruct taking fields by reference (like in `match`)

**Comment by alamb** [comment]
> I thought it's an option to destruct taking fields by reference (like in `match`)

That is true but it won't help modifying the field 🤔

**Comment by findepi** [comment]
Oh see your point. Destruct by reference, compute new value for a field and then you want to construct new instance. You need shallow clone of all other fields. 👍

**Comment by alamb** [comment]
Closed in https://github.com/apache/datafusion/pull/13203
