### ISSUE TITLE
Migrate code to use ScalarUDF::invoke_batch and ScalarUDFImpl::invoke_batch

### ISSUE THREAD

**Issue by findepi** [apache/datafusion#13238]
Migrate code from ScalarUDF::invoke and invoke_no_arg to use ScalarUDF::invoke_batch 
And from ScalarUDFImpl::invoke and invoke_no_arg  ScalarUDFImpl::invoke_batch.

The places in the  code to be changed can be found by searching for `#[allow(deprecated)] // TODO migrate UDF invoke to invoke_batch`

- follows https://github.com/apache/datafusion/pull/13001 -- introduced `invoke_batch`
- follows https://github.com/apache/datafusion/pull/13179 -- deprecated the other invoke variants for ScalarUDF
- follows https://github.com/apache/datafusion/pull/13174 -- deprecated the other invoke variants for ScalarUDFImpl

**Comment by irenjj** [comment]
take

**Comment by findepi** [comment]
@irenjj thanks!
it would be better to wait for https://github.com/apache/datafusion/pull/13174 to be merged first.
https://github.com/apache/datafusion/pull/13246 migrates `invoke_no_arg`, but definitely more work is for the regular `invoke`, your help here would be awesome!
