### ISSUE TITLE
Add support for string view to a few functions

### ISSUE THREAD

**Issue by timsaucer** [apache/datafusion#13330]
### Is your feature request related to a problem or challenge?

These functions are failing when passing in a string view instead of a string. Now that string view is the default type, it is causing some regressions on existing code that have to be modified.

### Describe the solution you'd like

Add options of passing in string view to these:

- [ ] ArrayToString
- [ ] NamedStructFunc
- [ ] DateBinFunc (I couldn't quite track down where the Utf->Interval or Timestamp conversion occurs
- [ ] BitLengthFunc
- [ ] ConcatFunc (gives error on optimizer not matching schema)
- [ ] EncodeFunc

### Additional context

These were discovered during the `datafusion-python` migration to DF43.0.0. This commit is where I made adjustments in that repo to account for these: https://github.com/apache/datafusion-python/pull/905/commits/fcb5f968e3f11cbcdf77d4c86e5d437de7427f11

**Comment by jonathanc-n** [comment]
This could be made into an EPIC. Should we apply this to the regexp functions as well? Off the top of the head, I remember `regexp_match` still needing string view support.

**Comment by timsaucer** [comment]
Related: https://github.com/apache/datafusion/issues/13347

**Comment by Omega359** [comment]
regexp_match looks to not support stringview either.
```
// TODO: Native support Utf8View for regexp_match.
                    TypeSignature::Exact(vec![Utf8, Utf8]),
                    TypeSignature::Exact(vec![LargeUtf8, LargeUtf8]),
                    TypeSignature::Exact(vec![Utf8, Utf8, Utf8]),
                    TypeSignature::Exact(vec![LargeUtf8, LargeUtf8, LargeUtf8]),
```

**Comment by Omega359** [comment]
regexp_match filed as https://github.com/apache/datafusion/issues/13357

**Comment by timsaucer** [comment]
I'm going to recommend a 43.1.0 release after we get all these resolved

**Comment by Omega359** [comment]
[array_to_string](https://github.com/apache/datafusion/blob/main/datafusion/functions-nested/src/string.rs) aslso does not appear to support Utf8View

**Comment by Omega359** [comment]
None of the crypto functions support UTF8View directly as a input type. For example [digest](https://github.com/apache/datafusion/blob/main/datafusion/functions/src/crypto/digest.rs):
```Rust
signature: Signature::one_of(
                vec![
                    Exact(vec![Utf8, Utf8]),
                    Exact(vec![LargeUtf8, Utf8]),
                    Exact(vec![Binary, Utf8]),
                    Exact(vec![LargeBinary, Utf8]),
                ],
                Volatility::Immutable,
            ),
```

**Comment by Omega359** [comment]
[NullIf](https://github.com/apache/datafusion/blob/main/datafusion/functions/src/core/nullif.rs):

```Rust
static SUPPORTED_NULLIF_TYPES: &[DataType] = &[
    DataType::Boolean,
    DataType::UInt8,
    DataType::UInt16,
    DataType::UInt32,
    DataType::UInt64,
    DataType::Int8,
    DataType::Int16,
    DataType::Int32,
    DataType::Int64,
    DataType::Float32,
    DataType::Float64,
    DataType::Utf8,
    DataType::LargeUtf8,
];
```

**Comment by Omega359** [comment]
[nvl](https://github.com/apache/datafusion/blob/main/datafusion/functions/src/core/nvl.rs):
```Rust
static SUPPORTED_NVL_TYPES: &[DataType] = &[
    DataType::Boolean,
    DataType::UInt8,
    DataType::UInt16,
    DataType::UInt32,
    DataType::UInt64,
    DataType::Int8,
    DataType::Int16,
    DataType::Int32,
    DataType::Int64,
    DataType::Float32,
    DataType::Float64,
    DataType::Utf8,
    DataType::LargeUtf8,
];
```

**Comment by Omega359** [comment]
crypto PR - https://github.com/apache/datafusion/pull/13407
array_to_string/string_to_array PR - https://github.com/apache/datafusion/pull/13403
nvl PR - https://github.com/apache/datafusion/pull/13382
nullif PR - https://github.com/apache/datafusion/pull/13380
