### ISSUE TITLE
[substrait] Replace SessionContext with a trait

### ISSUE THREAD

**Issue by notfilippo** [apache/datafusion#13342]
### Is your feature request related to a problem or challenge?

When producing / consuming a substrait plan it's not always practical to pass the SessionContext. Most of the methods used in the crate directly reference SessionContext even though all of them actually make use of the memory in its underlying SessionState. The producer / consumer method could directly take SessionState or we could allow further abstraction by creating a trait with just the functionality needed.

### Describe the solution you'd like

It should be possible to just use the SessionState or a specialised trait when producing / consuming substrait plans.

**Comment by notfilippo** [comment]
take

**Comment by vbarua** [comment]
This is complementary to https://github.com/apache/datafusion/issues/13318
