### ISSUE TITLE
  Implement better tests for ParquetExec

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#134]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11020

Implement better tests for ParquetExec

**Comment by alamb** [comment]
Comment from Krisztian Szucs(kszucs) @ 2021-01-12T14:48:02.701+0000:
<pre>Postponing to 4.0</pre>

**Comment by houqp** [comment]
looks like this could potentially be a good first issue, but we need to provide more details and define what better means here :)

**Comment by novemberkilo** [comment]
@alamb @houqp I am interested in working on this once you've helped specify (it a bit) better :)

**Comment by alamb** [comment]
I think that since @andygrove  filed https://issues.apache.org/jira/browse/ARROW-11020 this one he would probably need to weigh in on what he had in mind.

The `ParquetExec` implementation has changed fairly significantly in the last few months (e.g. https://github.com/apache/arrow-datafusion/pull/1141) as well; Perhaps @rdettai  has some ideas of areas that need better test coverage

**Comment by alamb** [comment]
ParquetExec is pretty well tested in my mind now -- I don't think this ticket is actionable
