### ISSUE TITLE
[substrait] support try_cast

### ISSUE THREAD

**Issue by vbarua** [apache/datafusion#13419]
### Is your feature request related to a problem or challenge?

The Substrait [Cast Expression](https://github.com/substrait-io/substrait/blob/e3a7773895f4121deb6904b79efbcd76c656c9e8/proto/substrait/algebra.proto#L1285-L1295) contains a field to specify whether the cast should return null if it fails (TRY CAST) or throw an error if it fails (CAST).

The current Substrait consumer and producers do not set this field.

### Describe the solution you'd like

The `failure_behavior` field should be set to allow encoding `CAST` and TRY_CAST` correctly.

**Comment by eatthepear** [comment]
take
