### ISSUE TITLE
Subquery check_internal_plan does not support LogicalPlan::Unnest

### ISSUE THREAD

**Issue by kosiew** [apache/datafusion#13498]
### Describe the bug

The `Error during planning: Unsupported operator in the subquery plan.` error in
https://github.com/apache/datafusion-python/issues/850 is due to 
datafusion/optimizer/src/analyzer/subquery.rs's check_internal_plan not handling LogicalPlan::Unnest

### To Reproduce

Follow the steps in https://github.com/apache/datafusion-python/issues/850

### Expected behavior

Datafusion should handle it

**Comment by kosiew** [comment]
I can try to fix this but I don't know where the existing tests for check_inner_plan are.

**Comment by alamb** [comment]
@kosiew  I would recommend trying to write a SQL query (or rust dataframe example) that shows the same behavior

the sql tests are in https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/unnest.slt

The dataframe test are in: https://github.com/apache/datafusion/blob/main/datafusion/core/tests/dataframe/mod.rs

**Comment by kosiew** [comment]
Thanks @alamb
