### ISSUE TITLE
Perf: Allow User defined functions to potentially reuse their argument arrays (to avoid new allocations)

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13516]
### Is your feature request related to a problem or challenge?

Arrow Arrays are designed to be immutable and use shared references extensively, but it is possible to reuse the underlying buffer in some cases when there are no other references (see the arrow [unary_mut](https://docs.rs/arrow/latest/arrow/compute/fn.unary_mut.html) kernel for example)

At the time of writing, DataFusion scalar functions ([`ScalarFunctionImpl`](https://docs.rs/datafusion/latest/datafusion/logical_expr/trait.ScalarUDFImpl.html) must *always* allocate a new array when generating output. They can not reuse the existing underlying memory, even if the source array will never be used again

This is because the invoke signature gets the arguments as reference (slice of `ColumnarValue`) rather than by ownership

```rust
fn invoke_batch(
    &self,
    args: &[ColumnarValue],
    number_rows: usize,
) -> Result<ColumnarValue, DataFusionError>
```

For example, an expression like `(a + b) + c`  will be evaluated like
- `a + b` --> `temp_array`
- `temp_array + c` --> `result_array`

Resulting in two new allocations

### Describe the solution you'd like

It would be really nice if it were possible to evaluate `(a + b) + c`  like this (with no new allocations)
- `a + b` --> `a` (write output to `a`, reusing allocation)
- `a + c` --> `a` (now add c, also reusing allocation)

And the result would be a new array that re-used the original allocation of the `a` array

### Describe alternatives you've considered

Now that this is merged
- https://github.com/apache/datafusion/pull/13290 (thanks @joseph-isaacs)

I think we can make  it possible in the future to reuse allocations by changing what is passed into `ScalarFunctionArgs` 

Since we haven't yet released a version with `ScalarFunctionArgs` we can change its signature without breaking APIs until DataFusion 44 is released

### Additional context

I have a draft of the basic idea here: 
- https://github.com/apache/datafusion/pull/13507

**Comment by alamb** [comment]
I think @joseph-isaacs  has done this in https://github.com/apache/datafusion/pull/13491

**Comment by findepi** [comment]
For closing this issue could we have an example showing how to do this reuse and proving that it really takes place?
Is this maybe part of https://github.com/apache/datafusion/pull/13491?

**Comment by alamb** [comment]
> For closing this issue could we have an example showing how to do this reuse and proving that it really takes place?
Is this maybe part of https://github.com/apache/datafusion/pull/13491?

This is a good idea -- I agree an example should be written

**Comment by Omega359** [comment]
> I think @joseph-isaacs has done this in #13491

Are you sure? I took a look at [ScalarFunctionArgs](https://github.com/apache/datafusion/blob/86740bfd3d9831d6b7c1d0e1bf4a21d91598a0ac/datafusion/expr/src/udf.rs#L331) in main and it seems to use `&'a [ColumnarValue]`

**Comment by alamb** [comment]
Good call @Omega359  -- I think it was removed eventually. I'll try and make the change with an example over the next few days/weeks

**Comment by alamb** [comment]
Here is a PR that implements the change and adds an example:
- https://github.com/apache/datafusion/pull/13637
