### ISSUE TITLE
Simple query fails with `column types must match schema types`

### ISSUE THREAD

**Issue by adriangb** [apache/datafusion#13534]
### Describe the bug

Found in our production system using datafusion internals, but reproducible in `datafusion-cli`:

```sql
SELECT
    'foo' AS text,
    arrow_cast('2024-01-01T00:00:00Z'::timestamptz, 'Timestamp(Microsecond, Some("UTC"))') AS ts
GROUP BY ts, text
```

Gives:

```
Arrow error: Invalid argument error: column types must match schema types, expected Timestamp(Microsecond, Some("UTC")) but found Timestamp(Microsecond, None) at column index 0
```

### Additional context

I bisected it with this script:

```shell
pushd datafusion-cli && cargo run --bin datafusion-cli -- --file ../q.sql && popd
```

And then:

```shell
git checkout c0ca4b4  # current HEAD
git bisect start
git bisect bad
git checkout 88f58bf # 43.0, I manually verified it is okay
git bisect good
git bisect run ./test.sh  # the above script
```

The result points to ecc04d4af85a29111a1598e615350fea84e60fcb / https://github.com/apache/datafusion/pull/13457

**Comment by adriangb** [comment]
cc @jonathanc-n @jayzhan211 @alamb

**Comment by alamb** [comment]
@jayzhan211  is on the case:
- https://github.com/apache/datafusion/pull/13535

**Comment by alamb** [comment]
I think this issue was introduced in 
- https://github.com/apache/datafusion/pull/13457

Which has not been released yet
