### ISSUE TITLE
Improve performance of `corr` function

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13549]
### Is your feature request related to a problem or challenge?

The `corr` function is used in the h20 benchmark and is quite slow. 

https://github.com/apache/datafusion/blob/main/datafusion/functions-aggregate/src/correlation.rs

It would be great to make it faster so our performance in the H2o benchmark improves

### Describe the solution you'd like

See details on https://github.com/apache/datafusion/issues/13548

1. Add a benchmark for `corr` function
2. Improve performance of `corr` function (likely by implementing `GroupsAccumulator`)

### Additional context

Used here in @MrPower's benchmark:

https://github.com/MrPowers/mrpowers-benchmarks/blob/0b586a0657d7f6cfd55d89508e15b95e79bd4010/benchmarks/datafusion_h2o_groupby_queries.py#L37

**Comment by 2010YOUY01** [comment]
take
