### ISSUE TITLE
Move available_parallelism() into utility function

### ISSUE THREAD

**Issue by Dandandan** [apache/datafusion#13591]
### Is your feature request related to a problem or challenge?

As noted by @comphead in  https://github.com/apache/datafusion/pull/13579#pullrequestreview-2465606280
We can move the repeated:
```
available_parallelism()
             .unwrap_or(NonZero::new(1).unwrap())
             .get()
```
into a seperate method.

### Describe the solution you'd like

Create a utility method and replace all calls to `std:thread::available_parallelism` with this new method.

**Comment by alan910127** [comment]
take
