### ISSUE TITLE
Support 1 or 3 arg in `generate_series()` UDTF

### ISSUE THREAD

**Issue by 2010YOUY01** [apache/datafusion#13615]
### Is your feature request related to a problem or challenge?

This is a follow up task for https://github.com/apache/datafusion/pull/13540
Now only 2-argument version is supported
```
> select * from generate_series(1,3);
+-------+
| value |
+-------+
| 1     |
| 2     |
| 3     |
+-------+
```

It can be extended with 'no start' and 'step' support:
```
D select * from generate_series(3);
┌─────────────────┐
│ generate_series │
│      int64      │
├─────────────────┤
│               0 │
│               1 │
│               2 │
│               3 │
└─────────────────┘
D select * from generate_series(3,1,-1);
┌─────────────────┐
│ generate_series │
│      int64      │
├─────────────────┤
│               3 │
│               2 │
│               1 │
└─────────────────┘
```

### Describe the solution you'd like

- Extend the UDTF for 1/3 argument support, following the behavior of `DuckDB` https://duckdb.org/docs/sql/functions/list#generate_series
- Add `sqllogictest`s

**Comment by buraksenn** [comment]
@jonathanc-n did you start working on this? I think this is a low-hanging issue and I can also try
