### ISSUE TITLE
Unnest relation can't accept a field from its join table

### ISSUE THREAD

**Issue by goldmedal** [apache/datafusion#13659]
### Describe the bug

There is a common usage of SQL to operate the nested data that is allowed by Postgres and DuckDB but DataFusion can't execute.
## Postgres
```
postgres=# create table unnest_test (c1 int[]);
CREATE TABLE
postgres=# insert into unnest_test values (ARRAY [1,2,3]);
INSERT 0 1
postgres=# select * from unnest_test u, unnest(u.c1);
   c1    | unnest 
---------+--------
 {1,2,3} |      1
 {1,2,3} |      2
 {1,2,3} |      3
(3 rows)
```

## DuckDB
```
D create table t1(c1 int[]);
D insert into t1 values ([1,2,3]);
D select * from t1, unnest(t1.c1);
┌───────────┬───────┐
│    c1     │  c1   │
│  int32[]  │ int32 │
├───────────┼───────┤
│ [1, 2, 3] │     1 │
│ [1, 2, 3] │     2 │
│ [1, 2, 3] │     3 │
└───────────┴───────┘
```

### To Reproduce

It can be reproduced by the following SQL (I just added them in the sqlogicitests `unnest.slt` and ran the test)
```
statement ok
create table t1(c1 array<int>);

statement ok
insert into t1 values ([1,2,3]);

query ?I
select * from t1, unnest(t1.c1)
----
[1, 2, 3] 1
[1, 2, 3] 2
[1, 2, 3] 3
```
Then, it will throw the error:
```
Running "unnest.slt"
External error: query failed: DataFusion error: Schema error: No field named t1.c1.
[SQL] select * from t1, unnest(t1.c1)
```

### Expected behavior

The test mentioned above should pass.

**Comment by jonahgao** [comment]
This should be a LATERAL JOIN, with the LATERAL keyword omitted. We do not support it yet.

As stated in the PostgreSQL [documentation](https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-LATERAL).
> Table functions appearing in FROM can also be preceded by the key word LATERAL, but for functions the key word is optional;

**Comment by rkrishn7** [comment]
Hello! I'm happy to take on the logical planning piece of this.

**Comment by alamb** [comment]
Postgres appears to simply plan this type of query as a NestedLoops join:

```sql
 Nested Loop  (cost=0.00..295.60 rows=13600 width=36)
   Output: u.c1, unnest.unnest
   ->  Seq Scan on public.unnest_test u  (cost=0.00..23.60 rows=1360 width=32)
         Output: u.c1
   ->  Function Scan on pg_catalog.unnest  (cost=0.00..0.10 rows=10 width=4)
         Output: unnest.unnest
         Function Call: unnest(u.c1)
```

🤔 

I think the postgres join operator re-evaluates the right input (`pg_catalog.unnest`) on each input row to the join which is how the lateral joins can refer to the outer query

The current DataFusion join operators don't run the input over and over again -- they normally run each input and then combine them (they don't restart inputs)

So in a query like
```sql
select * from t1, unnest(t1.c1)
```

I think we would need a (new) type of JoinExec that actually does run the outer query (aka `unnest(t1.c1)` for each input row of `t1`) 🤔

**Comment by alamb** [comment]
@goldmedal  also pointed out this may be related to supporting table functions that take columns as arguments (DataFusion only support taking constants at the moment)

**Comment by alamb** [comment]
After some more research, I think this ticket is now a dupe of https://github.com/apache/datafusion/issues/10048

**Comment by goldmedal** [comment]
> After some more research, I think this ticket is now a dupe of #10048

Agreed. The logical plan part has been finished. Let's close this issue and move to #10048.
