### ISSUE TITLE
Test DataFusion 44.0.0 with Comet

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13835]
### Is your feature request related to a problem or challenge?

- Part of #13661 

We are trying to make sure the upgrade experience for DataFusion is better and to do so we are hoping to improve the testsing of major downstream projects

For version 44.0.0 we would like to test with comet prior to release

### Describe the solution you'd like

I would like to create a PR to test DataFusion comet with a pre-released version of DataFusion (pinned to the main branch)

### Additional context

@andygrove has done this in https://github.com/apache/datafusion-comet/pull/1154

**Comment by alamb** [comment]
Testing looks good from what I can tell ✅

**Comment by andygrove** [comment]
Reopening ... I upgraded to latest and disabled default features, enabled our miri checks again but they are still failing.

**Comment by andygrove** [comment]
```
error: unsupported operation: can't call foreign function `rust_psm_stack_pointer` on OS `linux`
    --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/psm-0.1.24/src/lib.rs:319:14
     |
319  |     unsafe { rust_psm_stack_pointer() }
     |              ^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function `rust_psm_stack_pointer` on OS `linux`
     ```

**Comment by alamb** [comment]
I found another issue when testing today:
- https://github.com/apache/datafusion/issues/13898

**Comment by alamb** [comment]
Looks like we are good to go now: https://github.com/apache/datafusion-comet/pull/1154

<img width="977" alt="Screenshot 2024-12-24 at 6 55 42 PM" src="https://github.com/user-attachments/assets/8854bf3f-f1cb-45f2-9081-132ef51f27ed" />

I am claiming success (again) 🤞
