### ISSUE TITLE
Consolidate Example: simplify_udwf_expression.rs into advanced_udwf.rs #13842

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13843]
### Is your feature request related to a problem or challenge?

- Part of https://github.com/apache/datafusion/issues/11172

The large number of small examples in DataFusion leads to multiple problems:
- Unnecessarily large amounts of temporary disk space (each example binary takes 100+ MB)
- Larger `cargo t` time (each binary must be linked / created)
- Makes it harder to find the relevant examples

Thus I think the fewer examples we have the 
1. faster our dev experience will be 
2. easier it will be to find the relevant examples

### Describe the solution you'd like

- Consolidate the contents of the window function example [simplify_udwf_expression](https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/simplify_udwf_expression.rs)
- Into [advanced_udwf.rs](https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/advanced_udwf.rs)

Then update the readme page: 
- https://github.com/apache/datafusion/blob/main/datafusion-examples/README.md

### Additional context

I think this is a good first issue as the task is straightforward and doesn't require deep understanding of the DataFusion codebase

**Comment by cj-zhukov** [comment]
I'd like to take this if nobody is working on it

**Comment by xarus01** [comment]
take
