### ISSUE TITLE
Consolidate Example: dataframe_output.rs into dataframe.rs

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13844]
### Is your feature request related to a problem or challenge?

- Part of https://github.com/apache/datafusion/issues/11172

The large number of small examples in DataFusion leads to multiple problems:
- Unnecessarily large amounts of temporary disk space (each example binary takes 100+ MB)
- Larger `cargo t` time (each binary must be linked / created)
- Makes it harder to find the relevant examples

Thus I think the fewer examples we have the 
1. faster our dev experience will be 
2. easier it will be to find the relevant examples

### Describe the solution you'd like

- Consolidate the contents of https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/dataframe_output.rs
- Into https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/dataframe.rs

Then update the readme page: 
- https://github.com/apache/datafusion/blob/main/datafusion-examples/README.md

### Additional context

I think this is a good first issue as the task is straightforward and doesn't require deep understanding of the DataFusion codebase

**Comment by zhuqi-lucas** [comment]
take

**Comment by alamb** [comment]
Thank you @zhuqi-lucas 🙏
