### ISSUE TITLE
Consolidate Example: simplify_udaf_expression.rs into advanced_udaf.rs

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13842]
### Is your feature request related to a problem or challenge?

- Part of https://github.com/apache/datafusion/issues/11172

The large number of small examples in DataFusion leads to multiple problems:
- Unnecessarily large amounts of temporary disk space (each example binary takes 100+ MB)
- Larger `cargo t` time (each binary must be linked / created)
- Makes it harder to find the relevant examples

Thus I think the fewer examples we have the 
1. faster our dev experience will be 
2. easier it will be to find the relevant examples

### Describe the solution you'd like

- Consolidate the contents of  [simplify_udaf_expression](https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/simplify_udaf_expression.rs)
- Into [advanced_udaf.rs](https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/advanced_udaf.rs)

Then update the readme page: 
- https://github.com/apache/datafusion/blob/main/datafusion-examples/README.md

### Additional context

I think this is a good first issue as the task is straightforward and doesn't require deep understanding of the DataFusion codebase

**Comment by takaebato** [comment]
I'll work on this!

**Comment by takaebato** [comment]
take

**Comment by alamb** [comment]
Thank you @takaebato 🙏

**Comment by takaebato** [comment]
@alamb 

Sorry for the delay! I have a quick question.
I’m not too sure about this, but should the return type of `AggregateFunctionSimplification` perhaps be `Result<ExprSimplifyResult>`?

Currently, it looks like there’s no way to skip simplification, as it always returns a simplified `Expr` (or Err). 
The simplify method can return an `Option`, but the decision to simplify seems to rely on information passed to `AggregateFunctionSimplification`, so would it be better if this method can choose whether or not to simplify?

**Comment by alamb** [comment]
> @alamb
> 
> Sorry for the delay🙏 But I have a quick question! I’m not too sure about this, but should the return type of `AggregateFunctionSimplification` perhaps be `Result<ExprSimplifyResult>`(or a similar enum that can indicate whether or not simplification occurred)?
> 
> Currently, it doesn’t seem possible to skip simplification, as it always returns a simplified `Expr` (or Err). The `simplify` method can return an `Option`, but the decision to simplify seems to rely on information passed to `AggregateFunctionSimplification`, so might it be better if this method can choose whether or not to simplify..?

The rationale for returning ExprSimplifyResult is so that the argument doesn't have to be cloned -- aka to avoid coping the ownership of argument is passed to the function and there needs to be some way to get the original structuer back

**Comment by takaebato** [comment]
@alamb 

Thank you so much for the explanation!! 
(I realized that if we want to use the actual implementation conditionally, we can return `Ok(Expr::AggregateFunction(aggregate_function))`.)
