### ISSUE TITLE
Test DataFusion 44.0.0 with Sail

### ISSUE THREAD

**Issue by shehabgamin** [apache/datafusion#13855]
### Is your feature request related to a problem or challenge?

- Part of of https://github.com/apache/datafusion/issues/13661

We are trying to make sure the upgrade experience for DataFusion is better and to do so we are hoping to improve the testing of major downstream projects

For version 44.0.0 we would like to test with Sail prior to release.

### Describe the solution you'd like

I would like to create a PR to test DataFusion Sail with a pre-released version of DataFusion (pinned to the main branch)

### Additional context

https://github.com/lakehq/sail/pull/335

**Comment by Omega359** [comment]
> Smooth Sailing testing commit `5d563d9` from DataFusion `main` branch.
> 
> The following test reports run tests on the PR branch and compares them against the tests from the Sail `main` branch:
> 
>     * [DataFusion 44.0.0 Pre-Release Testing lakehq/sail#335 (comment)](https://github.com/lakehq/sail/pull/335#issuecomment-2556353768)
> 
>     * [DataFusion 44.0.0 Pre-Release Testing lakehq/sail#335 (comment)](https://github.com/lakehq/sail/pull/335#issuecomment-2556416669)

After a brief review of the errors I suspect there may be something up with lists and structs but I would have to see the actual logic being tested to know for certain. Many of the errors are expected - functions not existing, etc.

**Comment by alamb** [comment]
> After a brief review of the errors I suspect there may be something up with lists and structs but I would have to see the actual logic being tested to know for certain. Many of the errors are expected - functions not existing, etc.

I feel like we have had several bugs / issues with structs / lists the last few releases so it would be amazing if we could figure out what is going on before the release. @shehabgamin is this something you can help with?

**Comment by alamb** [comment]
> This leads me to believe that any issues with lists and/or structs would likely be preexisting. I will take a close look at all of the errors, but, with that in mind, should we scope the issues into a separate GitHub issue if we do find errors? Also @Omega359, let me know if any errors in particular caught your eye.

That would make sense. Glad to hear the errors aren't new

**Comment by alamb** [comment]
Thank you very much @shehabgamin  for the help and assistance. I love it when incentives are aligned like this

**Comment by Omega359** [comment]
> Also, @Omega359 please let me know regarding our earlier discussion (linked below). I haven't taken a look yet because of the holidays, but will create a new issue if I discover anything. [#13855 (comment)](https://github.com/apache/datafusion/issues/13855#issuecomment-2557868273)

Thanks for reminding me about this - I've added it to my TODO list and I'll do my best to try and get to this in the next week.
