### ISSUE TITLE
SELECT * FROM subquery ignores ordering

### ISSUE THREAD

**Issue by TheBuilderJR** [apache/datafusion#13904]
### Describe the bug

Generally for almost all other sql query engines I expect

```
SELECT * FROM (
  SOME_ORDERED_SUB_QUERY_HERE
) AS query LIMIT 10000
```

to maintain the same order as the subquery, eg.

```
SELECT * FROM (
SELECT
  session.access_token,
  COUNT(1) as c
FROM quizchat_chats
GROUP BY session.access_token
ORDER BY c
) AS query LIMIT 10000
```

But in datafusion, it doesn't! It seemingly returns a randomly ordered list.

### To Reproduce

Run a SELECT * FROM over an ordered subquery

### Expected behavior

ordering is preserved

**Comment by 2010YOUY01** [comment]
I think SQL standard doesn't enforce such ordering, but it's possible most engines implemented it as ordered

**Comment by jonahgao** [comment]
A subquery is a derived table/relation. A relation is unordered, and you can't rely on its tuples being ordered; different database implementations or queries have different behaviors. In #12003, DataFusion intentionally optimized away unnecessary ordering in subqueries.

Some discussions of other databases:
- [SQLite: Any way to preserve subquery result order in outer query](https://sqlite.org/forum/info/2d5a6e83bb501dffea1207cce3ae09292d1effd656c09471dce1130e9dcf83e6)
- [MariaDB FAQ: Why is ORDER BY in a FROM Subquery Ignored?](https://mariadb.com/kb/en/why-is-order-by-in-a-from-subquery-ignored/)

**Comment by ozankabak** [comment]
@jonahgao is correct -- this is not a bug. If the top-level query doesn't specify an ordering, the engine is free to optimize the subquery ordering away.

**Comment by comphead** [comment]
@TheBuilderJR thanks for opening the issue and please let us know if anything still needed. as @ozankabak correctly mentioned the if there is no top level ordering the engine cannot guarantee the final order. 

The LIMIT clause gets evaluated after the ORDER clause, so if you rewrite your query 

```
SELECT * FROM (
SELECT
  session.access_token,
  COUNT(1) as c
FROM quizchat_chats
GROUP BY session.access_token
) AS query ORDER BY c LIMIT 10000
``` it should work
