### ISSUE TITLE
Consolidate Example: dataframe_subquery.rs into dataframe.rs

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#13911]
### Is your feature request related to a problem or challenge?

- Part of https://github.com/apache/datafusion/issues/11172

The large number of small examples in DataFusion leads to multiple problems:
- Makes it harder to find the relevant examples
- Unnecessarily large amounts of disk space on a full build (each example binary takes 100+ MB)
- Larger `cargo t` time (each binary must be linked / created)

Thus I think the fewer examples we have the 
1. easier it will be to find the relevant examples
2. faster our dev experience will be 

### Describe the solution you'd like

- Consolidate the contents of https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/dataframe_subquery.rs
- Into https://github.com/apache/datafusion/blob/main/datafusion-examples/examples/dataframe.rs

Then update the readme page: 
- https://github.com/apache/datafusion/blob/main/datafusion-examples/README.md

### Additional context

I think this is a good first issue as the task is straightforward and doesn't require deep understanding of the DataFusion codebase

**Comment by zjregee** [comment]
take.
