### ISSUE TITLE
The Eq method in HashAggregate takes up a lot of time, how to optimize it

### ISSUE THREAD

**Issue by ic4y** [apache/datafusion#1456]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Related issue  #1246 #956

Part of the high-cardinality aggregation performance problem can be solved in arrow2. But currently `eq_array` still takes a lot of time.

https://github.com/apache/arrow-datafusion/blob/6478a33c705fc7fdf28ec141685b447a6619ec08/datafusion/src/physical_plan/hash_aggregate.rs#L375-L389

View in pprof
![image](https://user-images.githubusercontent.com/83933160/146330115-28a6728d-22d1-40d9-bc2a-130819a22243.png)
![image](https://user-images.githubusercontent.com/83933160/146330722-40f879a4-efb5-4166-9c3b-d135d0c71bfb.png)

**Describe the solution you'd like**
Optimize the performance of eq_array

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
I think `eq_array` is a symptom, rather than the root cause

The eq_array is necessary in the current hash aggregate  implementation to detect hash collisions:

```
                                            ┌──────────────────────────────────────┐
                ┌─────────┐                 │Bucket                                │
                │         │                 │(                                     │
                │HashTable│        ┌───────▶│ grp_key1: ScalarValue                │
                │         │────────┘        │ grp_key2: ScalarValue                │
                │         │                 │)                                     │
                │         │                 └──────────────────────────────────────┘
                └─────────┘                                                         
                                                                                    
                                                                                    
                                                                                    
                                                                                    
  ┌─────────────┬─────────────┐                                                     
  │Group Column │Group Column │                                                     
  │      A      │      B      │             Step 1:  hash(grp_key1, grp_key2) is    
  └─────────────┴─────────────┘                     computed (vectorized)           
        ...           ...                                                           
  ┌─────────────┬─────────────┐             Step 2: bucket for that hash value is   
  │  grp_key1   │  grp_key2   │                           obtained                  
  └─────────────┴─────────────┘                                                     
        ...           ...                Step 3: Validate that the values stored in 
                                          the bucket are the same as the input key  
                                           (aka that there are no hash collisions)  
                                                                                    
                                                                                    
                                                                                    
                                                                                    
                                                                                    
        eq_array is used for step 3                                                 
                                                                                    
```

I am pretty sure this code is correct, though since it is general purpose (works for all types) there is non trivial dispatch overhead

If you are trying to speed up a distinct aggregate calculation I suggest you look into special casing group keys which are native types and which can be packed into fixed length byte arrays (so they can be compared using mem comparisons rather than dispatching on each column) 

Another way of saying this is "don't try and remove `eq_array` but instead try to remove the use of `Scalar` entirely

**Comment by Dandandan** [comment]
I think this issue is out of date. Please reopen if thus is not the case

**Comment by alamb** [comment]
In case anyone is interested, we rewrote the hash aggregation code several times to avoid this overhead (arrow2 was not necessray). Here is a blog that describes some of the techniques: https://www.influxdata.com/blog/aggregating-millions-groups-fast-apache-arrow-datafusion
