### ISSUE TITLE
  Add optional rust features for functions in library to keep dependencies down

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#146]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11214

As we expand the numbers of functions available in DataFusion, DataFusion will likely pick up additional third-party dependencies. In general, I think it would be a nice feature for DataFusion to  allow users more fine grained control over the features that they wanted to use (and pay the subsequently higher compilation / link time (and binary size) cost. At the moment, with a single codebase and no feature flags, everyone's compile time and binary size will increase even if they don't use a specific set of features. 

It seems to me like we might want to start offering a way to keep the number of required dependencies of DataFusion down. For example, in the case of https://github.com/apache/arrow/pull/9139, we could potentially put the use of crypto functions behind a feature flag. Users of DataFusion could then pick a subset of features  like "core" and "func-datetime" and "func-crypto" to have more control over the dependencies they pulled in

**Comment by drauschenbach** [comment]
This issue looks obsolete. Use of feature flags such as `avro` are now used to control dependency scope.

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
