### ISSUE TITLE
Remove call_ip in the SchedulerServer

### ISSUE THREAD

**Issue by yahoNanJing** [apache/datafusion#1558]
**Describe the bug**

Currently there's a field in the SchedulerServer for recording caller ip which sends requests to the scheduler. However, for one scheduler, there will be multiple clients. Concurrency issue may occur. It's not a good way for record the requester info in a global field. Therefore, it's better to remove it from the SchedulerServer.

We can get the requester ip from the hyper info and set it to the tonic info. Then in each tonic-based grpc interface, we can get the  the requester ip from the **Request**.

**Comment by drauschenbach** [comment]
Resolved elsewhere. See #1559.

**Comment by alamb** [comment]
Thanks @drauschenbach
