### ISSUE TITLE
Error `Unexpected accumulator state List([NULL])` in `COUNT(distinct ..)` query

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#1623]
**Describe the bug**
A query returns this error:

```
ArrowError(ExternalError(Internal("Unexpected accumulator state List([NULL])")))
```

**To Reproduce**
Download and extract [data.zip](https://github.com/apache/arrow-datafusion/files/7908494/data.zip)

```shell
cargo run --bin datafusion-cli
    Finished dev [unoptimized + debuginfo] target(s) in 0.93s
     Running `target/debug/datafusion-cli`
DataFusion CLI v5.1.0

❯ create external table stops stored as parquet location '2021-11.parquet';
0 rows in set. Query took 0.010 seconds.
❯ select count(*), count(distinct stop_name), trip_tid  from stops group by trip_tid limit 10;
ArrowError(ExternalError(Internal("Unexpected accumulator state List([NULL])")))
```
**Expected behavior**
A result

**Additional context**
@matthewmturner  and @jhorstmann  helped me discover this as part of the Rust syncup today 🤣

**Comment by HaoYang670** [comment]
It seems like there is a `List(None, _)` in the `states`:
```rust

        let col_values = states
            .iter()
            .map(|state| match state {
                ScalarValue::List(Some(values), _) => Ok(values),
                _ => Err(DataFusionError::Internal(format!(
                    "Unexpected accumulator state {:?}",
                    state
                ))),
            })
            .collect::<Result<Vec<_>>>()?;
```

https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/expressions/distinct_expressions.rs#L148-L157

**Comment by HaoYang670** [comment]
This query works:

**Comment by alamb** [comment]
Perhaps the accumulator just needs to be able to handle "null" (aka seeing no values)

**Comment by HaoYang670** [comment]
I am curious about why 
```sql
❯ select count(distinct stop_name), trip_tid from stops group by trip_tid limit 10;
```
works,
but
```sql
❯ select count(*), count(distinct stop_name), trip_tid  from stops group by trip_tid limit 10;
```
does not work.

**Comment by alamb** [comment]
What do the plans look like if you do `EXPLAIN select count(distinct stop_name), trip_tid from stops group by trip_tid limit 10;`? Perhaps the optimizer is doing something non trivial to the plan

**Comment by alamb** [comment]
`EXPLAIN VERBOSE select count(distinct stop_name), trip_tid from stops group by trip_tid limit 10;` will tell you even more

**Comment by alamb** [comment]
> This is a little amazing for me. Without count(*), datafusion will replace count distinct by firstly doing hash aggregate on stop_name (generate alias1) and then count directly.

That is a cool optimization (it is in https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/optimizer/single_distinct_to_groupby.rs)  contributed by @ic4y

**Comment by HaoYang670** [comment]
I also test the sql: (removing `group by trip_tid`)
```sql
select count(*), count(distinct stop_name) 
from stops 
limit 3
```
and there is no error appearing.

After debugging, I find that the function `DistinctCountAccumulator.merge_batch` is called from `group_aggregate_batch` when the sql containing `group by  trip_tid` and is called from `aggregate_batch` when removing `group by trip_tid`. 
So I guess the bug is in the function `group_aggregate_batch` in `hash_aggregate.rs`, but I am not sure.

**Comment by findepi** [comment]
this issue doesn't seem reproducible on current main.  @alamb close?
