### ISSUE TITLE
CoalesceBatchesStream poll_next_inner function bug

### ISSUE THREAD

**Issue by JasonLi-cn** [apache/datafusion#1879]
**Describe the bug**
SQL: select * from table where col1 = 'datafusion' limit 10;
Some files are still being read after the result is returned。

Because：
[https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/coalesce_batches.rs](url)
CoalesceBatchesStream poll_next_inner function has a loop logic, when sync table scan stream don't return Poll::Pending(eg. Parquet), when CoalesceBatchesStream's parent abort him, still can't quit loop, util table scan stream return Poll::Ready(None).
Also, spawn_execution function in common.rs has this problem.

**To Reproduce**

**Expected behavior**
End stream when has sync table scan in a friendly way.

**Additional context**

**Comment by alamb** [comment]
I think this may have been fixed by https://github.com/apache/datafusion/pull/11652 from @ozankabak  and the synnada team to push limit into the `CoalesceBatchesStream`

**Comment by ozankabak** [comment]
I think so too 🚀

**Comment by alamb** [comment]
Closing this one -- please feel free to reopen it @JasonLi-cn  if you think it is still an issue
