### ISSUE TITLE
  Review the contract between DataFusion and Arrow

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#196]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-12284

I am creating this issue based on the discussion at the sync call earlier today.

Apparently DataFusion is not only using the high-level Arrow API but is also accessing Arrow internals directly and this would be one challenge in moving to a majorly refactored Arrow implementation.

Perhaps we need to review what the public Arrow API should be and which APIs DataFusion should or should not be using.

**Comment by drauschenbach** [comment]
It's worth considering whether this issue is obsolete, now that the project depends on an external `arrow` crate.

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
