### ISSUE TITLE
Presentation RFC for DataBricks conference: DataFusion and Arrow

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#2323]
# Overview
@Dandandan and I are working on a presentation about DataFusion at conference at the end of June 2022. In the spirit of open collaboration, we would like to solicit community feedback / crowd source some of the content prior to doing so. 

I hope / expect some of the content from this talk (like "why use datafusion") may make it back into the main https://arrow.apache.org/datafusion/ documentation

Also, part of this presentation is about how DataFusion is used by downstream projects and we want to ensure our presentation is
1. Technically Accurate
2. Allowed by the downstream project to mention them and their use of DataFusion

Since most of the projects we have listed are open source, I don't think it will be a problem, but before we present I want an explicit signoff from people involved in the projects.

As an aside, it is very cool to see what others are doing with DataFusion

# Talk Details:
Conference details https://databricks.com/dataaisummit/north-america-2022/agenda 

https://databricks.com/dataaisummit/north-america-2022/agenda/?sessionid=1798

Talk Description: 

**DATA ENGINEERING**
DataFusion and Arrow: Supercharge Your Data Analytical Tool with a Rusty Query Engine
Learn how Rust, the Apache Arrow project, and the Data Fusion Query Engine are increasingly being used to accelerate the creation of modern data stacks.

Presentation: https://docs.google.com/presentation/d/1q1bPibvu64k2b7LPi7Yyb0k3gA1BiUYiUbEklqW1Ckc

And so with that, please leave us comments !

**Comment by iravid** [comment]
Thanks for including Coralogix on the slides :-) we'd be happy for that to stay on; would it be alright if we provide the text for the Overview and Use of Datafusion sections?

**Comment by Dandandan** [comment]
> Thanks for including Coralogix on the slides :-) we'd be happy for that to stay on; would it be alright if we provide the text for the Overview and Use of Datafusion sections?

Yeah, that would be great 👏

**Comment by andygrove** [comment]
@alamb It looks like these two presentations linked to from the main presentation are not publicly accessible:

- https://docs.google.com/presentation/d/1owNlmpNpC2-eBd-jEYRCt0L8_sW4PWYx70gqnFC0twM/edit?usp=sharing
- https://docs.google.com/presentation/d/1lXsYsPjeowey7H9wIOQUnUjsCo_282Zv/edit#slide=id.p1

**Comment by Dandandan** [comment]
@yjshen (blaze-rs) @houqp (roapi, delta-lake) @jonmmease (VegaFusion) @gangliao (Flock) @paveltiunov/@ovr (Cube.js) @andygrove (dask-sql, Ballista), @rdettai (loudfuse Buzz)

As I think (one of) the main authors of those projects, would you be able to review or contribute the content of your project, or maybe help us finding someone who can?

**Comment by alamb** [comment]
> @alamb It looks like these two presentations linked to from the main presentation are not publicly accessible:

@andygrove  thank you for pointing that out -- given how the permissions are setup I can't make them publically accessable  iin general but I can share them explicitly with inviduals 

They are also on slideshare https://www.slideshare.net/AndrewLamb32/presentations

https://www.slideshare.net/AndrewLamb32/a-rusty-introduction-to-apache-arrow-and-how-it-applies-to-a-time-series-database

https://www.slideshare.net/AndrewLamb32/2021-0420-apache-arrow-and-its-impact-on-the-database-industrypptx

https://www.slideshare.net/AndrewLamb32/2021-1013-i-ox-query-processing

**Comment by jychen7** [comment]
nice, great presentation
