### ISSUE TITLE
[Question] how to add expr inline

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/datafusion#2330]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Hi,  I have met some problems.  I want to implement an expr `inline` which 

inline(expr) - Explodes an array of structs into a table.:
```
> SELECT inline(array(struct(1, 'a'), struct(2, 'b')));
 1  a
 2  b
```

 i have two solutions:
1. add inline in ScalarFunction , But  i found 
```
pub type ScalarFunctionImplementation =
    Arc<dyn Fn(&[ColumnarValue]) -> Result<ColumnarValue> + Send + Sync>;
```

In this case, I can not produce more than two columns by using  ScalarFunction, am i right ?

2. implement a Expr like `Wildcard`
I think this is not a good way 😂

Could anyone give me some advice ?

in spark i found, is there something similar?
```
/**
 * Explodes an array of structs into a table.
 */
// scalastyle:off line.size.limit line.contains.tab
@ExpressionDescription(
  usage = "_FUNC_(expr) - Explodes an array of structs into a table. Uses column names col1, col2, etc. by default unless specified otherwise.",
  examples = """
    Examples:
      > SELECT _FUNC_(array(struct(1, 'a'), struct(2, 'b')));
       1	a
       2	b
  """,
  since = "2.0.0",
  group = "generator_funcs")
// scalastyle:on line.size.limit line.contains.tab
case class Inline(child: Expression) extends UnaryExpression with CollectionGenerator {
  override val inline: Boolean = true
  override val position: Boolean = false

  override def checkInputDataTypes(): TypeCheckResult = child.dataType match {
    case ArrayType(st: StructType, _) =>
      TypeCheckResult.TypeCheckSuccess
    case _ =>
      TypeCheckResult.TypeCheckFailure(
        s"input to function $prettyName should be array of struct type, " +
          s"not ${child.dataType.catalogString}")
  }

  override def elementSchema: StructType = child.dataType match {
    case ArrayType(st: StructType, _) => st
  }

  override def collectionType: DataType = child.dataType

  private lazy val numFields = elementSchema.fields.length

  override def eval(input: InternalRow): TraversableOnce[InternalRow] = {
    val inputArray = child.eval(input).asInstanceOf[ArrayData]
    if (inputArray == null) {
      Nil
    } else {
      for (i <- 0 until inputArray.numElements())
        yield inputArray.getStruct(i, numFields)
    }
  }

  override protected def doGenCode(ctx: CodegenContext, ev: ExprCode): ExprCode = {
    child.genCode(ctx)
  }

  override protected def withNewChildInternal(newChild: Expression): Inline = copy(child = newChild)
}
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andygrove** [comment]
I think we will need to introduce a new type of function to cover `inline` since it is not a scalar function.

I don't have a good name for it yet but I think we need something like this?

``` rust
pub type MultiColumnProducingFunctionImplementation =
    Arc<dyn Fn(&[ColumnarValue]) -> Result<Vec<ColumnarValue>> + Send + Sync>;
```

**Comment by Ted-Jiang** [comment]
> I think we will need to introduce a new type of function to cover `inline` since it is not a scalar function.
> 
> I don't have a good name for it yet but I think we need something like this?
> 
> ```rust
> pub type MultiColumnProducingFunctionImplementation =
>     Arc<dyn Fn(&[ColumnarValue]) -> Result<Vec<ColumnarValue>> + Send + Sync>;
> ```

Thanks ❤️ @andygrove, I agree we need func return `Vec<ColumnarValue` i will working on this

**Comment by Ted-Jiang** [comment]
@andygrove Another question, if add TableFunction like ScalarFunction
```rust
 /// Represents the call of a built-in scalar function with a set of arguments.
    ScalarFunction {
        /// The function
        fun: built_in_function::BuiltinScalarFunction,
        /// List of expressions to feed to the functions as arguments
        args: Vec<Expr>,
    },
    TableFunction {
        /// The function
        fun: built_in_function::BuiltinTableFunction,
        /// List of expressions to feed to the functions as arguments
        args: Vec<Expr>,
    },
```

 if we treat it as a `Expr` , we need change it to `PhysicalExpr` but 
``` rust
/// Evaluate an expression against a RecordBatch
    fn evaluate(&self, batch: &RecordBatch) -> Result<ColumnarValue>;
```

```rust
pub enum ColumnarValue {
    /// Array of values
    Array(ArrayRef),
    /// A single value
    Scalar(ScalarValue),
}
```
cause of it return ColumnarValue, we can not return result as a table, am i right?

Should i implement a `TablePhysicalExpr`
using 
```rust
  fn evaluate(&self, batch: &RecordBatch) -> Result<Vec<ColumnarValue>>;
```

**Comment by gandronchik** [comment]
@andygrove @Ted-Jiang I already implemented it. Today or tomorrow I will create PR. Thanks

**Comment by Ted-Jiang** [comment]
@gandronchik Thanks a lot !❤️

**Comment by alamb** [comment]
As @gandronchik  implies, this type of `expr` that yields a table is typically called a `TableFunction` -- he has an implementation at https://github.com/apache/arrow-datafusion/pull/2177

**Comment by alamb** [comment]
I think the `unnest` implementation that is now built in to DataFusion provides an example of how to do this.

Depending on the exact semantics required, it would likely need its own function rewrite and special operator.

Closing this ticket down now. Let's open a new one if we want to continue the discussion
