### ISSUE TITLE
User guide should have a reference listing all the built-in functions

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#2872]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As a user of DataFusion, how do I know what functions are available?

**Describe the solution you'd like**
User guide should have a reference listing all the built-in functions.

They are documented in crates.io at https://docs.rs/datafusion-expr/9.0.0/datafusion_expr/expr_fn/index.html so maybe we can link to that for now but it would be better if we could generate the same information directly into the user guide.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by alamb** [comment]
I think we now have this: https://datafusion.apache.org/user-guide/sql/scalar_functions.html, https://datafusion.apache.org/user-guide/sql/aggregate_functions.html , https://datafusion.apache.org/user-guide/sql/window_functions.html
