### ISSUE TITLE
filter_push_down internal error

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#3416]
**Describe the bug**
I have queries failing with:

```
Error: Internal("Optimizer rule 'filter_push_down' failed due to unexpected error: Internal error: on_lr_is_preserved cannot be appplied to SEMI/ANTI-JOIN nodes. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker")
```

**To Reproduce**
I do not have a repro case yet and cannot share the query

**Expected behavior**
Should not hit internal errors

**Additional context**
None

**Comment by liukun4515** [comment]
is it related with this issue https://github.com/apache/arrow-datafusion/issues/3421?
