### ISSUE TITLE
Move filter_push_down::split_members to be reused outside of DataFusion

### ISSUE THREAD

**Issue by NGA-TRAN** [apache/datafusion#382]
The [filter_push_down::split_members](https://github.com/apache/arrow-datafusion/blob/14f1eebef068a9e65f556ed74d2b6d98376c97f4/datafusion/src/optimizer/filter_push_down.rs#L220) function is being copied and used outside in [IOx](https://github.com/influxdata/influxdb_iox). If this function is moved to optimizer/utils, it will be reused outside DataFusion

**Comment by alamb** [comment]
Maybe it could be a function on `Expr` itself

**Comment by drauschenbach** [comment]
This issue seems obsolete, given that no `split_members` function exists anymore, so IoX must have worked around that.

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
