### ISSUE TITLE
Enhance SortMergeJoin to support Join filters(non-equal Join conditions)

### ISSUE THREAD

**Issue by mingmwang** [apache/datafusion#4364]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DDtKey** [comment]
Hi @alamb, 

Just wanted actualize this issue and enrich with some information.

Currently Join filters are disabled for `SortMergeJoin` with [TODO](https://github.com/apache/arrow-datafusion/blob/68061aaccc2b069eb68f20a31202bd1f884ed752/datafusion/core/src/physical_plan/planner.rs#L1065-L1066) and it produces error in such case.

So if I will disable `prefer_hash_join` config, it will lead to errors for such queries.

**Comment by alamb** [comment]
Thanks for the report @DDtKey  -- it would likely help to write some tests (maybe sqllogictest style) that showed the errors (and leave a comment pointing back at this ticket).

**Comment by Dandandan** [comment]
AFAIK closed by https://github.com/apache/datafusion/pull/9080
