### ISSUE TITLE
[Ballista] Improve task and job metadata

### ISSUE THREAD

**Issue by edrevo** [apache/datafusion#472]
The task and job status we save in the scheduler state is currently lacking. See:

https://github.com/apache/arrow-datafusion/blob/16011120a1b73798049c5be49f9548b00f8a0a00/ballista/rust/core/proto/ballista.proto#L669-L680

And

https://github.com/apache/arrow-datafusion/blob/16011120a1b73798049c5be49f9548b00f8a0a00/ballista/rust/core/proto/ballista.proto#L614-L624

The job status should include:

- Start time for the job (the moment it was queued)
- Finish time for the job (for the completed state)
- Number of pending/running/completed/failed tasks and stages (for the running state)

The task status should include:

- Start time for the task
- Finish time for the task (for the completed state)

**Comment by edrevo** [comment]
cc @pradomota. I'm opening this one in case you want to take a stab at it 😉 We can do pair programming if you want.

**Comment by msathis** [comment]
This will be great addition. We can expose this information to the UI as well.

**Comment by drauschenbach** [comment]
This issue should be closed now that Ballista no longer resides in this git repo.

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
