### ISSUE TITLE
[Python] Raise DataFusionError instead of plain Exceptions

### ISSUE THREAD

**Issue by kszucs** [apache/datafusion#494]
**Describe the bug**
The library should raise a more specific exception. 

**To Reproduce**
See test case https://github.com/apache/arrow-datafusion/pull/493/files#diff-833d46d402a40f517bfea151178579e3ec772a0da4ce098c0b89867251e6113fR33

**Comment by jorgecarleitao** [comment]
I think that we using them already: https://github.com/apache/arrow-datafusion/blob/master/python/src/errors.rs#L25

I think that we just not test them.

**Comment by alamb** [comment]
Seems like this was solved a while ago -- please reopen / file a new ticket if there is additional work to do.  Thanks @drauschenbach for flagging this.
