### ISSUE TITLE
`LogicalPlan.schema()` returns incorrect schema for `CreateMemoryTable` and `CreateView`

### ISSUE THREAD

**Issue by charlesbluca** [apache/datafusion#5004]
**Describe the bug**
For `LogicalPlan::CreateMemoryTable` and `CreateView`, `schema()` returns the schema of the input plan, rather than the schema of the newly created table/view:

https://github.com/apache/arrow-datafusion/blob/92d0a054c23e5fba91718db32ccd933ce86dd2b6/datafusion/expr/src/logical_plan/plan.rs#L155-L156

**Expected behavior**
I would expect `LogicalPlan.schema()` to return the schema of the newly created table or view.

**Additional context**
This came up in discussion around fetching the schema of a created memory table or view in https://github.com/dask-contrib/dask-sql/pull/854#discussion_r1081723309

**Comment by mslapek** [comment]
I've run `CREATE VIEW` and `CREATE TABLE` with

```rust
let plan = ctx.state().create_logical_plan(sql).await?;

println!("plan={:?}\n\nschema={:?}", plan, plan.schema());
```

and the schema seems to be the **almost** correct -
i.e. fields represent the **new** table, not the **original** one.

Only qualifier of `DFField` is not set - is it the bug? 🐞

**Comment by alamb** [comment]
Let's claim this is not a bug for now. Please reopen, ideally with a reproducer showing the desired behavior, if we want to change the behavior
