### ISSUE TITLE
Support pruning on string columns using starts_with

### ISSUE THREAD

**Issue by nevi-me** [apache/datafusion#507]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

From looking at the pruning logic, it appears that we can prune inputs based on `col = 'string_value'`, but we can't prune on `col LIKE 'value%'`.

We should be able to support `LIKE` and `NOT LIKE`.

**Describe the solution you'd like**

Extend the pruning logic to generate a pruning filter for `LIKE` and `NOT LIKE`.

**Describe alternatives you've considered**

None

**Additional context**

Spark will push down a `LIKE` filter if it can be converted to a `starts_with`, normally by checking if the string doesn't start with `%`.

**Comment by adriangb** [comment]
Thanks for the idea. We are close to implementing this in #12978. It adds support for pushing down `like` but notably does _not_ add support for `starts_with` as that will be done in a followup PR.

**Comment by adriangb** [comment]
@alamb I think we should re-open this for `starts_with`.

**Comment by alamb** [comment]
Thanks @adriangb  -- I changed this ticket to refer to `LIKE` / `NOT LIKE` and I will file a follow on ticket for supporting starts_with

**Comment by alamb** [comment]
Filed the following ticket to support `starts_with`: 🎣 
- https://github.com/apache/datafusion/issues/14027

**Comment by adriangb** [comment]
I think we also need follow up tickets for:
- NOT LIKE
- Case insensitive matching

**Comment by alamb** [comment]
> I think we also need follow up tickets for:
> 
> * NOT LIKE
> * Case insensitive matching

Sounds good -- can you please file them (and the more hints you leave in the ticket the more likely it is for someone else to be able to do it)
