### ISSUE TITLE
Creating external the table with SQL with unbounded and ordered options

### ISSUE THREAD

**Issue by metesynnada** [apache/datafusion#5126]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

```sql
CREATE EXTERNAL TABLE t(c1 int) STORED AS CSV PARTITIONED BY (p1 int) LOCATION 'foo.csv'
```

is supported, however, we cannot inject unbounded and ordered information like other flags. A basic usage can be

```sql
CREATE EXTERNAL TABLE t(c1 int) STORED AS CSV ORDERED BY (p1 int) LOCATION 'foo.csv' UNBOUNDED
```
but, of course, I am open to better word selection. The problem is not limited to CSV, we need to support JSON and AVRO types also.

**Describe the solution you'd like**
The problem requires the `sqlparser` crate to be changed first. Then, we apply necessary flag declarations and logical plan changes here. 

**Describe alternatives you've considered**
NA

**Additional context**
Na

**Comment by alamb** [comment]
This might be a good feature to add as a custom DataFUsion parser extension -- i.e. you can follow the model of `CREATE EXTERNAL TABLE` which is not supported by  sqlparser but rather in DataFusion

**Comment by metesynnada** [comment]
Sure, thanks for the feedback. If no one owns the issue in a couple of weeks, we will start it.

**Comment by alamb** [comment]
I believe `WITH ORDER` and `UNBOUNDED` are now supported so we can close this ticket

Doc reference: https://datafusion.apache.org/user-guide/sql/ddl.html#create-external-table
