### ISSUE TITLE
`Compute error: Overflow happened` in `tpcds_logical_q58`

### ISSUE THREAD

**Issue by jackwener** [apache/datafusion#5396]
**Describe the bug**
after disable `skip_failed_rules`.

tpcds_logical_q58 failed in

'simplify_expressions' failed due to unexpected error: Arrow error: Compute error: Overflow happened on: 100 * 100000000000000000000000000000000000000"

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by jackwener** [comment]
I investigated it, I found bug in `ConstEvaluator`.

It will failed in `expr.rewrite(&mut const_evaluator)?`

**Comment by jackwener** [comment]
cc @HaoYang670 .
After we fix this problem, we can disable `skip_failed_rules `

**Comment by HaoYang670** [comment]
> After we fix this problem, we can disable skip_failed_rules
This is really a great news! Great works @jackwener.

**Comment by jackwener** [comment]
failed in `"CAST(Int64(100) AS Decimal128(38, 38))"`

`"ArrowError(ComputeError("Overflow happened on: 100 * 100000000000000000000000000000000000000"))"`

**Comment by viirya** [comment]
We've dealt with such issue in [#3690](https://github.com/apache/arrow-rs/pull/3690).

**Comment by tustvold** [comment]
> failed in expression "CAST(Int64(100) AS Decimal128(38, 38))"

This sounds like a type inference bug, as opposed to something related to the handling of decimal arithmetic. In particular where has this scale of 38 come from? Such a datatype cannot represent anything greater 1 and so the query is perfectly correct to bail out with an error.

The original schema has a precision of 2, as it represents a monetary quantity, and so ending up with a scale of 38 is extremely suspect...

**Comment by Jefffrey** [comment]
`skip_failed_rules` is now disabled by default by #6265

https://github.com/apache/datafusion/blob/19356b26f515149f96f9b6296975a77ac7260149/datafusion/common/src/config.rs#L546-L549

And `tpcds_logical_q58` is not ignored and runs successfully in test suite:

https://github.com/apache/datafusion/blob/19356b26f515149f96f9b6296975a77ac7260149/datafusion/core/tests/tpcds_planning.rs#L319-L322

Closing issue
