### ISSUE TITLE
Support parameter (`$1`) type inference for `LIKE` predicates

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#5617]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We are trying to run a query like this:

```sql
SELECT ... WHERE col LIKE $1
```

However the type inference logic in https://github.com/apache/arrow-datafusion/blob/0f6931caa6f8b48e116a8e77e989c404f31f3f8d/datafusion/sql/src/expr/mod.rs#L503

only handles `=` predicates

cc  @avantgardnerio 

**Describe the solution you'd like**
I would like the type inference logic to handle `LIKE`, `NOT LIKE`, `ILIKE` and `NOT ILIKE`

**Describe alternatives you've considered**

**Additional context**
Found while implementing FlightSQL (via parameterized queries) in IOx: https://github.com/influxdata/influxdb_iox/pull/7213

**Comment by alamb** [comment]
I found a workaround that works for https://github.com/influxdata/influxdb_iox/pull/7213

**Comment by Weijun-H** [comment]
What is the outcome of the SQL query` SELECT ... WHERE col LIKE $1`? 🤔
