### ISSUE TITLE
switch to using AsyncBencher for datafusion benches?

### ISSUE THREAD

**Issue by jimexist** [apache/datafusion#563]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

https://docs.rs/criterion/0.3.4/criterion/struct.AsyncBencher.html

**Describe alternatives you've considered**

**Additional context**

**Comment by drauschenbach** [comment]
I suggest closing this issue because the questions were not populated, so I'm not clear what the intended benefit would be.

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
