### ISSUE TITLE
Support Grouping functions with Group By CUBE/ROLLUP/GROUPING SETS

### ISSUE THREAD

**Issue by mingmwang** [apache/datafusion#5647]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

PostgreSQL, SparkSQL and Oracle support using `GROUPING` functions to specify the null is from subtotal or from original
data.
https://www.postgresql.org/docs/15/functions-aggregate.html#FUNCTIONS-HYPOTHETICAL-TABLE

Databricks SparkSQL
https://docs.databricks.com/sql/language-manual/functions/grouping.html

Oracle
https://oracle-base.com/articles/misc/rollup-cube-grouping-functions-and-grouping-sets#grouping

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mingmwang** [comment]
I'm working on it now.

**Comment by l1t1** [comment]
where is the document of these features?

**Comment by bgjackma** [comment]
take

**Comment by bgjackma** [comment]
I don't think this works as a aggregate function in the physical plan. It depends on the grouping rather than the data, so the current abstraction doesn't have access to the necessary information.

I think this case (along with GROUPING_ID, any others?) will need special handling in [`GroupHashedAggregateStream`](https://github.com/apache/datafusion/blob/aeca7ea99940401573eb14601c74316279bbdae5/datafusion/physical-plan/src/aggregates/row_hash.rs#L336).

**Comment by alamb** [comment]
Note there is a PR with a proposed implementation from @JasonLi-cn  in https://github.com/apache/datafusion/pull/10208

**Comment by bgjackma** [comment]
Thanks for the heads up, that's helpful however I think I have a slightly nicer solution that doesn't force changes on existing accumulators.

**Comment by eejbyfeldt** [comment]
Note that @mingmwang (the author of this ticket) had an alternative approach here: https://github.com/apache/datafusion/pull/5749 but it seems like it was never pushed above the finish line. 

What is good with that approach is that it also helps address other issues in the current implementation of grouping sets. For example the current implementation will produce incorrect results when there are null values in the actual columns. I also looked into creating PR for only fixing that bug in a similar way to #5749 but need to spend some more time on it.
