### ISSUE TITLE
Check the udf output size which should be equal to the input size

### ISSUE THREAD

**Issue by doki23** [apache/datafusion#5735]
Hmmm...or we should check the result size of udf? I'm not sure wether it's proper that the sizes of input and result could be different. cc @alamb @mingmwang @tustvold

_Originally posted by @doki23 in https://github.com/apache/arrow-datafusion/issues/5635#issuecomment-1475092781_

**Comment by ZhengLin-Li** [comment]
@alamb @doki23 it seems that this issue is fixed?

**Comment by doki23** [comment]
> @alamb @doki23 it seems that this issue is fixed? 

I'm not sure :(

**Comment by alamb** [comment]
I think the idea of this ticket was to put some basic checks / assert to ensure that the output of UDFs has the correct 

As I understand it this would mean adding (or seeing if there was an assert) that the number of output rows from accumulators was correct 

Maybe somewhere in

https://github.com/apache/arrow-datafusion/blob/main/datafusion/physical-plan/src/aggregates/row_hash.rs

**Comment by duongcongtoai** [comment]
Hi, i would like to take this issue

**Comment by alamb** [comment]
So the idea here is that we add a check after invoking a ScalarUDF that the number of rows that came out was the same as the number that went in. If this is not the case DataFusion should raise an internal error with a clear error message

**Comment by duongcongtoai** [comment]
This was implemented in this [PR](https://github.com/apache/datafusion/pull/10148) (and we fixed 2 existing UDF violating this violation)
