### ISSUE TITLE
Fuse grouped aggregate and filter operators for improved performance

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#5944]
### Is your feature request related to a problem or challenge?

When we perform a grouped aggregate on a filtered input (such as with TPC-H q1), the filter operator performs two main tasks:

- Evaluate the filter predicate (usually very fast)
- Create new batches and copy over the filtered data (very slow if the filter is not very selective, as in q1)

I wonder if we would see a significant performance improvement if we could avoid creating the filtered batches in this case.

One idea would be to create the filtered batches by copying the arrays and mutating the validity bitmap to hide the rows that are filtered out. This would potentially change the semantics in some cases though so we can probably only do this under certain conditions.

Another idea is to update the aggregate logic to perform the predicate evaluation and then use the resulting bitmap to determine which rows to accumulate.

### Describe the solution you'd like

I am working on a small prototype of this, outside of DataFusion, that I will share once the code is less embarrassing.

### Describe alternatives you've considered

It would be worth seeing how other engines handle this.

**Comment by andygrove** [comment]
@Dandandan @alamb wdyt?

**Comment by Dandandan** [comment]
One source of inefficiency (and should be relatively easy to change) is that currently we output the entire `RecordBatch`, including the columns that are needed to evaluate the filter, while throwing those columns away in the following `Projection`.

See:
 See https://github.com/apache/arrow-datafusion/issues/5436

**Comment by Dandandan** [comment]
In q1 this would remove `l_shipdate` from the list of 7 columns to be copied, so I would expect a smaller improvement here.

**Comment by tustvold** [comment]
https://github.com/apache/arrow-rs/issues/3620 may be related

**Comment by andygrove** [comment]
I did some research / prototyping on this idea.

I used this logic to create a selection vector from a predicate bit mask:

```rust
    let num_true = predicate.true_count();
    let mut b = Int32Builder::with_capacity(num_true);
    for i in 0..predicate.len() {
        if predicate.value(i) {
            b.append_value(i as i32);
        }
    }
    let offsets = b.finish();
```

The selection vector can then be used in a naive sum aggregate like this:


```rust
    let mut sum = 0;
    for i in 0..selection_vector.len() {
        sum += array.value(selection_vector.value(i) as usize);
    }
```

If we ignore the cost of creating the selection vector, then this approach is faster than filtering the batch first. However, the cost of creating the selection vector is similar to filtering a batch in some cases, such as when we are aggregating a single column.

I'm less excited about using selection vectors for aggregates at this point.
