### ISSUE TITLE
Add `greatest(T,...)` and `least(T,...)` SQL functions

### ISSUE THREAD

**Issue by jimexist** [apache/datafusion#6531]
### Is your feature request related to a problem or challenge?

a challenge to implement `greatest` and `least` SQL functions

### Describe the solution you'd like

Similar to the 2023 standard

### Describe alternatives you've considered

using if else but it is very cumbersome

**Comment by waynexia** [comment]
I'd like to continue this task if you don't mind. AFAIK there isn't an obvious blocker from the history of #6527 by @jimexist and #12474 by @rluvaton.

For the topic in #12357 by @alamb, given `greatest` and `least` are both supported by PG and in the spec, adding them to the built-in function list makes sense to me.

**Comment by rluvaton** [comment]
I can reopen my pr and add it

**Comment by alamb** [comment]
Upate is that @rluvaton  added support for greatest in 
- https://github.com/apache/datafusion/pull/12474

Perhaps we should file a separate ticket for `least` 🤔

**Comment by rluvaton** [comment]
I'll try to add the least function in the coming week
