### ISSUE TITLE
Support `FixedSizeList` in array methods

### ISSUE THREAD

**Issue by izveigor** [apache/datafusion#6560]
### Is your feature request related to a problem or challenge?

Follow on to https://github.com/apache/arrow-datafusion/pull/6384

Data can come from different sources (such as `apache-avro`, `parquet` ...) where the list data type is supported, which can become `FixedSizeList` in `arrow-datafusion`. So as not to cause difficulties regarding the casting between `FixedSizeList` and `List`, I suggest to support `FixedSizeList` in all array functions.

### Describe the solution you'd like

Pre casting `FixedSizeList` to `List` before calling array functions or native support for that data type.

### Additional context

Simillar Issues:
https://github.com/apache/arrow-datafusion/issues/6119
https://github.com/apache/arrow-datafusion/issues/6075

**Comment by alamb** [comment]
> 
We should do coercion in datafusion/optimizer/src/analyzer/type_coercion.rs, right?



Yes, that is the preferred location (as it happens before any optimization passes) -- the reason is that type coercion can change the semantics of the plan, but the optimizer passes should not

https://docs.rs/datafusion/latest/datafusion/index.html#planning

**Comment by jayzhan211** [comment]
My first thought is to add casting from `FixedSizeList` to `List` in `coerce_arguments_for_signature`.

However, I fail to construct a test.
I don't know how to create a test case with `DataType::FixedSizeList` in `sqllogictests array.slt`. make_array([1,2]) gives us `ScalarValue::List` which converted to `DataType::List`, anyone have idea?

**Comment by alamb** [comment]
Since `FixedSizeList` is a different Arrow type, we probably need a new ScalarValue variant for it. Maybe `ScalarValue::FixedSizedList` 🤔 


https://docs.rs/datafusion/latest/datafusion/scalar/enum.ScalarValue.html#variant.List

**Comment by jayzhan211** [comment]
I think we have support FixedSizeList already. Thanks for @Weijun-H
