### ISSUE TITLE
Constructing and Destructing Objects (JSON)

### ISSUE THREAD

**Issue by bubbajoe** [apache/datafusion#6631]
### Is your feature request related to a problem or challenge?

Hello,

I am having a problem where i can't handle/use destruct object data. So i figured i'd create an issue and attempt to figure constructing as well. Is there any plan to add full object/json support?

### Describe the solution you'd like

https://www.postgresql.org/docs/9.5/functions-json.html

Operators listed at the top and the functions listed below

**Comment by alamb** [comment]
Thanks @BubbaJoe  -- I added this to our current list at https://github.com/apache/arrow-datafusion/issues/2326

It would be great to add this feature

**Comment by alamb** [comment]
See also #7845

**Comment by alamb** [comment]
I think this is covered by https://github.com/apache/datafusion/issues/7845 so let's keep the discussion going there
