### ISSUE TITLE
Add projection to `HashJoinExec` to avoid unecessary output creation

### ISSUE THREAD

**Issue by Dandandan** [apache/datafusion#6768]
### Is your feature request related to a problem or challenge?

Currently `HashJoinExec` returns all the columns from both sides of the join.

We can add the necessary output columns so we can save some work in gathering values (`take`) from batches based on matching indices.

This is similar to #5436

### Describe the solution you'd like
Add projection to hashjoinexec, use it to reduce output.

**Comment by my-vegetable-has-exploded** [comment]
I'd like to have a try.

**Comment by eejbyfeldt** [comment]
Is there something left to be done in this issue after #9236 My understanding is that it completes all the work currently described in the ticket.

**Comment by Dandandan** [comment]
It's done

**Comment by Dandandan** [comment]
Thanks @eejbyfeldt for the observation
