### ISSUE TITLE
Using string datatype from python raises "Exception: The type 13 is not valid"

### ISSUE THREAD

**Issue by syntonym** [apache/datafusion#693]
I'm trying to use datafusion from python with the python package datafusion  0.2.0 and pyarrow 4.0.1. Using a string datatype leads to `Exception: The type 13 is not valid` when trying to construct a dataframe (see code below). 

It seems that at least for my pyarrow 4.0.1 the string datatype has id 13 instead of the expected 21.

In datafusion-python the ids are set in python/src/types.rs where 21 gets mapped to UTF8 and 13 is not mapped due to being unsupported. Changing 21 here to 13 and building the package fixes the error and datafusion works with my data as expected. In arrow it seems like type ids are coming from an enum in arrow/python/pyarrow/includes/libarrow.pxd where string is the 21st entry. I thought that maybe I used an old pyarrow version, but the last recent code changes in that area are 13 months old.

**To Reproduce**

```
import datafusion
import pyarrow

f = datafusion.functions

batch = pyarrow.RecordBatch.from_arrays(
    [pyarrow.array(["a", "b", "c"]), pyarrow.array([4, 5, 6])],
    names=["a", "b"],
)

ctx = datafusion.ExecutionContext()
df = ctx.create_dataframe([[batch]])
```

**Comment by drauschenbach** [comment]
This issue seems obsolete now.

__To Verify__

```python
import datafusion
import pyarrow

f = datafusion.functions

batch = pyarrow.RecordBatch.from_arrays(
    [pyarrow.array(["a", "b", "c"]), pyarrow.array([4, 5, 6])],
    names=["a", "b"],
)
ctx = datafusion.SessionContext()
df = ctx.create_dataframe([[batch]])
print(df)
```

```
DataFrame()
+---+---+
| a | b |
+---+---+
| a | 4 |
| b | 5 |
| c | 6 |
+---+---+
```

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
