### ISSUE TITLE
Improved performance for streaming group by 

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#7023]
### Is your feature request related to a problem or challenge?

During review of https://github.com/apache/arrow-datafusion/pull/6932 there were several suggstions made about how we could improve the performance of streaming / bounded grouping (when the data is sorted by some/all of the group keys)

This ticket tracks those improvements

### Describe the solution you'd like

# Suggestion 1
@tustvold  suggests on https://github.com/apache/arrow-datafusion/pull/6932#r1267305736

> It occurs to me that a potentially faster way to detect the group boundaries would be to use the inequality kernel offset by one w.r.t to each other, ORing the results together, and then iterating over the set bits.
> 
> There would be some subtlety to handle nulls correctly, but it would likely be significantly faster and would not require converting to the row format
>
> We could likely do something similar for window functions if we aren't already

Note that IOx does something similar to compute partition boundaries here: https://github.com/influxdata/influxdb_iox/blob/d3b3805e5fa87214ea934427df3967a57a14669c/iox_query/src/provider/deduplicate/algo.rs#L101-L207

# Suggestion 2
From https://github.com/apache/arrow-datafusion/pull/6932#r1267344573

> In the case of GroupOrderingFull it seems unnecessary to be computing hashes at all, we can just group based on whenever the sort key changes?

This could likely go quite a bit faster as hashing is a significant part of the time

**Comment by smiklos** [comment]
@alamb I think this issue can be closed. Suggestion 1 is done, suggestion 2 is no longer relevant as there are no hashes computed for GroupOrderingFull

**Comment by alamb** [comment]
Thanks @smiklos  -- done!
