### ISSUE TITLE
is there a way to get a result similar to `datediff` function

### ISSUE THREAD

**Issue by jiangzhx** [apache/datafusion#7097]
### Is your feature request related to a problem or challenge?

I’d like to ask if there is a way to get a result similar to `datediff` function , also it seems that this function is not available in DataFusion.

i try another way like this,but how can i get 6  days from  interval  result
```
select to_timestamp(now())-to_timestamp('2023-07-20T05:44:00.419557');

+------------------------------------------------------------------------+                                                                                             
| to_timestamp(now()) - to_timestamp(Utf8("2023-07-20T05:44:00.419557")) |                                                                                             
+------------------------------------------------------------------------+                                                                                             
| 0 years 0 mons 6 days 0 hours 51 mins 7.343851000 secs                 |                                                                                             
+------------------------------------------------------------------------+           
```                                                                                  

### Describe the solution you'd like

something like `date_diff` 
 

### Describe alternatives you've considered

add udf like `date_diff`
or 
make 
`select extract(day from interval '1 days' ); `
work
```

Error during planning: No function matches the given name and argument types 'date_part(Utf8, Interval(MonthDayNano))'. You might need to add explicit type casts.
        Candidate functions:
        date_part(Utf8, Date32)
        date_part(Utf8, Date64)
        date_part(Utf8, Timestamp(Second, None))
        date_part(Utf8, Timestamp(Microsecond, None))
        date_part(Utf8, Timestamp(Millisecond, None))
        date_part(Utf8, Timestamp(Nanosecond, None))
        date_part(Utf8, Timestamp(Nanosecond, Some("+00:00")))

```

### Additional context
https://www.postgresql.org/docs/current/functions-datetime.html

https://github.com/apache/arrow-datafusion/blob/52cf58b46133d448e067455baab0faf8a50e565a/datafusion/expr/src/built_in_function.rs#L1021-L1032

https://github.com/apache/arrow-datafusion/blob/52cf58b46133d448e067455baab0faf8a50e565a/datafusion/physical-expr/src/datetime_expressions.rs#L729C1-L729C1

**Comment by alamb** [comment]
I think this would be a good first issue as the wiring is all done and this would be a relatively simple extension to date_part I think

**Comment by alamb** [comment]
For example, either use or follow https://docs.rs/arrow/latest/arrow/compute/fn.day.html

**Comment by smallzhongfeng** [comment]
Do we have plans to support date_diff, date_add and other time functions, such as comparing spark's udf function about `date`? [https://spark.apache.org/docs/3.4.1/api/sql/search.html?q=date](https://spark.apache.org/docs/3.4.1/api/sql/search.html?q=date)

**Comment by alamb** [comment]
> Do we have plans to support date_diff, date_add and other time functions, @alamb such as comparing spark's udf

There do not appear to be any such plans:  https://github.com/apache/arrow-datafusion/issues?q=is%3Aissue+is%3Aopen+date_diff+

Adding them seems like a good idea to me. However, st some point we probably need to figure out how to split functions into packages so users can mix/match "packages" of functions they want without having to get all of the others. I filed https://github.com/apache/arrow-datafusion/issues/7110 to track this idea

🤔

**Comment by NiwakaDev** [comment]
@alamb 

I'd like to implement the following feature:
```sql
select extract(~ from interval ~ ); 
```

**Comment by alamb** [comment]
Thanks @NiwakaDev  -- let us know if you run into any trouble.

**Comment by NiwakaDev** [comment]
As far as I understand, it seems like this issue depends on https://github.com/apache/arrow-rs/issues/4969.

**Comment by Jefffrey** [comment]
Note there is an existing issue for implementing `extract(X from interval)` in Datafusion here: #6327

I've also put details in a comment there with comparison of other engines behaviour
