### ISSUE TITLE
implement `generate_series` function

### ISSUE THREAD

**Issue by jimexist** [apache/datafusion#753]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

implement `generate_series` function

**Describe the solution you'd like**

similar to https://www.postgresql.org/docs/current/functions-srf.html

**Describe alternatives you've considered**

**Additional context**

**Comment by Jimexist** [comment]
see related #1080

**Comment by Weijun-H** [comment]
Hi @Jimexist, is this feature still pending completion? If so, I would like to take responsibility for it.

**Comment by Abdullahsab3** [comment]
I believe `generate_series` is now included in Datafusion

**Comment by Weijun-H** [comment]
Thanks @Abdullahsab3, this issue is completed via #8140
