### ISSUE TITLE
Improve optimizer performance by not using `Error`s in the happy path

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#7552]
### Is your feature request related to a problem or challenge?

We have had a few issues / reports where the creation of `DataFusionError` during query planning has contributed significantly to the overall planning time. Specifically,  https://github.com/apache/arrow-datafusion/issues/5309 and more recently https://github.com/apache/arrow-datafusion/issues/7522

At the core of the issue is that creating a `DataFusionError` is a fairly slow operation (as it requires allocating a new `String` to hold the error message, and sometimes, as in https://github.com/apache/arrow-datafusion/issues/5309, the construction of the message itself is significant. 

### Describe the solution you'd like

I would like to update the DataFusion codebase so it does not use Errors on the "happy path" 

Tasks: 
- [x] https://github.com/apache/arrow-datafusion/issues/5309
- [x] https://github.com/apache/arrow-datafusion/issues/7553

### Describe alternatives you've considered

We could potentially make it faster / cheaper to create DataFusion errors

**Comment by alamb** [comment]
Here is an example of using Errors in the happy path (aka ignoring an error rather than fixing the underlying issue)

https://github.com/apache/arrow-datafusion/blob/c47ae0d13dbc9474897609f3dea4f80a93cf4de0/datafusion/physical-plan/src/filter.rs#L206-L209

**Comment by comphead** [comment]
I wanna check that if no other volunteers

**Comment by comphead** [comment]
I would also close this as most a lot of job was done for planner to improve the performance

**Comment by comphead** [comment]
@alamb I'm closing this, please feel free to reopen if needed

**Comment by alamb** [comment]
I agree -- thanks for cleaning these up @comphead  -- we can file new tickets if/when we have actionable changes to make
