### ISSUE TITLE
Is it possible to pass query parameters in a SQL query?

### ISSUE THREAD

**Issue by shner-elmo** [apache/datafusion#7776]
### Is your feature request related to a problem or challenge?

I would like to do smth like: `execute("SELECT * FROM table WHERE id = ?", &[435])`, is it possible?

### Describe the solution you'd like

It would be nice to be able to pass the parameters as an array or something similar (instead of hardcoding them into the query-string)

**Comment by alamb** [comment]
hi @shner-elmo  -- yes you can do this with `PREPARE` statements:

Here are some examples:
https://github.com/apache/arrow-datafusion/blob/b6f87edbbaaaedd696b2e448fcd7df7ad3cd2c93/datafusion/sqllogictest/test_files/prepare.slt#L18-L20

You can do it via a `DataFrame` like this:
https://docs.rs/datafusion/latest/datafusion/dataframe/struct.DataFrame.html#method.with_param_values

Something like
```rust
let ctx: SessionContext = ...;
ctx.sql(""SELECT * FROM table WHERE id = ?")
  .await?
  .with_param_values(vec![lit(435)])?
  .collect()
```

This is something that should be documented. I will try and do so

**Comment by alamb** [comment]
PR with documentation: https://github.com/apache/arrow-datafusion/pull/7785

**Comment by alamb** [comment]
(there are some rough edges around the usability that I fixed in https://github.com/apache/arrow-datafusion/pull/7785)
