### ISSUE TITLE
Add mechanism to verify that source code in documentation is valid

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#7951]
### Is your feature request related to a problem or challenge?

Our user guide and library guide contain code samples, but these can quickly become outdated and stop compiling and we have to automated way to check if they still compile.

### Describe the solution you'd like

I propose that code samples be written as unit tests and that we then use a script to insert these code samples into the documentation when we publish the docs.

**Comment by alamb** [comment]
I believe this is now handled via the `doctest` macro, for example:

https://github.com/apache/datafusion/blob/37e54ee874e9027a329ba4f6c1e0e6359d63a33c/datafusion/core/src/lib.rs#L618-L643
