### ISSUE TITLE
Introduce return_data_type for Aggregate function

### ISSUE THREAD

**Issue by jayzhan211** [apache/datafusion#7960]
### Is your feature request related to a problem or challenge?

return_data_type is not the same as the data_type for List case. For example, data_type: List(Int64), return_data_type will be Int64

Ref: https://github.com/apache/arrow-datafusion/pull/7242/files

### Describe the solution you'd like

Introduce return_data_type for Sum, and other Aggregate function

**Comment by alamb** [comment]
I think we should do some more careful thinking of how to handle multi-phase aggregates where the intermediate type is not the same as the output type -- for example `SUM(x)` for non lists can use the same aggregate (as you can sum partial sums) but `COUNT(x)` does not -- the first phase must actually COUNT but the second needs to use SUM.

This causes problems for #6937 where we might want to dynamically stop doing the first phase aggregation.

**Comment by jayzhan211** [comment]
TODO
- [ ] min_max

**Comment by jayzhan211** [comment]
Reopen it if there is any concrete issue to solve
