### ISSUE TITLE
Implement `parquet_metadata` function in datafusion-cli

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#8367]
### Is your feature request related to a problem or challenge?

When exploring Parquet files using `datafusion-cli` I would often like to see how they are structured (how many row groups, if they have statistics, etc). 

### Describe the solution you'd like

I would like to create new functions for exploring parquet metadata using the new User Defined Table Functions (🙇 to @Veeupup ) introduced in https://github.com/apache/arrow-datafusion/pull/8306

Ideally we could implement something like `parquet_metadata`:  https://duckdb.org/docs/data/parquet/overview

(I think parquet_schema is covered by `describe 'filename.parquet'` already

Note I think this should be done  in datafusion-cli (not core DataFusion)

**Comment by alamb** [comment]
This would also be a great test of the user defined table function feature to see if we can build something slightly more complicated than `read_csv`

**Comment by Veeupup** [comment]
I can help with this ticket as a following PR to #8306

**Comment by Veeupup** [comment]
After this ticker was finished, maybe we can have a list of internal table functions to implement, just like:

- [ ] read_csv
- [ ] read_parquet
- [ ] read_json
- [ ] ...
