### ISSUE TITLE
CSV WriterBuilder should expose `timestamp_tz_format` field

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion#8640]
### Is your feature request related to a problem or challenge?

There are no set/get methods for the field `timestamp_tz_format`. I don't know if this is intentional or just an oversight. If it is intentional then it would be good to add a comment explaining the rationale.

**Comment by andygrove** [comment]
@devinjdangelo fyi

**Comment by alamb** [comment]
I think this would be a good first issue for someone to help out with if they wanted

**Comment by razeghi71** [comment]
I can work on this. Just to clarify this need this needs to be implemented in `arrow-csv` right?

**Comment by alamb** [comment]
I did some poking around, and while I actually think the relevant `timestamp_tz_format` field already exists in arrow:
https://github.com/apache/arrow-rs/blob/b2b4e7a44f814ac5f9d20886171ea20b2dd8a30f/arrow-csv/src/writer.rs#L128

It doesn't seem to be able to be set it.

So maybe the first thing to do is to figure out if that is an important setting to control for csv writing and if so, expose its configuration in arrow-rs.

Then this  ticket would entail connecting it up to datafusion, similarly to how `date_format` and `time_format` are exposed: https://github.com/apache/arrow-datafusion/blob/bf0a39a791e7cd0e965abb8c87950cc4101149f7/datafusion/common/src/file_options/csv_writer.rs#L69C1-L74
