### ISSUE TITLE
Support parsing SQL strings to `Expr`s

### ISSUE THREAD

**Issue by jiacai2050** [apache/datafusion#8736]
Part of https://github.com/apache/datafusion/issues/9494

### Is your feature request related to a problem or challenge?

Currently when we need to construct an `Expr`, we need to build it by hand, take `a > 1` for example:
```rust
Expr::BinaryExpr(datafusion::logical_expr::BinaryExpr::new(
    Box::new(col("a")),
    Operator::Gt,
    Box::new(lit(1)),
))
```

Although this works, it becomes tedious when we need to construct complex expr like `a > 1 and b in (1,10) ....`

### Describe the solution you'd like

Impl `FromStr` for Expr, so we can get an `Expr` from String directly.

**Comment by alamb** [comment]
Also related https://github.com/apache/arrow-datafusion/issues/7165

I think this also came up a few days ago but I can't find the reference (maybe @devinjdangelo remembers 🤔 )

**Comment by Jefffrey** [comment]
Also relates to https://github.com/apache/arrow-datafusion/issues/4890 I believe

**Comment by devinjdangelo** [comment]
> Also related https://github.com/apache/arrow-datafusion/issues/7165
> 
> 
> 
> I think this also came up a few days ago but I can't find the reference (maybe @devinjdangelo remembers 🤔 )

#8661 perhaps?

**Comment by jiacai2050** [comment]
If maintainers thinks this is a reasonable request, and no one is working on this, I will draft a PR in next few days.

**Comment by alamb** [comment]
Making exprs from strings sounds like a good idea to me.

BTW you can also use the more fluent style API to make exprs, which while still tedious is still a bit better:

Rather than
```rust
Expr::BinaryExpr(datafusion::logical_expr::BinaryExpr::new(
    Box::new(col("a")),
    Operator::Gt,
    Box::new(lit(1)),
))
```

You can write
```
col("a").gt(lit(1))
```

The benfit of this approach over strings is that the compiler can check / ensure the exprs are constructed correctly. However, I think the usecase of usign strings to, for example, serialize Exprs and let users provide arbitrary filters makes a `String` --> `Expr` API still useful

**Comment by alamb** [comment]
I think you can do this today via [`SqlToRel::sql_to_expr`](https://docs.rs/datafusion/latest/datafusion/sql/planner/struct.SqlToRel.html#method.sql_to_expr) 


## Step 1:  Add an example to show how to use `SqlToRel::sql_to_expr`

 So add  an example (perhaps `expr_to_sql.rs`) in
https://github.com/apache/arrow-datafusion/tree/main/datafusion-examples/examples that showed how to call `SqlToRel` to parser the expression above

## Step 2: Add an API to DataFusion that made parsing SQL easier 

The idea is to avoid requiring  PlannerContext, a `DFSchema`, etc). 

For example:
```rust
let expr: Expr = parse_expr("c < 5")?;
```

Note this doesn't provide a schema.

**Comment by Omega359** [comment]
```
let table_provider = norm.session_context.table_provider(norm.table_name.clone()).wait().unwrap();
    let table_schema_provider = TableSchemaProvider::new(norm.table_name.clone(), table_provider.as_ref());
    let sql_to_rel = SqlToRel::new_with_options(&table_schema_provider, parser_options);
    let sql_to_expr = sql_to_rel.sql_to_expr(expr.clone(), df.schema(), &mut PlannerContext::new());

    if sql_to_expr.is_err() {
        error!("Unable to transform sql expression '{}' to datafusion Expr: {:?}", &expression, sql_to_expr.err());
        panic!();
    }

    sql_to_expr.unwrap()
    ```

**Comment by alamb** [comment]
Thanks @Omega359  -- that looks nice. I think the next step is to turn it into a function with some doc strings and an example

**Comment by Omega359** [comment]
I took a quick look at the impl for sql_to_expr and on down the code paths from there. Removing the requirement for a schema may be problematic since so much of the api requires a schema for handling identifiers, aliases and type information.

**Comment by alamb** [comment]
> I took a quick look at the impl for sql_to_expr and on down the code paths from there. Removing the requirement for a schema may be problematic since so much of the api requires a schema for handling identifiers, aliases and type information.

Maybe we could use an empty schema (e.g. https://docs.rs/datafusion/latest/datafusion/common/struct.DFSchema.html#method.empty) if there were no column references

I agree that if there are column references in the expression, the user will need to provide a schema for parsing

**Comment by backkem** [comment]
This new testcase has some similar code:
https://github.com/apache/arrow-datafusion/blob/3b61004a02978843ff02a06c8f1f3ce3e88e4a6d/datafusion/sql/tests/sql_integration.rs#L4501-L4509

Maybe it can be cleaned up when the new API is added.

**Comment by alamb** [comment]
This came up again on discord: https://discord.com/channels/885562378132000778/1166447479609376850/1252616019357470731

Here is some code that @Omega359  shared


```rust
pub(crate) fn build_expression(norm: &FieldNormalizer, df: &DataFrame, expression: &str) -> Result<Expr> {
    let parser = Parser::new(&AnsiDialect {});
    let tokenized = parser.try_with_sql(expression);
    if tokenized.is_err() {
        bail!("Unable to tokenize expression '{}': {:?}", &expression, tokenized.err())
    }

    let parsed = tokenized?.parse_expr();
    if parsed.is_err() {
        bail!("Unable to parse expression '{}': {:?}", &expression, parsed.err())
    }

    let expr = parsed?;
    debug!("Parsed expression was '{}'", expr);

    let parser_options = ParserOptions {
        enable_ident_normalization: false,
        parse_float_as_decimal: false,
    };

    let table_schema_provider = TableSchemaProvider::new(norm.table_name.clone(), norm.session_context.clone());
    let sql_to_rel = SqlToRel::new_with_options(&table_schema_provider, parser_options);
    let sql_to_expr = sql_to_rel.sql_to_expr(expr.clone(), df.schema(), &mut PlannerContext::new());

    if sql_to_expr.is_err() {
        bail!("Unable to transform sql expression '{}' to datafusion Expr: {:?}", &expression, sql_to_expr.err())
    }

    Ok(sql_to_expr?)
}
```

I think it would be great to add an API to `DataFrame` and `SessionContext` to do this:

```rust
impl SessionContext {
   /// parse the provided expression as a string
  fn parse_sql(&self, sql: &str) -> Result<Expr> { ... }
}
```

```rust
impl DataFrame {
   /// parse the provided expression as a string
  fn parse_sql(&self, sql: &str) -> Result<Expr> { ... }
}
```

Perhaps @xinlifoobar has time to help here 🤔

**Comment by xinlifoobar** [comment]
I am trying to look into this.

**Comment by xinlifoobar** [comment]
> This came up again on discord: https://discord.com/channels/885562378132000778/1166447479609376850/1252616019357470731
> 
> Here is some code that @Omega359 shared
> 
> ```rust
> pub(crate) fn build_expression(norm: &FieldNormalizer, df: &DataFrame, expression: &str) -> Result<Expr> {
>     let parser = Parser::new(&AnsiDialect {});
>     let tokenized = parser.try_with_sql(expression);
>     if tokenized.is_err() {
>         bail!("Unable to tokenize expression '{}': {:?}", &expression, tokenized.err())
>     }
> 
>     let parsed = tokenized?.parse_expr();
>     if parsed.is_err() {
>         bail!("Unable to parse expression '{}': {:?}", &expression, parsed.err())
>     }
> 
>     let expr = parsed?;
>     debug!("Parsed expression was '{}'", expr);
> 
>     let parser_options = ParserOptions {
>         enable_ident_normalization: false,
>         parse_float_as_decimal: false,
>     };
> 
>     let table_schema_provider = TableSchemaProvider::new(norm.table_name.clone(), norm.session_context.clone());
>     let sql_to_rel = SqlToRel::new_with_options(&table_schema_provider, parser_options);
>     let sql_to_expr = sql_to_rel.sql_to_expr(expr.clone(), df.schema(), &mut PlannerContext::new());
> 
>     if sql_to_expr.is_err() {
>         bail!("Unable to transform sql expression '{}' to datafusion Expr: {:?}", &expression, sql_to_expr.err())
>     }
> 
>     Ok(sql_to_expr?)
> }
> ```
> 
> I think it would be great to add an API to `DataFrame` and `SessionContext` to do this:
> 
> ```rust
> impl SessionContext {
>    /// parse the provided expression as a string
>   fn parse_sql(&self, sql: &str) -> Result<Expr> { ... }
> }
> ```
> 
> ```rust
> impl DataFrame {
>    /// parse the provided expression as a string
>   fn parse_sql(&self, sql: &str) -> Result<Expr> { ... }
> }
> ```
> 
> Perhaps @xinlifoobar has time to help here 🤔

I am thinking of the consequence usages of `DataFrame::parse_sql`, e.g.,

```rust
let ctx = SessionContext::new();
// Read the data from a csv file
let df = ctx.read_csv("tests/data/example.csv", CsvReadOptions::new()).await?;

// 1st parse_sql
df.parse_sql("SELECT a, MIN(b) FROM df WHERE a <= b GROUP BY a LIMIT 100;");

// 2nd parse_sql
df.parse_sql("SELECT a, MIN(b) FROM df WHERE a <= b GROUP BY a LIMIT 100;");
```

Can this simply treat the first SQL as a subquery?

**Comment by xinlifoobar** [comment]
Additionally, I looked into the `pyspark` library. It has `sql` function at the `SparkSession` level but not in `Dataframe`.

[SparkSession.sql](https://spark.apache.org/docs/2.4.4/api/python/_modules/pyspark/sql/session.html#SparkSession.sql)
[Dataframe](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/dataframe.html)

**Comment by alamb** [comment]
@xinlifoobar  has a very nice PR to add this API: https://github.com/apache/datafusion/pull/10995
