### ISSUE TITLE
Support `array_distance` in `array_expression`

### ISSUE THREAD

**Issue by Weijun-H** [apache/datafusion#8782]
### Is your feature request related to a problem or challenge?

The current implementation of `array_expression.rs` lacks support for the array_distance functionality. This feature is essential for users who want to calculate distances between arrays using specific metrics or custom distance functions.

expect result
```
array_distance([1, 2, 3], [4, 5, 6]) --> 5.196152422706632
array_distance([1, 2, 3], [4, 5, 6], 'l1') --> 3
array_distance([1, 2, 3], [4, 5, 6], 'l2') --> 5.196152422706632
```

### Additional context

list_distance [duckdb](https://duckdb.org/docs/sql/functions/nested)
l1distance [clickhouse](https://clickhouse.com/docs/en/sql-reference/functions/distance-functions#l1distance)l1distance l2distance [clickhouse](https://clickhouse.com/docs/en/sql-reference/functions/distance-functions#l2distance)

**Comment by Weijun-H** [comment]
I will work on this task if no one else wants to.

**Comment by Weijun-H** [comment]
It seems like it could be done after #7213.

**Comment by Tangruilin** [comment]
@Weijun-H , I am interesting in this issue.

**Comment by Weijun-H** [comment]
> @Weijun-H , I am interesting in this issue.

Hi @Tangruilin , I think this issue is stalled by #8708

**Comment by Weijun-H** [comment]
support the column value
