### ISSUE TITLE
Optimize performance by fusing boolean operations.

### ISSUE THREAD

**Issue by RTEnzyme** [apache/datafusion#8816]
https://github.com/apache/arrow-datafusion/blob/e5ba6de074affd40cb0984d503694e543d816a6c/datafusion/physical-expr/src/expressions/case.rs#L164C1-L165C1

For the below code:
``` Rust
remainder = and(&remainder, &not(&when_match)?)?;
```
By implementing the `and_not` boolean function, we can fuse these two operations into one single operation, instead of performing them separately (first applying not to when_match and then applying and to remainder). This optimization can potentially enhance the efficiency of the code.

**Comment by alamb** [comment]
if we can get a benchmark showing it is faster this seems like a reasonable idea to me

**Comment by RTEnzyme** [comment]
benchmark:
```Rust
use arrow::array::{Array, BooleanArray};
use arrow::compute::{not, and};
use arrow_buffer::{NullBuffer, BooleanBuffer, bitwise_bin_op_helper};
use arrow_schema::ArrowError;
use criterion::{criterion_group, criterion_main, Criterion, black_box};
use rand::prelude::*;

fn do_bench(c: &mut Criterion, array_length: usize, lhs: &BooleanArray, rhs: &BooleanArray) {
    

    c.bench_function(&format!("Use and(lhs, not(rhs)), {array_length}"), |b| {
        b.iter(|| black_box(and(lhs, &not(rhs).unwrap())))
    });

    c.bench_function(&format!("Use and_not(lhs, rhs), {array_length}"), |b| {
        b.iter(|| black_box(and_not(lhs, rhs)))
    });
}

pub fn and_not(left: &BooleanArray, right: &BooleanArray) -> Result<BooleanArray, ArrowError> {
    let nulls = NullBuffer::union(left.nulls(), right.nulls());
    let buffer = bitwise_bin_op_helper(
        left.values().inner(),
        0,
        right.values().inner(),
        0,
        left.len(),
        |a, b| a & !b,
    );
    let values = BooleanBuffer::new(buffer, 0, left.len());
    Ok(BooleanArray::new(values, nulls))
}

fn do_benches(
    c: &mut Criterion,
    array_length: usize,
) {
    let mut rng = StdRng::seed_from_u64(120320);


    let lhs: BooleanArray = (0..array_length)
        .map(|_| Some(rng.gen::<bool>()))
        .collect();

    let rhs: BooleanArray = (0..array_length)
        .map(|_| Some(rng.gen()))
        .collect();

    do_bench(
        c,
        array_length,
        &lhs,
        &rhs,
    );
}

fn criterion_benchmark(c: &mut Criterion) {
    for array_length in [100, 1000, 10000, 100000] {
        do_benches(c, array_length)
    }
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```
The benchmark result:

| array_length | and(lhs, not(rhs)) | and_not(lhs, rhs) | Improvement Ratio|
|--------------|-------------------|------------------|------------------|
| 100 | 149.17 ns | 102.88 ns | 31.11% |
| 1000 | 167.16 ns | 78.770 ns | 52.89% |
| 10000 | 270.81 ns | 90.285 ns | 66.67% |
| 100000 | 666.20 ns | 336.37 ns | 49.51% |

**Comment by alamb** [comment]
It certainly looks promising

Maybe it is worth filing a suggeston in arrow-rs: https://github.com/apache/arrow-rs/issues

In general I think improving filtering performance would be beneficial whenever possible 👍
