### ISSUE TITLE
Improved output of `datafuson-cli` with empty results

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#8904]
### Is your feature request related to a problem or challenge?

As @Jefffrey @crepererum  and @berkaysynnada  pointed out on https://github.com/apache/arrow-datafusion/pull/8895 (see https://github.com/apache/arrow-datafusion/pull/8895#discussion_r1456993754), the handling of results that have no rows could potentially be improved

```shell
datafusion-cli
seleDataFusion CLI v34.0.0
❯ select * from (values (1));
+---------+
| column1 |
+---------+
| 1       |
+---------+
1 row in set. Query took 0.009 seconds.

❯ select * from (values (1)) where column1 = 2;
0 rows in set. Query took 0.003 seconds.
```

Note there is nothing printed out from `select * from (values (1)) where column1 = 2;` (not even headers) when there are no results

### Describe the solution you'd like

It would be nice to print out headers even when there was no result:

So something like:
```sql
select * from (values (1)) where column1 = 2;
+---------+
| column1 |
+---------+
+---------+
```

### Describe alternatives you've considered

We can also do nothing

### Additional context

This issue itself isn't particularly pressing in my opinion

**Comment by Tangruilin** [comment]
I can help with this problem.

maybe it can be assign to me

**Comment by Tangruilin** [comment]
@alamb

**Comment by alamb** [comment]
BTW I think the tests added in https://github.com/apache/arrow-datafusion/pull/8896 are sufficient -- if you make this change I think the existing tests can be updated and no new tests are needed
