### ISSUE TITLE
Optimize performance of regular expression filtering

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#905]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The performance of the `~` operators, introduced in https://github.com/apache/arrow-datafusion/pull/870 will likely be non ideal due to the interface of the arrow kernel used, as described in https://github.com/apache/arrow-rs/issues/697

**Describe the solution you'd like**
If/when the kernel of https://github.com/apache/arrow-rs/issues/697 is implemented, the idea would be to switch datafusion to use those kernels. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Jefffrey** [comment]
Closed by #870 (it included the changes from https://github.com/apache/arrow-rs/issues/697 after that was merged since was part of 5.3)
