### ISSUE TITLE
Optimize `to_timestamp`

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#9090]
### Is your feature request related to a problem or challenge?

I think there is significant performance to be had when creating dates and now thanks to @Omega359  there are benchmarks

To run the benchmarks, do:
```shell
cargo bench --bench to_timestamp
```

### Describe the solution you'd like

Make  the function faster, as defined by the command above

The high level procedure for this is to profile the function and figure out how to make it go faster while still computing the same results

### Describe alternatives you've considered

It may not be possible to make this faster and in that case no worries.

### Additional context

I think this is actually a pretty good initial project for someone because 
1. The code is relatively straightforward
2. The benchmark is in place

**Comment by manoj-inukolunu** [comment]
@alamb  can i give this a shot too please?

**Comment by istvan-fodor** [comment]
@alamb, @Omega359  I took at look at the benchmarks and I had some questions. 

It looks to me that the code that is benchmarked doesn't actually create timestamps, it just creates the expressions that **if** evaluated would/should return timestamps. I checked in the debugger and could never catch anything in `ToTimestampFunc::invoke()`. Also, when I printed out the results of the `to_timestamp` calls form the benchmark I saw these:

```
to_timestamp(Utf8("1997-01-31T09:26:56.123Z"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%dT%H:%M:%S%.f%Z"))
to_timestamp(Utf8("1997-01-31T09:26:56.123-05:00"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%dT%H:%M:%S%.f%z"))
to_timestamp(Utf8("1997-01-31 09:26:56.123-05:00"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%d %H:%M:%S%.f%Z"))
to_timestamp(Utf8("2023-01-01 04:05:06.789 -08"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%d %H:%M:%S%.f %#z"))
to_timestamp(Utf8("1997-01-31T09:26:56.123"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%dT%H:%M:%S%.f"))
to_timestamp(Utf8("1997-01-31 09:26:56.123"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%d %H:%M:%S%.f"))
to_timestamp(Utf8("1997-01-31 09:26:56"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%d %H:%M:%S"))
to_timestamp(Utf8("1997-01-31 092656"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%d %H%M%S"))
to_timestamp(Utf8("1997-01-31 092656+04:00"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%d %H%M%S%:z"))
to_timestamp(Utf8("Sun Jul  8 00:34:60 2001"), Utf8("%+"), Utf8("%c"), Utf8("%Y-%m-%d 00:00:00"))
```

Am I reading this right or am I missing this completely? Is the goal here to speed up str -> timestamp creation or to speed up the creation of the expression?

**Comment by alamb** [comment]
> Am I reading this right or am I missing this completely? Is the goal here to speed up str -> timestamp creation or to speed up the creation of the expression?

I believe @Omega359  fixed this in https://github.com/apache/arrow-datafusion/pull/9608 (which merged a few hours ago)

**Comment by vojtechtoman** [comment]
https://github.com/apache/arrow-datafusion/pull/9694 is still an early draft but I was already able to improve the performance of `to_timestamp` (without format for now) by about 15% percent on my machine, and I think there is still quite some potential there.

**Comment by vojtechtoman** [comment]
While #9694 is still work in progress, I managed to speed up some cases of `to_timestamp(timestamp, format) in https://github.com/apache/arrow-datafusion/pull/9833.

**Comment by alamb** [comment]
Awesome -- thank you @vojtechtoman -- I'll check it out!

**Comment by Omega359** [comment]
I think this issue can be closed as I believe it's been resolved via https://github.com/apache/datafusion/pull/9833
