### ISSUE TITLE
Add fuzzing / random SQL testing 

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#913]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In a past project, we had a harness that could generate random SQL queries and it found many bugs -- such tests are a wonderful way to help database software mature. Applying such technology to DataFusion would be very cool.

On https://github.com/sqlparser-rs/sqlparser-rs/pull/312#discussion_r693298728, @PsiACE points at a good blog post from cockroachdb: https://www.cockroachlabs.com/blog/sqlsmith-randomized-sql-testing/ that describes such testing

One of the tools mentioned is https://github.com/anse1/sqlsmith 

**Describe the solution you'd like**
Add a script / way to run [SQLSmith](https://github.com/anse1/sqlsmith) against DataFusion. As described in the [blog](https://www.cockroachlabs.com/blog/sqlsmith-randomized-sql-testing) this might require modifying SQLSmith to restrict itself to the subset of postgres datafusion supports

I would suggest we don't put this in CI initially until someone has the bandwidth to review the results, but getting the scripts that could be run setup would be a great first step

**Describe alternatives you've considered**
Haven't done research into alternatives to SQlsmitg

**Additional context**
https://github.com/sqlparser-rs/sqlparser-rs/pull/312

**Comment by andygrove** [comment]
I have started work on fuzzing SQL and data using https://github.com/andygrove/sqlfuzz and plan on eventually adding tests to this project but for now, I am doing this separately. It has already been effective in finding bugs.

**Comment by alamb** [comment]
Given https://github.com/apache/datafusion/issues/11030 / https://github.com/datafusion-contrib/datafusion-sqlancer from @2010YOUY01 I think I am going to claim this issue is closed. 

Thanks again @2010YOUY01
