### ISSUE TITLE
Support `IS NOT NULL` predicates in PruningPredicate

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#9231]
### Is your feature request related to a problem or challenge?

the [`PruningPredicate` ](https://docs.rs/datafusion/latest/datafusion/physical_optimizer/pruning/struct.PruningPredicate.html)currently does not handle `IS NOT NULL` predicates

### Additional context

@appletreeisyellow  added an initial implementation in https://github.com/apache/arrow-datafusion/pull/9208 but I believe it didn't work in all cases, as described in https://github.com/apache/arrow-datafusion/issues/9230

**Comment by guojidan** [comment]
take

**Comment by guojidan** [comment]
Perhaps @appletreeisyellow  is more suitable for handling this issue😄

**Comment by alamb** [comment]
One thing I should have noted in the description here is that I think implementing `IS NOT NULL` will require a new API to `PruningStatistics` (the `total_row_count`) . Conveniently, @appletreeisyellow  is adding this API as part of https://github.com/apache/arrow-datafusion/issues/9171  I think

So in other words, this ticket is likely blocked until #9171 is done

BTW there is a bunch more backstory on https://github.com/apache/arrow-datafusion/issues/9230

**Comment by alamb** [comment]
I believe that @Ted-Jiang  implemented this in https://github.com/apache/datafusion/pull/9989 + https://github.com/apache/datafusion/pull/10051 so closing this issue
