### ISSUE TITLE
Creating dataframe with Recordbatch using pyarrow.Table.to_batches gives "type16 not valid error" when schema includes date32[day] type

### ISSUE THREAD

**Issue by preetijoshi-womply** [apache/datafusion#949]
**Describe the bug**
I want to create a datafusion dataframe using an in memory pyarrow table which has a pa.date32[day] field.. But while doing so i am getting schema error. Saying type 16 not supported.

**To Reproduce**
import datafusion
import pyarrow
import datetime

ctx = datafusion.ExecutionContext()

batch = pyarrow.RecordBatch.from_arrays(
    [pyarrow.array([1, 2, 3]), pyarrow.array([datetime.date(1970, 1, 1),datetime.date(1970, 1, 2),datetime.date(1970, 1, 3)])],
    names=["a", "b"],
)
df = ctx.create_dataframe([[batch]])

**Expected behavior**
A dataframe should be created with or without date column

**Additional context**
pa_table.schema gives the following:
"a: string
b: date32[day]

**Comment by drauschenbach** [comment]
This issue appears to have been resolved.


```python
import datafusion
import pyarrow
import datetime

ctx = datafusion.SessionContext()

batch = pyarrow.RecordBatch.from_arrays(
    [pyarrow.array([1, 2, 3]), pyarrow.array([datetime.date(1970, 1, 1),datetime.date(1970, 1, 2),datetime.date(1970, 1, 3)])],
    names=["a", "b"],
)
df = ctx.create_dataframe([[batch]])


>>> print(df)
DataFrame()
+---+------------+
| a | b          |
+---+------------+
| 1 | 1970-01-01 |
| 2 | 1970-01-02 |
| 3 | 1970-01-03 |
+---+------------+


>>> print(df.schema())
a: int64
b: date32[day]
```

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
