### ISSUE TITLE
Move Atan, Atan2, Acosh, Asinh, Atanh to datafusion-functions

### ISSUE THREAD

**Issue by Tangruilin** [apache/datafusion#9514]
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/arrow-datafusion/issues/9285 the Atan, Atan2, Acosh, Asinh, Atanh  datetime functions should be migrated to the new datafusion-functions crate in the new structure

### Describe the solution you'd like

Functions are migrated to the new crate and use the new patterns as described in https://github.com/apache/arrow-datafusion/issues/9286 & https://github.com/apache/arrow-datafusion/pull/9216,

**Comment by Tangruilin** [comment]
take

**Comment by jonahgao** [comment]
These functions have been moved to 

https://github.com/apache/datafusion/blob/ad2b1dcac8168906e4444527320d3139a1a2ea5b/datafusion/functions/src/math/mod.rs#L46
