### ISSUE TITLE
Add a `AggregateUDFImpl::simplfy()` API

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#9526]
### Is your feature request related to a problem or challenge?

For the same reasons as described for `ScalarUDFImpl` on https://github.com/apache/arrow-datafusion/issues/9289 we should allow user defined aggregates to provide simplification rules 

### Describe the solution you'd like

Add `AggregateUDFImpl::simplify`, following the model @jayzhan211  made in 
 https://github.com/apache/arrow-datafusion/pull/9304

**Comment by alamb** [comment]
Thanks @yyy1000  -- I think the first thing to do would be to pick an example to deonstrate how it works

Perhaps you could implement a case to simplify `COUNT(NULL)` to  `0` or something?

**Comment by yyy1000** [comment]
Ok! I will try it
