### ISSUE TITLE
Add a `WindowUDFImpl::simplfy()` API

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#9527]
### Is your feature request related to a problem or challenge?

For the same reasons as described for `ScalarUDFImpl` on https://github.com/apache/arrow-datafusion/issues/9289 we should allow user defined window functions to provide simplification rules 

### Describe the solution you'd like

Add `WindowUdfImpl::simplify`, following the model @jayzhan211  made in 
 https://github.com/apache/arrow-datafusion/pull/9304

**Comment by guojidan** [comment]
take

**Comment by guojidan** [comment]
let me try 😄

**Comment by alamb** [comment]
Thanks! My suggestion is to start this project with an example of how to use simplify (aka write the test first)
