### ISSUE TITLE
Evaluate pyo3 abi3 wheel limitations for datafusion python binding

### ISSUE THREAD

**Issue by houqp** [apache/datafusion#955]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

There are some documented limitations in pyo3 for abi3 wheel support, see https://pyo3.rs/v0.13.2/building_and_distribution.html#missing-features. As a follow up for https://github.com/apache/arrow-datafusion/issues/921, we should look into them to see if datafusion is impacted.

**Comment by drauschenbach** [comment]
This issue seems obsolete, now that `datafusion-python` as relocated to an external git repo.

**Comment by andygrove** [comment]
Closing this. Thanks @drauschenbach.
