### ISSUE TITLE
Support build right with HashJoin in DataFusion

### ISSUE THREAD

**Issue by viirya** [apache/datafusion#9603]
### Is your feature request related to a problem or challenge?

See the discussion at Comet: https://github.com/apache/arrow-datafusion-comet/pull/194#discussion_r1521912155

> Yea, in DataFusion, only left side could be the build side. But in Spark, the HashJoin operator has a build side parameter to indicate which side is build side. The operator will do right thing accordingly internally. So currently we cannot just create a DataFusion HashJoin operator with right side as build side.

> It can be swapped between left and right side, only if we also swap outputs and also column binding in joining keys and joining filter. I'd like to relax the build side constraint in DataFusion instead of doing the swap in Comet.

### Describe the solution you'd like

HashJoin supports build right option.

**Comment by metesynnada** [comment]
Is there a technical problem with swapping join sides in Comet?

**Comment by viirya** [comment]
No, I think technically we can do the swapping on joining keys, join filter, join output, etc. in Comet. I think it would be good if we can make DataFusion HashJoin more flexible to remove this constraint.

**Comment by metesynnada** [comment]
Got it, I was figuring out if this could be a blocker.

**Comment by comphead** [comment]
> No, I think technically we can do the swapping on joining keys, join filter, join output, etc. in Comet. I think it would be good if we can make DataFusion HashJoin more flexible to remove this constraint.

That sounds cool, and such initiative will help DF to support its own join order hints instead of hardcoded join order

**Comment by edmondop** [comment]
@comphead how would this work? do you think we should extend the SQL parser to support hints?

**Comment by viirya** [comment]
I think this is not related to SQL parser. The SQL query looks the same. But in Spark, it can decide hash side based on relation statistics or the hint given by users.

**Comment by viirya** [comment]
I will work on this.
