### ISSUE TITLE
[question]when using the datafusion reading csv in rust project,  it went wrong 

### ISSUE THREAD

**Issue by colommar** [apache/datafusion#9652]
part of my rust project
```let ctx = SessionContext::new();
  ctx.register_csv("example", "src/b.csv", CsvReadOptions::new().has_header(true)).await?;
  let df = ctx.sql("select * from example").await?;
  df.show().await?;
```
top 3 lines of `src/b.csv`
```
date,time,name,num,target,money,pay_type,status
2024.03.15,12:02:02,POS消费,20240315115719080408,A食堂1楼大餐厅,14.50,现金,交易成功
2024.03.15,10:03:20,POS消费,20240315100247068511,北区西点房,4.00,现金,交易成功
```
error
```
Error: ArrowError(ParseError("Error while parsing value 20240315100247068511 for column 3 at line 2"), None)
error: process didn't exit successfully: `target\debug\rg.exe` (exit code: 1)
```
Could anyone try to help me to figure this problem out?

**Comment by haohuaijin** [comment]
related to https://github.com/apache/arrow-datafusion/issues/3174

**Comment by colommar** [comment]
> related to #3174, maybe you can avoid this problem by specifying the schema instead of letting Datafusion infer the schema.

I think maybe surface the underlying error here is a good choice.
As I have found the in [this](https://github.com/apache/arrow-rs/blob/03d0505fc864c09e6dcd208d3cdddeecefb90345/arrow-csv/src/reader/mod.rs#L889-L917), Could you help me find which issue to contribute this?

**Comment by haohuaijin** [comment]
the related issue in arrow-rs is https://github.com/apache/arrow-rs/issues/2580

**Comment by alamb** [comment]
I think the question was answered so we can close the issue
