### ISSUE TITLE
Release DataFusion `37.1.0` (non breaking API release)

### ISSUE THREAD

**Issue by alamb** [apache/datafusion#9904]
### Is your feature request related to a problem or challenge?

@universalmind303 had a request for inclusion in DataFusion 37.0.0 https://github.com/apache/arrow-datafusion/issues/9682 that may miss the release: https://github.com/apache/arrow-datafusion/issues/9900#issuecomment-2030482986

### Describe the solution you'd like

Make a `37.1.0` release with non breaking changes

### Potential content: 
- [x] https://github.com/apache/arrow-datafusion/issues/10029
- [x] https://github.com/apache/arrow-datafusion/issues/9925
- [x] https://github.com/apache/arrow-datafusion/issues/10042
- [x] https://github.com/apache/arrow-datafusion/issues/9900
- [x] https://github.com/apache/arrow-datafusion/issues/9893

### Backport PRs
- [x] https://github.com/apache/arrow-datafusion/pull/10103
- [x] https://github.com/apache/arrow-datafusion/pull/10104
- [x] https://github.com/apache/arrow-datafusion/pull/10105
- [x] https://github.com/apache/arrow-datafusion/pull/10107
- [x] https://github.com/apache/arrow-datafusion/pull/10123

**Comment by alamb** [comment]
cc @andygrove

**Comment by alamb** [comment]
I started collecting some potential fixes for this release (basically regressions) in the description

**Comment by andygrove** [comment]
Thanks @alamb. I have more bandwidth now to help support maintenance releases. Do you have a target date in mind for 37.1.0?

**Comment by alamb** [comment]
> Thanks @alamb. I have more bandwidth now to help support maintenance releases. Do you have a target date in mind for 37.1.0?

Thank you !

I didn't have any date in mind -- how about we try for early next week (of April 15)? I am happy to do the backport PRs -- should we make a maintenance branch? Or maybe we should use https://github.com/apache/arrow-datafusion/tree/branch-37 🤔 ?

**Comment by andygrove** [comment]
> > Thanks @alamb. I have more bandwidth now to help support maintenance releases. Do you have a target date in mind for 37.1.0?
> 
> Thank you !
> 
> I didn't have any date in mind -- how about we try for early next week (of April 15)? I am happy to do the backport PRs -- should we make a maintenance branch? Or maybe we should use https://github.com/apache/arrow-datafusion/tree/branch-37 🤔 ?

That sounds good. My plan was to use `branch-{version}` for any maintenance releases, following the pattern used by Apache Spark., so we would release any 37.x.x releases from branch-37.

**Comment by alamb** [comment]
> That sounds good. My plan was to use branch-{version} for any maintenance releases, following the pattern used by Apache Spark., so we would release any 37.x.x releases from branch-37.

Makes sense -- I will do that.

I'll plan to make some backport PRs tomorrow morning

**Comment by ion-elgreco** [comment]
Heey @alamb, when are you planning this release? :)

**Comment by alamb** [comment]
> Heey @alamb, when are you planning this release? :)

@ion-elgreco  I hope the end of this week -- I am going to do the backporting now

**Comment by alamb** [comment]
I made the following 4 backport PRs: https://github.com/apache/arrow-datafusion/pull/10103, https://github.com/apache/arrow-datafusion/pull/10104, https://github.com/apache/arrow-datafusion/pull/10105, https://github.com/apache/arrow-datafusion/pull/10107

I will also send a note to the dev list and on slack/discord in case anyone else wants to backport additional items

**Comment by Omega359** [comment]
Note that #9900 didn't in fact make all the udf's public - the string and unicode modules do not in fact have the modules changed to pub nor is default implemented for the functions that I spot checked.

**Comment by alamb** [comment]
> Note that #9900 didn't in fact make all the udf's public - the string and unicode modules do not in fact have the modules changed to pub nor is default implemented for the functions that I spot checked.

Thank you -- moved the conversation to https://github.com/apache/arrow-datafusion/pull/10107#issuecomment-2059991319

**Comment by alamb** [comment]
We also added https://github.com/apache/arrow-datafusion/pull/10123 to this release, to reduce debug stack frame sizes. Thanks @sergiimk and @devinjdangelo

**Comment by alamb** [comment]
I am now beginning the process of creating a release candidate

**Comment by alamb** [comment]
Here is a PR with the changelog / version update: https://github.com/apache/arrow-datafusion/pull/10128

```shell
./dev/release/generate-changelog.py apache/arrow-datafusion 37.0.0 branch-37 > dev/changelog/37.1.0.md
```

**Comment by progval** [comment]
Would https://github.com/apache/arrow-datafusion/pull/9770 and https://github.com/apache/arrow-datafusion/pull/9969 be eligible for backport too?

**Comment by alamb** [comment]
> Would #9770 and #9969 be eligible for backport too?

@progval  -- If it was a regression or a serious bug I think it would be a good idea to backport. In this case I can't remember the exact sequence of events (as in some types were enabled, and then disabled, but I am not sure what was in the 37.0.0 release)

What exactly do you think we should backport?

**Comment by progval** [comment]
int8/int16/int32/int64 were enabled for a while. #9770 enabled for uint8/uint16/uint32/uint64, then #9969 disabled for int8/int16/uint8/uint16.

So backporting #9770 adds a non-breaking feature and a regression; and backporting #9969 immediately fixes that regression plus an existing bug.

**Comment by alamb** [comment]
I see -- so from that perspective 37.0.0 and earlier have a bug where `int8/int16` bloom filters can incorrectly filter out incorrect answers. 

I did some archeology and it seems like the in8/int16 bloom filter support was added in https://github.com/apache/arrow-datafusion/pull/7821 / shipped as part of https://github.com/apache/arrow-datafusion/blob/main/dev/changelog/33.0.0.md 

(aka the bug has been present for several months/releases yet)

Thus I think it would be useful to fix but I also don't think it is critical to include in 37.1.0

**Comment by alamb** [comment]
Unfortunately it appears I made an error and forgot to update the release version in this RC

I have started a new thread[1] for a second RC https://lists.apache.org/thread/0md6qyhw0hody8p0v9wddvt7vo8r8z2x

**Comment by alamb** [comment]
The release was approved and published to crates.io: https://lists.apache.org/thread/v6y745zyljoor471964l3tfq8m37lzh2

The release is available here:
  https://dist.apache.org/repos/dist/release/arrow/arrow-datafusion-37.1.0

It has also been released to crates.io: https://crates.io/crates/datafusion/37.1.0

Thank you to everyone 🙏

**Comment by ion-elgreco** [comment]
Thanks @alamb!

I tried it with 37.1.0 in delta-rs, but we still get this error: ` internal error: entered unreachable code: NamedStructField should be rewritten in OperatorToFunction`, wasn't this regression fixed?

**Comment by ion-elgreco** [comment]
@alamb this is the code:       

```
  let (table, _metrics) = DeltaOps(table)
            .delete()
            .with_predicate("props['a'] = '2021-02-02'")
            .await
            .unwrap();

```

**Comment by alamb** [comment]
Filed https://github.com/apache/datafusion/issues/10181 to track the issue with `internal error: entered unreachable code: NamedStructField should be rewritten in OperatorToFunction`
