### ISSUE TITLE
Enable the UDF function to collect its metrics.

### ISSUE THREAD

**Issue by JasonLi-cn** [apache/datafusion#9993]
### Describe the solution you'd like

I have a UDF function `foo`, and I want to track the number of rows it processes and the time it takes, but currently, I am unable to do so.

**Comment by alamb** [comment]
> I have a UDF function foo, and I want to track the number of rows it processes and the time it takes, but currently, I am unable to do so.


I wonder if you could do this with a rewrite that replaced instances of your UDF with instances that were annotated to collect statistics 🤔

**Comment by JasonLi-cn** [comment]
Thank you @alamb for your answer, that's a good idea. :grin:
